### ISSUE TITLE
(🐞) Do not use `repr` to format paths shown in console

### ISSUE THREAD

**Issue by KotlinIsland** [pypa/pipx#1003]
```
> pipx install ...
...
⚠️  Note: 'C:\\Users\\amongus\\.local\\bin' is not on your PATH environment variable.
...
```

There shouldn't be double backslashes here, single only.

**Comment by uranusjr** [comment]
Not really a bug per-se (the path works!) but more of a cosmetic issue. Pull requests are welcomed of course.
