### ISSUE TITLE
Installing multiple local packages in the same virtual environment?

### ISSUE THREAD

**Issue by pablob127** [pypa/pipx#1004]
This is more a question rather than a feature request, as there may be ways to do what I want but I could not find them.

I have developed a number of packages and command line tools to deal with some equipment and data I have. I have packaged these tools and libraries into a number of Python packages that I keep local (I don't think I will upload those to PyPI, they are very local and not relevant to most of the world). These packages have inter-dependencies (i.e. I have a "hardware drivers" package on which all the "data acquisition" packages depend). All packages also provide CLI interfaces that can be useful at times, some also have GUI interfaces.

I used to install all these packages with pip and everything worked fine, I could use my CLI (and GUI) tools in the system with no problems. Now Debian (my Linux distribution of choice) declared the system Python to be externally managed so I cannot install these local packages with pip, to have them available in the system, anymore.

The switch to an externally managed Python is good, in my opinion, so I want to find a way to make my packages to work without having to break this (that is, I'd prefer to avoid using 'pip --break-system-packages' if possible).

Would it be possible to use pipx for this, or would this require a new feature? I would like to install all the local packages into the same virtual environment, not one enviroment for each, while keeping system-wide availability for the CLI and GUI tools.

Thanks!

**Comment by chrysle** [comment]
This is what `pipx inject` is for.
