### ISSUE TITLE
pipx installation instructions on Windows don't seem to work

### ISSUE THREAD

**Issue by markmelvin** [pypa/pipx#1007]
I love `pipx` and am recommending it to people using my packages, however the first two people that tried to install it failed miserably.

These people both have Windows 10, and Python 3.x. I believe Python was installed from the Python installer for all users and resides in:

```
<USER_folder>\AppData\Local\Programs\Python\Python311-32\python.exe
``` 

Installing `pipx` with the recommended command `python -m pip install --user pipx`, installs `pipx` into  `<USER_folder>\AppData\Roaming\Python\Python3x\Scripts` . Then going into that folder and running `pipx ensurepath` doesn't seem to do anything to put that folder on the PATH. Thus, from then on, running `pipx` just fails to find the executable.

For one user, we manually hacked their PATH to add the right folder to it. For the other user, we removed `pipx` and installed it without the `--user` flag to install it into their Local folder as opposed to the Roaming one and it works.

But the out-of-box experience for both users was that installing `pipx` didn't work and I needed to hold their hand to figure out what went wrong. Not sure, but this may be related to https://github.com/pypa/pipx/issues/978

**Comment by gaborbernat** [comment]
> In theory this should be fixed once the next version of the userpath library gets published.
