### ISSUE TITLE
Set up versioning for documentation

### ISSUE THREAD

**Issue by chrysle** [pypa/pipx#1017]
**How would this feature be useful?**

This should help users to keep up to date with development changes and changes between the versions.

**Describe the solution you'd like**

An external tool can be set up in the configuration. See the [documentation of the Material docs theme](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/) for a suggestion.

**Describe alternatives you've considered**

Keeping the workflow as is, which means deploying the docs every time a new release is published.

**Comment by uranusjr** [comment]
IMO showing versioned docs encourages users to keep using the old versions and not keeping up with the latest stable. This is the opposite of what we want.

**Comment by chrysle** [comment]
Your objection sounds reasonable. But  it is also possible to just differ between `latest` and `stable` version, and set up docs deploy via CI for `latest` for every push to the main branch. Does this sound like an option?

**Comment by uranusjr** [comment]
Sounds reasonable if the stable version is the default.

**Comment by webknjaz** [comment]
I think this is something RTD provides by default.

**Comment by gaborbernat** [comment]
Yes. Because RTD does it by default should be the case going ahead.
