### ISSUE TITLE
Add the ability to prompt after a pipx install to add the PATH of the project to the system ? (Y/n)

### ISSUE THREAD

**Issue by pzim-devdata** [pypa/pipx#1019]
**How would this feature be useful?**

No needs to create the PATH
**Describe the solution you'd like**

If pipx, after an installation, describe : Your project is not in the PATH, pipx should prompt if we want to add it to the PATH permanently.
**Describe alternatives you've considered**

An alternative could be that pipx show us a command line to temporarily and/or permanently add the project to the PATH

**Comment by dukecat0** [comment]
> If pipx, after an installation, describe : Your project is not in the PATH, pipx should prompt if we want to add it to the PATH permanently.

Why would people install a package and then not add it to PATH?

**Comment by pzim-devdata** [comment]
> > If pipx, after an installation, describe : Your project is not in the PATH, pipx should prompt if we want to add it to the PATH permanently.
> 
> 
> 
> Why would people install a package and then not add it to PATH?

I agree. It would be nice if pipx automatically add to the PATH instead of telling : "it's not in the PATH". But it would be better to ask before to add to the PATH because sometimes there is a local package already installed.

**Comment by webknjaz** [comment]
It's a can of worms, because it's usually integrated on the userspace level and is shell dependent + people set up their shells differently, except for installing through the downstream packages that could add such things on system levels.
For example, I set up such things via the oh-my-zsh plugin system.

**Comment by gaborbernat** [comment]
IMHO out of scope of this project.

**Comment by sudoshindo** [comment]
Question, for clarification.

If I use other shells like zsh, will I need to manually modify PATH because `pipx ensurepath` does not account for such shells??
