### ISSUE TITLE
pipx inject --include-binaries removes environment if no binaries are found

### ISSUE THREAD

**Issue by marcolussetti** [pypa/pipx#1026]
**Describe the bug**
When `pip inject --include-binaries <main-package> <new-package>` references a new-package that does not have binaries, the entire venv is deleted with no warning.

**How to reproduce**
This shows the behaviour first with --include-binaries on a package with no binaries (showing the problem), and after with a package with binaries (showing the normal result)
![image](https://github.com/pypa/pipx/assets/15794684/c3664300-c1fe-438b-9e2b-497a33c2773d)

**Expected behavior**
The same warning about no included binaries should be emitted, but the virtual environment should not be deleted.

**Comment by marcolussetti** [comment]
I have now realized that Ubuntu focal, 20.04, is shipping quite an old version of `pipx`, so entirely possible this has been fixed since, but I wasn't able to find a bug referencing this. I will leave this up but I assume this will need to be closed as likely this was fixed long ago :)

**Comment by dukecat0** [comment]
Just confirmed that this was fixed.
