### ISSUE TITLE
pipx installing older version of package

### ISSUE THREAD

**Issue by MSBlueVn** [pypa/pipx#1028]
**Describe the bug**
When I install gimme-aws-creds for example, it installs 2.4.0 where the latest version on PyPi is 2.7.0.

**How to reproduce**
pipx install gimme-aws-creds, it will install 2.4.0

**Expected behavior**
It should install 2.7.0 which is the latest one on PyPi.

**Comment by MSBlueVn** [comment]
Just to add, this is on Windows, and they are blocked by winrt being outdated.

**Comment by dukecat0** [comment]
@MSBlueVn Please provide the output of `pipx install gimme-aws-creds --verbose`.

**Comment by MSBlueVn** [comment]
Hello, since Okta will phase out 3rd party apps that use API soon, we have moved on to another method for authenticating. I will close this issue.
