### ISSUE TITLE
(docs) What does --include-deps do?

### ISSUE THREAD

**Issue by jimboolio** [pypa/pipx#1030]
In short I'm requesting that the --include-deps flag description is reworded so that it explains what will be changed compared to running pipx install without the flag.

### Background

I'm quite familiar with Fedora and Debian package management. My assumption is that a package management handles the installation of dependencies, but the flag `--include-deps` suggests that it would install packages specified in a `pipx install`. How are those selected? For example if I install ansible, will this flag include any package that claims to depend on ansible, which would pose a security risk or is the list of dependent packages defined by ansible devs?

Probably obviously I'm not familiar with python dependency management

---

 Also `--python PYTHON` flag description "Must be v3.6+" would be more clearly understandable as "Must be v3.6 or above"

**Comment by dukecat0** [comment]
> My assumption is that a package management handles the installation of dependencies

pipx handles them as well, but it just doesn't append them to PATH if `--include-deps` is not passed.

> the list of dependent packages defined by ansible devs?

This one. You can see the list here: https://github.com/ansible/ansible/blob/f3a15a4a95d011741885942cad7187f1f7c572fe/setup.py#L19

**Comment by dukecat0** [comment]
> Also --python PYTHON flag description "Must be v3.6+" would be more clearly understandable as "Must be v3.6 or above"

It's changed to `Requires Python 3.8 or above.` recently.

**Comment by sigma67** [comment]
The changelog has an explanation: https://github.com/pypa/pipx/blob/238ae43bf4fd1797154ee07a40d045b0e81757e8/CHANGELOG.md?plain=1#L290

I agree that the name of the flag is confusing and that the current wording on the CLI help is not great. It should state what it does, namely to install binaries of dependencies and expose them globally. Something like ``--include-dep-binaries``, perhaps. Although that is not very concise, so I'm sure there are better suggestions.

**Comment by courtarro** [comment]
Might I suggest `--include-deps-in-path` ?
