### ISSUE TITLE
Add the ability to install from requirements.txt files

### ISSUE THREAD

**Issue by colrobloxkid69420** [pypa/pipx#1031]
**How would this feature be useful?**

I mean, who would like to manually type all the requirements for a project, or use their skills with Linux to think of some command which would pass in each line to pipx one at a time. Either way this is a waste of time.

**Describe the solution you'd like**

Something like pip's "-r"

**Describe alternatives you've considered**

Using pip in venv. It did kinda work but I had another unrelated issue ("EnvironmentError: [Errno 28] No space left on device")

**Comment by uranusjr** [comment]
pipx wants a “main” app that it exposes executable(s). What should a requirements.txt expose? You will need to better describe the expected workflow and result.

**Comment by colrobloxkid69420** [comment]
I don't really get your question. What did you mean by "exposes executables"?

The workflow + result (if I understood what you meant by those right) should be that it takes each line of the requirements.txt file and initiates a `pipx install {the contents of that line}` on it or something similar, just like [pip's -r argument](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-r)

**Comment by chrysle** [comment]
> The workflow + result (if I understood what you meant by those right) should be that it takes each line of the requirements.txt file and initiates a `pipx install {the contents of that line}` on it or something similar, just like [pip's -r argument](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-r)

We have a similar feature request at #934, but for `pipx inject`.

**Comment by uranusjr** [comment]
> We have a similar feature request at #934, but for `pipx inject`.

Having a requirements.txt for `install` and `inject` is fundamentally different since the latter installs everything into one existing environment, while the former needs to create one environment for each entry. But the request for `install` seems quite low in utility to me, since it is really only useful for populating a new machine, which is not that big a use case.

> For `pipx` to become much more usable for me, I would like to have a per project tooling option too.

pipx is not particularly useful for per-project tooling since tools for each project differ and (from my experience) more often than not conflict at some point. There are tools more suitable for this use case, such as pre-commit, tox, and nox.

**Comment by FeryET** [comment]
> > We have a similar feature request at #934, but for `pipx inject`.
> 
> Having a requirements.txt for `install` and `inject` is fundamentally different since the latter installs everything into one existing environment, while the former needs to create one environment for each entry. But the request for `install` seems quite low in utility to me, since it is really only useful for populating a new machine, which is not that big a use case.
> 
> > For `pipx` to become much more usable for me, I would like to have a per project tooling option too.
> 
> pipx is not particularly useful for per-project tooling since tools for each project differ and (from my experience) more often than not conflict at some point. There are tools more suitable for this use case, such as pre-commit, tox, and nox.

tox and nox are python testing environments, using them for development environments are hacky. Those are used usually by packages that aim to support multiple python versions, which usually is not the case for me or people who are developing python applications (and are containerizing it).

My current solution is to put a `requirements.tools.txt` (or put an optional dependency field called `tools`) in every project that I manage to make sure the developers are using the same tools and same versions.

Pre-commit is good for code qa, but it still has a different objective than `dev environment` tooling.

It will be much nicer for me if I could somehow automate this via pipx by using a notion like namespacing. For example I'm using tools like `dvc`, `black`, `ruff`, `pre-commit` and etc in all of my repositories, and I want to make sure that the new developers also have these. I can define a pipx namespace for my company and share it across developers with namespace wide configs. This can also be beneficial towards creating CI pipelines for such tools.

**Comment by uranusjr** [comment]
Err… you might want to revise your mental model. Both tox and nox include version-agnostic development workflow tools like mypy and flake8 in their examples. But okay, if you think they are for testing only, I’ll just say pipx is only for global, non-project tools, and politely reject your use case.

**Comment by daum3ns** [comment]
plus 1 on this as this is very important...

pipx is entirely useless without this option, as basically every  project out there will tell you to install the requirements.txt.... 

i mean look at this:
![2023-11-07 11_27_26-WAM Daily _ Microsoft Teams classic](https://github.com/pypa/pipx/assets/23260410/a9da9e62-2606-4d9d-b4ad-f05a2b0251e8)


- python tells me to use pipx
- it then tells me to use the -r option
- but when i do this it is an "unrecognized argument"

**Comment by colrobloxkid69420** [comment]
> plus 1 on this as this is very important...
> 
> pipx is entirely useless without this option, as basically every project out there will tell you to install the requirements.txt....
> 
> i mean look at this: ![2023-11-07 11_27_26-WAM Daily _ Microsoft Teams classic](https://user-images.githubusercontent.com/23260410/281006897-a9da9e62-2606-4d9d-b4ad-f05a2b0251e8.png)
> 
>     * python tells me to use pipx
> 
>     * it then tells me to use the -r option
> 
>     * but when i do this it is an "unrecognized argument"

you should just make a venv most of the time.

`python -m venv venv` to create the venv and then `source ./venv/bin/activate` to activate it, then just use pip as usual.

**Comment by gaborbernat** [comment]
> pipx is not particularly useful for per-project tooling since tools for each project differ and (from my experience) more often than not conflict at some point. There are tools more suitable for this use case, such as pre-commit, tox, and nox.

I agree here. pipx is not in business of custom project envs, and supporting `requirements.txt`.

**Comment by armandas** [comment]
I can't understand what's so bad about taking a `requirements.txt` and simply doing an `install` on each line?
Many people switch to `pipx` from `pip` due to PEP 668 and supporting `-r` parameter would make that transition that much more seamless...

**Comment by ror6ax** [comment]
In fact, the functionality seems to kinda alredy exist in the install-all subcommand. The only problem for me is that it only takes in json from `pipx list --json' that leaks too many host specific details.

All I want is to have a list of things pipx needs to install in one place. Latest by default, fixed versions if provided. Like Brewfile does. Like requirement.txt does.

**Comment by gsemet** [comment]
Hi. I would like to know if there is a solution for installing a wheel with the exact dependencies version this wheel has been validated with (typically by providing a frozen requirement.txt) ?
