### ISSUE TITLE
Deterministic builds

### ISSUE THREAD

**Issue by dudicoco** [pypa/pipx#1050]
**How would this feature be useful?**
pip by design is non-deterministic (https://github.com/pypa/pip/issues/5102), this means that we could get inconsistencies (and possibly bugs) in the resulting application when building a package of a specific version at different times.

**Describe the solution you'd like**
It would be great if applications built by pipx could somehow be deterministic (byte for byte identical) when built at different times.

I'm not sure how this could be achieved without adding some kind of a registry with lock files created for all applications, but perhaps someone can propose a more elegant solution for this problem.

**Comment by uranusjr** [comment]
pipx is only a wrapper and does not perform any building by itself, so this will be fixed and only fixed if the underlying tools obtain the ability. Closing since there is nothing for pipx to act on this topic.

**Comment by dudicoco** [comment]
@uranusjr by "building" I mean fetching pip dependencies and transitive dependencies.
pip can install dependencies according to a lock file (`pip freeze > requirements.txt`), however pipx cannot do that which is the main missing functionality.
