### ISSUE TITLE
 You need Cython to build URH's extensions!

### ISSUE THREAD

**Issue by tomcass240** [pypa/pipx#1054]
**Describe the bug**
Trying to install urh using pipx install urh. I get the message 

```
```
Fatal error from pip prevented installation. Full pip output in file:
    /home/z/.local/pipx/logs/cmd_2023-09-06_22.54.24_pip_errors.log

pip seemed to fail to build package:
    urh

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: metadata-generation-failed
```

cat /root/.local/pipx/logs/cmd_2023-09-06_22.51.35_pip_errors.log
PIP STDOUT
----------
Collecting urh
  Using cached urh-2.9.4.tar.gz (3.0 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      You need Cython to build URH's extensions!
      You can get it e.g. with python3 -m pip install cython.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**How to reproduce**
Try to install urh with pipx on Debian. Python3 and Cython3 both installed using package manager.

**Expected behavior**
Installed correctly as Cython is installed. 

If I try typing sudo pip3 install urh

I get this error message: 
```

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.


```

**Comment by uranusjr** [comment]
This is from the package you are trying to install, and you need to ask maintainers of that project for assistance.

**Comment by tomcass240** [comment]
I managed to get it installed using other commands so I don't understand how that's the problem. I followed instructions for installing in a python virtual environment and the program worked but couldn't access any of my libraries to support my devices (like RTL-SDR).
