### ISSUE TITLE
"No matching distribution found" without specifying `--python=$(which python)` 

### ISSUE THREAD

**Issue by connerxyz** [pypa/pipx#1055]
**Describe the bug**

`pipx install my-package` claims that are are no matching versions, even though there are several Python versions that matches the reported range.

Here's the output with Python 3.9.13 active. (I have versions 3.7-3.10 installed.)

```
PIP STDOUT
----------
Looking in indexes: https://corporate-artifactory

PIP STDERR
----------
ERROR: Ignored the following versions that require a different python version: 2.2.0 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement my-package (from versions: none)
ERROR: No matching distribution found for my-package
```

I **_can_** install this same package (under all Python versions in range) using `pip`, no problem. It's only a problem with `pipx`.

Further, it does work if I specify a Python version in range.

```
pipx install my-package --python=3.9.13
```

**How to reproduce**

I'm not sure, honestly. I have other similar packages that `pipx` has no problem installing.

I'm using `pyenv` to set Python versions and `poetry` + `pyproject.toml` to create and manage `my-package`.

```
[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"
```

**Expected behavior**

`pipx` should find valid, compatible versions and install it.

**Comment by uranusjr** [comment]
I have a hunch the pipx installation isn’t actually tied to the version you think it is. Try running the command with `--verbose` for more output.
