### ISSUE TITLE
Unicode symbols / Terminal ignored

### ISSUE THREAD

**Issue by buhtz** [pypa/pipx#1057]
What you see here is Debian 12 running in tmux via SSH shell. The SSH client is a Windows Remote Desktop window.

![image](https://github.com/pypa/pipx/assets/11861496/897bb9a1-05f3-45cf-917a-6c540e7a6ebe)

pipx should respect the terminal not using fancy icons.

**Comment by chrysle** [comment]
We have a function checking if the icons are supported by the operating system:

https://github.com/pypa/pipx/blob/271d0f1b4938777f6e2bce99879c4fe586d4265c/src/pipx/emojis.py#L15-L23

Most likely it's an issue with the font.

**Comment by buhtz** [comment]
But when I install another font then another application in that terminal do not show its characters correctly.
Just refuse to use such icons.

**Comment by chrysle** [comment]
You could set the environment variable `USE_EMOJI` to _false_ per default when logging into your shell.

**Comment by buhtz** [comment]
Close as duplicate.
