### ISSUE TITLE
Move the docs to a pypa.io subdomain?

### ISSUE THREAD

**Issue by webknjaz** [pypa/pipx#1058]
**How would this feature be useful?**

I think it's a good idea to have PyPA projects with the same URL scheme.. For example, there's https://hatch.pypa.io, https://setuptools.pypa.io, https://pip.pypa.io.

Plus, shorter URLs are typically easier to type in from memory.

**Describe the solution you'd like**

I thought, it'd be useful to put the docs @ https://pipx.pypa.io.

**Describe alternatives you've considered**

...not doing this?

**Comment by chrysle** [comment]
I've also considered this, and it sounds like a good idea! Don't know who is responsible for domain management, though.

**Comment by webknjaz** [comment]
First, the maintainers should be on board. Changing DNS can be requested from the org admins.

**Comment by dukecat0** [comment]
Seems related to #698?

**Comment by webknjaz** [comment]
Ah, I didn't realize. Well, RTD now allows running arbitrary build commands so what's needed is to copy the nox invocation to its config mostly. Not a biggie.

**Comment by chrysle** [comment]
Great! Off to some migrating, then.

**Comment by webknjaz** [comment]
@dukecat0 sounds like it's time to set up that domain?

**Comment by dukecat0** [comment]
Yes, but I don't have any permission to do this.

**Comment by webknjaz** [comment]
I have access to RTD so I can set up the domain on that side.

And on the DNS level, @di or @ewdurbin should be able to do the same..

Folks, could you point the `pipx.pypa.io` CNAME record to RTD?

**Comment by uranusjr** [comment]
The docs are not on rtd but GitHub Pages. I’ll see if I can change it…

**Comment by webknjaz** [comment]
@uranusjr they are actually on RTD since today. See the recent commits.

**Comment by uranusjr** [comment]
Oh I misunderstood your comment. It’s the other way around, you got rtd set up and is asking for the DNS update.

**Comment by ewdurbin** [comment]
```
$ dig +short pipx.pypa.io
readthedocs.io.
104.17.32.82
104.17.33.82
```

**Comment by chrysle** [comment]
Great, thanks!

**Comment by ewdurbin** [comment]
Repo URL updated.

@webknjaz if you add my user `ewdurbin` in RTD I will configure web hooks as well.

**Comment by ewdurbin** [comment]
@webknjaz Done.

**Comment by ewdurbin** [comment]
Unsubscribing. Please mention again if needed.

**Comment by gaborbernat** [comment]
> * [x]  stick a redirect on GH Pages after that

https://github.com/pypa/pipx/commit/69d6e5efe7d0f7e7dd1cd75ef885c66926fb9033

**Comment by gaborbernat** [comment]
> locate and update any mentions of the old GH Pages URL in the source code, including readme and dist metadata

https://github.com/pypa/pipx/commit/1349fcfbf57c32af2391864346e19547ebb08ea4
