### ISSUE TITLE
ensurepath when zshrc is read-only

### ISSUE THREAD

**Issue by fzakaria** [pypa/pipx#1064]
**Describe the bug**
I use Nix on my machine with Home-manager (https://github.com/nix-community/home-manager) that manages my dotfiles.
My dotfiles, like zshrc, become read-only as they are managed by config.

I tried to run `pipx ensurepath` and it says its successful but the new PATH hasn't taken effect and none of the files have changed.

I suspect this might be a problem with https://github.com/ofek/userpath

**How to reproduce**
Note: `--verbose` doesn't work for ensurepath
```
❯ pipx --version
1.2.0


❯ pipx --verbose ensurepath
usage: pipx [-h] [--version] {install,uninject,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions} ...
pipx: error: unrecognized arguments: --verbose

❯ pipx ensurepath
Success! Added /usr/local/google/home/fmzakari/.local/bin to the PATH environment variable.

Consider adding shell completions for pipx. Run 'pipx completions' for instructions.

Otherwise pipx is ready to go! ✨ 🌟 ✨
❯ echo $PATH
/usr/local/google/home/fmzakari/.nix-profile/bin:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google/home/fmzakari/.zsh/plugins/zsh-syntax-highlighting:/usr/local/google/home/fmzakari/.zsh/plugins/powerlevel10k

```

**Expected behavior**
I expect either my zshrc to have changed and/or my $PATH variable.

**Comment by dukecat0** [comment]
> I suspect this might be a problem with [ofek/userpath](https://github.com/ofek/userpath)

I believe it is. Could you open an issue in [ofek/userpath](https://github.com/ofek/userpath)?
