### ISSUE TITLE
Installed package, but wrong python installation called leads to "Module not found error "

### ISSUE THREAD

**Issue by davibicudo** [pypa/pipx#1067]
**Describe the bug**
After installing azure-cli with pipx on windows, it seems that, when running the main python installation is called instead of the venv's. 

C:\ProgramData\miniforge3\python.exe: Error while finding module specification for 'azure.cli' (ModuleNotFoundError: No module named 'azure')

If I run `az` within C:\Users\USER\.local\pipx\venvs\azure-cli\Scripts it works however (the same if I run activate.bat). 

The issue happens with az, az.bat and azps.ps1 (there is no az.exe). 

It might have something to do with how they set PYTHONPATH in these executables, e.g. az.bat:

```
@echo off
setlocal

SET PYTHONPATH=%~dp0\src;%PYTHONPATH%
SET AZ_INSTALLER=PIP

IF EXIST "%~dp0\python.exe" (
  "%~dp0\python.exe" -m azure.cli %*
) ELSE (
  python -m azure.cli %*
)
```

**Comment by chrysle** [comment]
This seems to be the same issue as in #1062.

**Comment by jcrben** [comment]
I fixed it by downgrading to 1.1.0 🤷‍♂️

**Comment by daviewales** [comment]
This also affects mssql-cli: https://github.com/dbcli/mssql-cli/issues/496.
Related: https://github.com/pypa/pipx/issues/12

**Comment by gaborbernat** [comment]
> This seems to be the same issue as in #1062.
