### ISSUE TITLE
Installing editable project with `scripts` fails

### ISSUE THREAD

**Issue by coldfix** [pypa/pipx#108]
Installing a project that only has a `scripts` entry results in an error `No binaries associated with package XXX.` and removes the installed environment. The same package installed in non-development mode works fine.

As far as I could find `python setup.py develop` leaves no record of the installed script (except for the script itself), and therefore the metadata based detection is destined to fail.

Two plausible fixes that come to mind:

- ask the user before simply removing the virtualenv, they could then manually create the symlinks to binaries
- change the binary detection code such that it diffs for the presence of scripts in `$VIRTUAL_ENV/bin`  before/after installation of each package. This might be overall simpler and more reliable than metadata, but requires that depedencies are installed in separate steps from the main package. If the installation is already performed in such a controlled manner, this solution might be preferrable, otherwise unreasonable.

pipx version: `0.12.3.3`

#### Minimal example:

Command

```
pipx install -e --spec . simple
```

`setup.py`

```python
from distutils.core import setup
setup(name='simple', scripts=['simple'])
```

`simple`:

```python
#! /usr/bin/env python
print("hello world")
```

**Comment by gaborbernat** [comment]
`python setup.py develop` is no longer supported.

**Comment by coldfix** [comment]
Though, the erroneous behaviour still occurs, using same minimal example  from above. just the error message changed to:

> No apps associated with package simple or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
