### ISSUE TITLE
Option for the `list` command not to go out to the internet

### ISSUE THREAD

**Issue by halloleo** [pypa/pipx#1081]
**How would this feature be useful?**

When using pipx while the system has no internet connection, `pipx list` takes an awful long time because before printing teh list of packages it tries to upgrade the shared libraries.

**Describe the solution you'd like**

The main purpose of the `list` command is to list what's there, so if I know I have no internet I should be able to say "_Just give me the list. I don't care about doing other maintenance things._" because these maintenance things won't work in any case.

**Describe the solution you'd like**
An option like `--no-maintenance` or `--dont-update` for the `list` command.

**Comment by Gitznik** [comment]
I've had a quick look at this. From what I can see the only network connections during this command are in the [shared_libs](https://github.com/pypa/pipx/blob/1a3e6adf651d57b4750d7e6cfd5dca90c5080a29/src/pipx/shared_libs.py#L84) utility, that is called during [verify_shared_libs](https://github.com/pypa/pipx/blob/1a3e6adf651d57b4750d7e6cfd5dca90c5080a29/src/pipx/commands/list_packages.py#L98). 

While that step is simple enough to skip when a flag is provided, I'm wondering if there's a good way to verify in a test that the command does not attempt to make any network connections, especially in subprocesses. Happy to hear suggestions. 

I'll work on this this weekend.

**Comment by halloleo** [comment]
Cool. Glad to read the problem happens only in shard_libs. 

Regarding a test: Maybe checking how long the command takes  when it is running without network connection would give an indication: When it takes a time similar to the network timeout duration, it is probably trying to each the network...
