### ISSUE TITLE
pipx show: show information about a single Python app installed with pipx

### ISSUE THREAD

**Issue by sigma67** [pypa/pipx#1085]
**How would this feature be useful?**

I would like to find out basic information about a single installed app, similar to what's shown in ``pipx list``

**Describe the solution you'd like**

``pipx show tox``

```

   package tox 4.6.4, installed using Python 3.10.6
    - tox

```

(potentially further information, but this would suffice for now)

**Describe alternatives you've considered**

The problem with ``pipx list`` is that it shows everything and it makes it hard to find exactly the info I need. It can also take quite some time when a lot of apps are installed

**Comment by dukecat0** [comment]
How about running `pipx list | grep "tox"`? I believe that should print the same output.

**Comment by sigma67** [comment]
It does, but it doesn't solve the caveat with the long runtime when you have a lot of venvs there.

On my machine with 20 venvs:

```
pipx list  0,44s user 0,06s system 96% cpu 0,517 total
```

Also doesn't work on Windows. There's also the bit that users coming from pip (which are many, I'd argue), see `pipx list` and expect and equivalent `pipx show`, knowing how pip works - only to be disappointed.

**Comment by dukecat0** [comment]
Maybe it's related to #640.

**Comment by sigma67** [comment]
Yes, it's the same thing I suppose. Although I provided a bit more context. Either way, I could work on it if there is agreement that it can go in

**Comment by uranusjr** [comment]
Sounds good to me.
