### ISSUE TITLE
pipx crashes when a file named logging.py is in the current directory

### ISSUE THREAD

**Issue by jamescooke** [pypa/pipx#1091]
**Describe the bug**

When a file called `logging.py` exists in the directory that `pipx` is invoked from, `pipx` crashes.

**How to reproduce**

On my Ubuntu 20.04 LTS machine:

```sh
cd $(mktemp -d)
pipx --version
```

```
1.2.0
```

Create a `logging.py` file:

```sh
cat > logging.py
print('hello world')
^d
```

Run pipx:

```sh
pipx --version
```

"hello world" appears, then a crash:

```
hello world
Traceback (most recent call last):
  File "/home/james/.local/bin/pipx", line 5, in <module>
    from pipx.main import cli
  File "/home/james/.local/lib/python3.8/site-packages/pipx/main.py", line 7, in <module>
    import logging.config
ModuleNotFoundError: No module named 'logging.config'; 'logging' is not a package
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 41, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python3/dist-packages/urllib3/util/__init__.py", line 20, in <module>
    from .retry import Retry
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 20, in <module>
    log = logging.getLogger(__name__)
AttributeError: module 'logging' has no attribute 'getLogger'

Original exception was:
Traceback (most recent call last):
  File "/home/james/.local/bin/pipx", line 5, in <module>
    from pipx.main import cli
  File "/home/james/.local/lib/python3.8/site-packages/pipx/main.py", line 7, in <module>
    import logging.config
ModuleNotFoundError: No module named 'logging.config'; 'logging' is not a package
```

**Expected behavior**

pipx is not be affected by the presence of a `logging.py` file in the current directory - it shows the current version and does not crash.

**Checking on docker with py3.12**

I was concerned that this failure might be a consequence of my shaky Ubuntu install in the global environment, so I reproduced it in a docker Python 3.12 image. It's a bit hacky because I've run it as root, but I'm able to get the same crash when trying to install `tox`:

```sh
docker run -it python:3.12 /bin/bash
```

```
root@8facc5020f37:/# python3 -m pip install pipx --user
Collecting pipx
  Downloading pipx-1.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 kB 2.6 MB/s eta 0:00:00
Collecting argcomplete>=1.9.4 (from pipx)
  Obtaining dependency information for argcomplete>=1.9.4 from https://files.pythonhosted.org/packages/1e/05/223116a4a5905d6b26bff334ffc7b74474fafe23fcb10532caf0ef86ca69/argcomplete-3.1.2-py3-none-any.whl.metadata
  Downloading argcomplete-3.1.2-py3-none-any.whl.metadata (16 kB)
Collecting packaging>=20.0 (from pipx)
  Obtaining dependency information for packaging>=20.0 from https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting userpath>=1.6.0 (from pipx)
  Obtaining dependency information for userpath>=1.6.0 from https://files.pythonhosted.org/packages/a2/28/20c7dcdb12681b2e12224184a8a158e5df51feb0c68116cb4b1b991a4aab/userpath-1.9.1-py3-none-any.whl.metadata
  Downloading userpath-1.9.1-py3-none-any.whl.metadata (3.0 kB)
Collecting click (from userpath>=1.6.0->pipx)
  Obtaining dependency information for click from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Downloading argcomplete-3.1.2-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.5/41.5 kB 10.1 MB/s eta 0:00:00
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 7.0 MB/s eta 0:00:00
Downloading userpath-1.9.1-py3-none-any.whl (9.1 kB)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 6.4 MB/s eta 0:00:00
Installing collected packages: packaging, click, argcomplete, userpath, pipx
  WARNING: The script userpath is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pipx is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed argcomplete-3.1.2 click-8.1.7 packaging-23.2 pipx-1.2.0 userpath-1.9.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: pip install --upgrade pip
root@8facc5020f37:/# /root/.local/bin/pipx --version
1.2.0
root@8facc5020f37:/# cat > logging.py
print('hello world')
root@8facc5020f37:/# /root/.local/bin/pipx --version
1.2.0
root@8facc5020f37:/# /root/.local/bin/pipx install tox
hello world
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/local/lib/python3.12/venv/__init__.py", line 17, in <module>
    logger = logging.getLogger(__name__)
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute 'getLogger'

'/usr/local/bin/python3 -m venv --without-pip /root/.local/pipx/venvs/tox' failed
```

I'm probably getting something wrong with "ensurepath" or there's something going on that I'm missing - but hopefully this is helpful 🙏🏻 

I spotted this when I tried to view a Markdown file with [frogmouth](https://github.com/Textualize/frogmouth/) in a project that contained a `logging.py` file and the frogmouth package kept crashing, so this might affect installed packages too.

**Comment by dukecat0** [comment]
I believe that's how Python resolves import, and renaming `logging.py` should fix this issue.

**Comment by jamescooke** [comment]
OK so just to confirm - I'd already found the solution was to move or remove the `logging.py` file while writing up this issue 👍🏻 

Also to confirm, with `frogmouth` installed with pipx, a crash will happen when I try to view a markdown file in the `~/Downloads` directory if a file that collides with a library (stdlib or otherwise) exists in the directory (like `logging.py`, `rich.py`, etc).

So, imagining I've downloaded a file called `rich.py` and a markdown file I now want to view:

```sh
cd Downloads
frogmouth README.md
```

This crashes *after* `rich.py` is executed.

```
Traceback (most recent call last):
  File "/home/james/.local/bin/frogmouth", line 5, in <module>
    from frogmouth.app.app import run
  File "/home/james/.local/pipx/venvs/frogmouth/lib/python3.11/site-packages/frogmouth/app/__init__.py", line 3, in <module>
    from .app import run
  File "/home/james/.local/pipx/venvs/frogmouth/lib/python3.11/site-packages/frogmouth/app/app.py", line 6, in <module>
    from textual import __version__ as textual_version  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/.local/pipx/venvs/frogmouth/lib/python3.11/site-packages/textual/__init__.py", line 6, in <module>
    import rich.repr
ModuleNotFoundError: No module named 'rich.repr'; 'rich' is not a package
```

My concerns are:

* This behaviour is not documented on the pipx docs site as far as I could see.
* An untrusted Python file could be executed on an unsuspecting user's machine - take the `~/Downloads` example above.

What I'm confused about is why the virtualenv created for the pipx-installed package is reading Python files from the current directory - shouldn't this be sandboxed away from the installed package by pipx for safety?

**Comment by pawamoy** [comment]
I can reproduce case 1: pipx invocation have the CWD in `sys.path`, but I cannot reproduce case 2: pipx-installed package invocations have the CWD in `sys.path`.

Meaning:

```bash
cd
touch argparse.py
pipx install frogmouth  # fails!
```

But:

```bash
rm argparse.py
pipx install frogmouth
touch rich.py
echo hello > README.md
frogmouth README.md  # works fine
```

**Comment by pawamoy** [comment]
Actually, looking back at the error I got, and at pipx' `__main__` module (which does not seem to ever add `''` or `'.'` to `sys.path`), the error comes from a layer below:

```console
% pipx install frogmouth
Error: module 'argparse' has no attribute 'ArgumentParser'

'/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.5/bin/python -m venv --without-pip /home/pawamoy/.local/pipx/venvs/frogmouth' failed
```

It's when pipx calls the `python` subprocess that the CWD is probably added to `sys.path`.

**Comment by uranusjr** [comment]
It’s probably safer if we run pip inside a temporary directory instead. That guard against much more potentially malicious setups.

**Comment by pawamoy** [comment]
I tried locally to add `-P` to the subprocess command:

```python
    def create_venv(self, venv_args: List[str], pip_args: List[str]) -> None:
        with animate("creating virtual environment", self.do_animation):
            cmd = [self.python, "-P", "-m", "venv", "--without-pip"]
```

and it seems to fix the issue.

**Comment by jamescooke** [comment]
Thanks for reproducing case 1 @pawamoy 👍🏻 

The reason that case 2 doesn't work is because I've got the following on this machine:

```sh
echo $PYTHONPATH
```
```
/home/james/opt/spark/python/:
```

The trailing colon is adding the current directory to the Python path and that's causing the shadowing of dependencies when running pipx-installed packages, like frogmouth. That's my bad - sorry for any confusion.

When I remove this, I can't reproduce the frogmouth / `rich.py` crash - so that's good news.

**Comment by uranusjr** [comment]
Both `-P` and `PYTHONSAFEPATH` (which is probably easier for pipx’s use case) are only available on Python 3.11 and above, so I don’t think we have much choice but to go with the temp directory method for now. We can add a todo note to migrate to the simpler approach in the future though.

**Comment by ehlewis** [comment]
I would be happy to open this PR, just want to clarify the thought
Are you thinking of running the pip install subprocess out of some randomly generated subdir and then tearing that dir down after subprocess completion?

**Comment by webknjaz** [comment]
> Both -P and PYTHONSAFEPATH (which is probably easier for pipx’s use case) are only available on Python 3.11 and above, so I don’t think we have much choice but to go with the temp directory method for now. We can add a todo note to migrate to the simpler approach in the future though.

I've started adding `-I` to my runpy commands. As in `python -Im pip install`, `python -Im pytest`. It basically resets `sys.path`, counteracting the effect of `-m`. So maybe using `-I` below Python 3.11 is a good fallback for `-E`?

**Comment by webknjaz** [comment]
It's good to add it regardless, since `-m` is what MODIFIES `sys.path` I the first place, even without `$PYTHONPATH` being present in the env.

**Comment by ehlewis** [comment]
I had been testing that as well and it does seem like a clean solution, and also implies -E if available
I'll work on getting this in a PR

**Comment by ehlewis** [comment]
Adding -I adds some unnecessary complication in many cases 
Went with a similar approach as [pawamoy](https://github.com/pawamoy) had pondered, and switched venv creation to run in the same directory as the venv will be placed in. This will isolate the creation from anything that happens to be in the cwd

#1126 was at the same moment as a release, needed to rebase for some changes and opened #1127
