### ISSUE TITLE
Upgrading pipx and apps with a new version of Python

### ISSUE THREAD

**Issue by sourcedelica** [pypa/pipx#1101]
I'm coming from a [Reddit post](https://www.reddit.com/r/Python/comments/17mwpo4/comment/k7qgyth) talking about how to upgrade pipx and it's apps after upgrading Python.   I realize that the various permutations of installation methods of Python, pipx, etc make this a potentially cumbnersome process to document or automate.  This is a request to add some documentation or even a new subcommand for how to upgrade pipx and it's apps using a new version of Python.

**Comment by michjnich** [comment]
I've thought the same thing a few times. 

Suggestion: add an export/import command to pipx, so you can export everything, uninstall pipx, re-install it with the new version of python, then import the packages and auto upgrade them to install using the new python version. 

So, eg. 
```
> python --version
Python 3.11.6
> pipx export
... creates a json file or something
> pip uninstall pipx
... 
<install python 3.12>
...
> python --version 
Python 3.12.1
> pip install pipx 
...
pipx import <optional file name> --upgrade-python
... imports all the packgages in the export file, the upgrade-python flag tells it to ignore any versions that are in the export file and just use the current python version
```

Kind of thinking out loud a little, but I think that would handle most use cases, and also allow people to backup their pipx configuration and easily install it on another machine (something that can be a bit of a pain sometimes if you're injecting packages as well...)

**Comment by gaborbernat** [comment]
Duplicate of https://github.com/pypa/pipx/issues/687

**Comment by SimonHeimberg** [comment]
`pipx reinstall-all` worked for new version of python

(Found command in duplicate. Noted here just as a hint for others.)
