### ISSUE TITLE
Cannot install app with access to system libraries

### ISSUE THREAD

**Issue by rossburton** [pypa/pipx#1108]
I want to install diffoscope from pypi but give it access to the system site-packages because there are some dependencies in there which are not in pypi. Installing it normally with `pipx install` works fine:

```
$ pipx install diffoscope
  These apps are now globally available
    - diffoscope
done! ✨ 🌟 ✨
```

That can't see the libraries in `/usr` however, so I add the required option:

```
$ pipx install  --system-site-packages diffoscope

No apps associated with package diffoscope or its dependencies. If you are attempting to install a library, pipx should not be used.
Consider using pip or a similar tool instead.
```

That doesn't seem right?

**Comment by dukecat0** [comment]
> `pipx install  --system-site-packages diffoscope`

This command works fine on my machine. What's the version of pipx that you are using?

**Comment by rossburton** [comment]
1.2.0.  I'll upgrade, try reinstalling pieces, and seeing what happens.
