### ISSUE TITLE
My system shows block instead of ✨ place when pipx install

### ISSUE THREAD

**Issue by qaqland** [pypa/pipx#1113]
**Describe the bug**

My system shows block instead of ✨ place when pipx install

**Expected behavior**

Anything works well except this. Could we switch to another character or **ASCII code**?

// Maybe this is also one feature request?

**Comment by dukecat0** [comment]
You can set the environment variable `USE_EMOJI`  to 0.

**Comment by qaqland** [comment]
sorry I dont see ENV before, it works.

see also: #376 #1057
