### ISSUE TITLE
feature request: install if not exists else upgrade

### ISSUE THREAD

**Issue by Kamilcuk** [pypa/pipx#1116]
**How would this feature be useful?**
I am integrating some batch scripts, and it would be nice to have it.

**Describe the solution you'd like**
pipx install --upgrade package.

**Describe alternatives you've considered**
pipx install --force package

I've read the documentation and I don't seem to find it. --force seems to reinstall the package if present, would be nice to do nothing if the package is fine, just like pip does.

Thanks for pipx, it's great.

**Comment by chrysle** [comment]
We could also include this functionality in `pipx upgrade`?

**Comment by chrysle** [comment]
> I think `pipx install --upgrade` lines up with `pip install --upgrade`.

Though this was recently rejected.
