### ISSUE TITLE
Requesting more repository rights

### ISSUE THREAD

**Issue by gaborbernat** [pypa/pipx#1119]
@cs01 can you make me admin here so I can set up trusted publishing for PyPI and branch protection? (or any other people with that power, please)

Also needs me to be an owner on pypi to be able to setup this.

**Comment by gaborbernat** [comment]
cc @itsayellow this is now blocking the 1.3.0 release...

**Comment by chrysle** [comment]
Can I also become a maintainer on PyPI?

**Comment by cs01** [comment]
Since the move to PyPA I don’t think I have the ability to grant admin rights. 

I believe @pradyunsg can do this.

**Comment by gaborbernat** [comment]
On the PyPI, though, you can still make me owner 😆 I believe to switch to trusted publishers...

**Comment by gaborbernat** [comment]
@pfmoore @pradyunsg @di can we make me an owner here, and also make @chrysle (I believe @dukecat0 already is, but if not let's fix that). Thanks!

**Comment by cs01** [comment]
On the PyPA pipx admin page, there is “pipx committers” and “pipx team”. Dukecat is a member of both. Bernat was only a member of committers so I added to team. I am not sure if there are other categories I’m not able to view but iirc @pradyunsg has some other access rights that I don’t. 

@gaborbernat i just added you as an admin on the PyPI repo as well as @uranusjr and @pradyunsg. I was listed as “sole owner” 😯. That’s a bad bus factor for a project so widely adopted! 

Thank you all for all the work you are putting into pipx!

**Comment by gaborbernat** [comment]
That's enough, I do not have access to the branch protection rules, I think I need to be at least maintainer on that page:

<img width="936" alt="image" src="https://github.com/pypa/pipx/assets/690238/e2c402bb-0f0e-489f-bed8-aedd9c3aa7e9">

like you are 🤔

**Comment by gaborbernat** [comment]
Yes, but note that your role here https://github.com/orgs/pypa/teams/pipx-team is a maintainer, while mine is just member (the tags right of your name):
<img width="350" alt="image" src="https://github.com/pypa/pipx/assets/690238/69b0329a-3ca2-4045-82b0-366800bfef0b">

**Comment by pradyunsg** [comment]
I see a lot of confusion here about how things work. None the less, here's what I just did:

- Made @gaborbernat and @dukecat0 maintainers on the https://github.com/orgs/pypa/teams/pipx-committers. Note that this team has triage permissions to the pipx repo.
- https://github.com/orgs/pypa/teams/pipx-committers now has Admin permission on this repo. Not sure why this was "Maintain" earlier.
- https://github.com/orgs/pypa/teams/pipx-committers now includes @chrysle. They now have Admin permissions on this repo.

> Bernat was only a member of committers so I added to team.

This isn't necessary/useful, unless you also want Bernat to be able to add triagers. The "team" should only include people directly if they're triagers (as members of the team) or are supposed to have the ability to add triagers (as maintainers of the team).

If you see the repositories tab, you'll notice that it grants triage permissions. GitHub only lets sub-teams have increasing permissions hence the presence of a "team" and then a sub-team named "committers".

**Comment by cs01** [comment]
Oh yes I missed that. I am on mobile and the screen shot was small. I just checked and it shows you as a maintainer as well now. Is everything good now? Are we able to close out this task? 

I added @chrysle as well. 

On the commiters page it shows I’m not a maintainer and you are. 

The top category says commiters, the headers says “folks with the maintain bit”, and then there is a badge next to each name. So I am thoroughly confused on how admin and access rights work. But hopefully you have everything you need now, and are able to grant permission to @chrysle if he’s still missing anything. 
![IMG_0531](https://github.com/pypa/pipx/assets/5715368/48968ce1-fb1e-441e-bf66-d8a98602935f)

**Comment by gaborbernat** [comment]
All good now, thanks!

**Comment by chrysle** [comment]
Thank you for your confidence in me!

**Comment by gaborbernat** [comment]
With great power comes great responsibility, use it wisely 😎
