### ISSUE TITLE
Consider removing PEP 723 support, while the PEP is provisional

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pipx#1128]
**Describe the bug**

pipx currently implements a provisional PEP, PEP 723. This PEP is not meant to be exposed [in a user-facing manner at this time](https://discuss.python.org/t/pep-722-723-decision/36763/) and [this was explicitly flagged in the PR](https://github.com/pypa/pipx/pull/1100#issuecomment-1793828832) as well as the discussion linked from the comment there.

**How to reproduce**

`pipx run` implements PEP 723, since #1100 was merged in 1.3.0.

**Expected behavior**

`pipx run` does not implement PEP 723, until a final decision is made on the PEP.

**Comment by pradyunsg** [comment]
x-ref [the discuss.python.org thread](https://discuss.python.org/t/pep-722-723-decision/36763/105?u=pradyunsg)

**Comment by dukecat0** [comment]
@pradyunsg I've opened #1129 to remove the PEP 723 support temporarily.

**Comment by gaborbernat** [comment]
I'm strong -1 on this. First, PEP-723 is provisionally accepted; while the alternative PEP-722 is rejected. So, considering this, PEP-723 is the likely winner, and is fine to have an implementation in pipx. Finally, tools are free to implement PEPs not accepted yet; if anything we had a conversation last year that to stop accepting PEPs that are never implemented, and going ahead we would require new PEPs to have at least one implementation before we accept it. pipx now satisfies this requirement. If the PEP gets amended (or rejected), the implementation in pipx can also be amended (or removed), I consider the implementation experimental, and not binding as far as backwards compatibility goes.
