### ISSUE TITLE
[Winerror 2]  The system cannot find the file specified

### ISSUE THREAD

**Issue by ovianao** [pypa/pipx#1157]
**Describe the bug**

When the registry key HKCU\Environment\Path is missing in Windows, executing "pipx ensurepath" results in an error stating "[WinError 2]  The system cannot find the file specified."

**How to reproduce**

On a Windows 10 machine,
Remove the registry key HKCU\Environment\Path.
Restart the computer.
Execute "pipx ensurepath"

**Expected behavior**

Either a more descriptive error should have been shown, or a warning that the key is not present.

The user doesn't have to have a Path environment variable assigned after all, as Windows allows us to remove it entirely once created.

To be entirely honest and transparent, I'm not sure exactly how it got removed on the system, but that was the cause of the error, as after adding the key back with an empty string, executing "pipx ensurepath" succeeded.

**Comment by dukecat0** [comment]
Please open this issue at https://github.com/ofek/userpath.
