### ISSUE TITLE
Manage changelog with `towncrier`?

### ISSUE THREAD

**Issue by chrysle** [pypa/pipx#1161]
**How would this feature be useful?**

I think it's time to consider adopting [`towncrier`](https://towncrier.readthedocs.io/en/stable/markdown.html) for keeping the changelog. This would have several advantages, including:

- no merge conflicts due to changelog
- more easily readable, ordered changelog
- ability to describe changes in more detail
- easy changelog creation for contributors and management for developers 
via `towncrier` CLI

**Describe the solution you'd like**

Configuring `towncrier` for this project. I'd be willing to work on that.

**Describe alternatives you've considered**

I'm not against the current way of managing the changelog.

**Comment by uranusjr** [comment]
I don’t see why not and would welcome a PR converting the changelog format.

**Comment by Gitznik** [comment]
I just realized that the current main documentation does not include the latest changelog from 1.4.3. They are in the changelog.md in main, but apparently the docs use the version before the last docs build.
I couldn't find how and when this documentation is updated. Can someone point me the right direction? @chrysle maybe?

**Comment by chrysle** [comment]
The changelog wasn't built due to the [failed job](https://github.com/pypa/pipx/actions/runs/7544497267/job/20539252092). You can already see it in the [latest version](https://pipx.pypa.io/latest/changelog/). This should be resolved with the next release, I think that's likely to happen soon?

**Comment by chrysle** [comment]
Right, I also thought about that. Maybe it should delete the tag, then recreate it?

**Comment by Gitznik** [comment]
Probably explains why most other repos have a manual step for creating the changelog: https://github.com/pypa/pipx/pull/1201#issuecomment-1890049664

So how it works is that https://pipx.pypa.io/stable/ points to the tag of the latest release?

**Comment by chrysle** [comment]
> So how it works is that https://pipx.pypa.io/stable/ points to the tag of the latest release?

Indeed.

**Comment by Gitznik** [comment]
If I understand the [readthedocs docs](https://docs.readthedocs.io/en/stable/versions.html#versioned-documentation) correctly, we might just be able to tag the commit after the docs are built with `stable`, and it should use that over the latest semantic version.

The other option for me would be to manually trigger the docs built when we want to release, and merging that PR would create a GH release. That way the actual up-to-date changelog would also be in the release artifacts.

**Comment by chrysle** [comment]
> If I understand the [readthedocs docs](https://docs.readthedocs.io/en/stable/versions.html#versioned-documentation) correctly, we might just be able to tag the commit after the docs are built with `stable`, and it should use that over the latest semantic version.

I've created a draft for this suggestion at #1246, please have a look. Also thinking about the second approach.

**Comment by chrysle** [comment]
FYI the changelog is only included in the sdist, not the built distribution.
