### ISSUE TITLE
Getting debug-like log messages in console after upgrade to v1.4.0

### ISSUE THREAD

**Issue by tspng** [pypa/pipx#1175]
**Describe the bug**

After upgrading to v1.4.0, I suddenly get the following console messages when running `pipx` commands:

```sh
$ pipx list
pipx version is 1.4.0
Default python interpreter is '/opt/homebrew/opt/python@3.12/libexec/bin/python'
running <checking pip's availability>
Time since last upgrade of shared libs, in seconds: 2674. Upgrade will be run by pipx if greater than 2592000.
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
...
```

The excessive log messages will go away when adding one level of `-q` flag to `pipx`.

On a first glance, the message `running <checking pip's availability>` is logged with `logger.info()`. Not sure, if that's really meant to be a info and not debug message though. But that log message call has not been changed for a long time. Maybe there’s a side effect with one of the recent log level changes that went into v1.4.

**How to reproduce**

Run `pipx list` without `-q` or `-v` flags.

**Expected behavior**

Show console log messages as it was pre v1.4.

**Environment**

```sh
$ pipx environment
pipx version is 1.4.0
Default python interpreter is '/opt/homebrew/opt/python@3.12/libexec/bin/python'
Environment variables (set by user):

PIPX_HOME=
PIPX_BIN_DIR=
PIPX_MAN_DIR=
PIPX_SHARED_LIBS=
PIPX_DEFAULT_PYTHON=
USE_EMOJI=

Derived values (computed by pipx):

PIPX_HOME=/Users/tspng/.local/pipx
PIPX_BIN_DIR=/Users/tspng/.local/bin
PIPX_MAN_DIR=/Users/tspng/.local/share/man
PIPX_SHARED_LIBS=/Users/tspng/.local/pipx/shared
PIPX_LOCAL_VENVS=/Users/tspng/.local/pipx/venvs
PIPX_LOG_DIR=/Users/tspng/.local/pipx/logs
PIPX_TRASH_DIR=/Users/tspng/.local/pipx/.trash
PIPX_VENV_CACHEDIR=/Users/tspng/.local/pipx/.cache
PIPX_DEFAULT_PYTHON=/opt/homebrew/opt/python@3.12/libexec/bin/python
USE_EMOJI=true
```

**Comment by luckman212** [comment]
Temporary workaround is to add the `--quiet` flag to your pipx commands

e.g. instead of
```
pipx list
```

use
```
pipx list --quiet
```

**Comment by Gitznik** [comment]
Looks like https://github.com/pypa/pipx/commit/7274ee47ba3ca0315e3ae92e5e1d26c66241a394 set the default logging level to INFO, while it used to be WARNING, which causes this. Should it be changed back to WARNING?

**Comment by tspng** [comment]
Right, I missed that it’s now `INFO` by default:
https://github.com/pypa/pipx/blob/7274ee47ba3ca0315e3ae92e5e1d26c66241a394/src/pipx/main.py#L794-L796

I have no knowledge about pipx’s codebase, but based on the messages that are logged with `info()` it should probably be `WARNING` by default (`max(0, logging.WARNING - 10 * verbose)`).
