### ISSUE TITLE
Adding two new maintainers

### ISSUE THREAD

**Issue by gaborbernat** [pypa/pipx#1214]
Hey everyone, I'd like to express my sincerest gratitude for @henryiii for the many high-quality PRs he put in, as such decided to invite him to be a maintainer.

Furthermore, I also extended a similar invitation to @Gitznik, as he's not yet a member of the org I cannot add him to the maintainer list at https://github.com/orgs/pypa/teams/pipx-committers/members, so I'd like to ask @pfmoore or @pradyunsg to do so. Thanks!

**Comment by pfmoore** [comment]
Happy to do so! Just to make 100% sure I'm not jumping the gun, has @Gitznik confirmed he wants to be a maintainer? Assuming he has, I can add him.

Congratulations to the two new maintainers!

**Comment by Gitznik** [comment]
> Happy to do so! Just to make 100% sure I'm not jumping the gun, has @Gitznik confirmed he wants to be a maintainer? Assuming he has, I can add him.

Yes I have :+1: Thanks for adding me.

> Congratulations to the two new maintainers!

Thank you!

**Comment by pfmoore** [comment]
Cool - invite sent!
