### ISSUE TITLE
Bad interpreter `/Users/USER/Library/Application: no such file or directory` on multiple commands

### ISSUE THREAD

**Issue by paw-lu** [pypa/pipx#1226]
Some installed libraries with pipx return the same type of error when invoked

```console
$ pipx install ranger
$ ranger
ranger:9: /Users/USER/.local/bin/ranger: bad interpreter: /Users/USER/Library/Application: no such file or directory
```

Looking at the file invoked:

```console
$ cat /Users/USER/Library/Application Support/pipx/venvs/ranger-fm/bin/ranger
#!/Users/USER/Library/Application Support/pipx/venvs/ranger-fm/bin/python
# This file is part of ranger, the console file manager.  (coding: utf-8)
# License: GNU GPL version 3, see the file "AUTHORS" for details.
...
```

Seems like the space in the directory, `Application Support` is causing issues here? In this case pipx was installed via homebrew.

**How to reproduce**

```console
$ pipx install ranger
$ ranger
ranger:9: /Users/USER/.local/bin/ranger: bad interpreter: /Users/USER/Library/Application: no such file or directory
$ pipx install visidata
$ vd
ranger:9: /Users/USER/.local/bin/vd: bad interpreter: /Users/USER/Library/Application: no such file or directory
$ visidata
# Weirdly this one works, while `vd` does not!
```

_Edit: Looking into this after the fact `visidata` does not start with the shebang line while `vd` does (`#!/Users/USER/Library/Application Support/pipx/venvs/visidata/bin/python`)_

**Expected behavior**

Packages installed via pipx may be invoked.

---

Thanks a lot for the tool, love using pipx!

**Comment by paw-lu** [comment]
Just now realized this might be a dup of https://github.com/pypa/pipx/issues/1212

**Comment by paw-lu** [comment]
I'm not sure I completely follow the newly [documented solution](https://pipx.pypa.io/latest/troubleshooting/#macos-issues).  The docs suggest symlinking to a directory with no spaces:

```console
$ mkdir $HOME/Library/ApplicationSupport
$ ln -s $HOME/Library/Application\ Support/pipx $HOME/Library/ApplicationSupport/pipx
```

But wouldn't pipx/venv keep generating a shebang with a space? Causing zsh to throw the error? Is a better solution here to maybe modify `$PIPX_HOME`?

**Comment by Gitznik** [comment]
> Just now realized this might be a dup:
> 
> 
> 
> - https://github.com/pypa/pipx/issues/1212
> 
> - https://github.com/pypa/pipx/issues/1198

It's a dup of the 1st one, but not the 2nd one.


> But wouldn't pipx/venv keep generating a shebang with a space? Causing zsh to throw the error? Is a better solution here to maybe modify `$PIPX_HOME`?

Considering this issue and the one in https://github.com/pypa/pipx/issues/1212 I agree this is the more robust fix right now. We should find a solution where this user intervention is not necessary anymore, but for now you're welcome to update the docs accordingly if you don't mind.

Catching this error and raising a more helpful error message would help as well.

Thanks for raising this.

**Comment by ucomru** [comment]
> Some installed libraries with pipx return the same type of error when invoked
> 
> ```
> $ pipx install ranger
> $ ranger
> ranger:9: /Users/USER/.local/bin/ranger: bad interpreter: /Users/USER/Library/Application: no such file or directory
> ```
> 
> Looking at the file invoked:
> 
> ```
> $ cat /Users/USER/Library/Application Support/pipx/venvs/ranger-fm/bin/ranger
> #!/Users/USER/Library/Application Support/pipx/venvs/ranger-fm/bin/python
> # This file is part of ranger, the console file manager.  (coding: utf-8)
> # License: GNU GPL version 3, see the file "AUTHORS" for details.
> ...
> ```
> 
> Seems like the space in the directory, `Application Support` is causing issues here? In this case pipx was installed via homebrew.
> 
> **How to reproduce**
> 
> ```
> $ pipx install ranger
> $ ranger
> ranger:9: /Users/USER/.local/bin/ranger: bad interpreter: /Users/USER/Library/Application: no such file or directory
> $ pipx install visidata
> $ vd
> ranger:9: /Users/USER/.local/bin/vd: bad interpreter: /Users/USER/Library/Application: no such file or directory
> $ visidata
> # Weirdly this one works, while `vd` does not!
> ```
> 
> _Edit: Looking into this after the fact `visidata` does not start with the shebang line while `vd` does (`#!/Users/USER/Library/Application Support/pipx/venvs/visidata/bin/python`)_
> 
> **Expected behavior**
> 
> Packages installed via pipx may be invoked.
> 
> Thanks a lot for the tool, love using pipx!

I'm asked the same question [$PIPX_HOME contain HARD separator - SPACE in the ".../Application Support/..." via HomeBrew #1288] (https://github.com/pypa/pipx/issues/1288)
Add to `.zshrc`:
```bash
export PIPX_HOME=$HOME/.local/pipx
```
It will help to you.
I think it will be the default value in the future. :-)
