### ISSUE TITLE
pipx fails to run script with dependencies.

### ISSUE THREAD

**Issue by planetmarshall** [pypa/pipx#1227]
**Describe the bug**

According to the [docs](https://pipx.pypa.io/stable/examples/#pipx-run-examples), the following script should run:

```.py
# test.py

# Requirements:
# requests
#
# The list of requirements is terminated by a blank line or an empty comment line.

import sys
import requests
project = sys.argv[1]
pipx_data = requests.get(f"https://pypi.org/pypi/{project}/json").json()
print(pipx_data["info"]["version"])
```

**How to reproduce**

```
brew install pipx
pipx ensurepath
pipx run test.py
```

**Expected behavior**

ths script should install the requirements and output the pipx version (eg. `1.4.3`)

**Actual Behaviour**

output is
```
File "/Users/andrew/projects/pipx-test/test.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Notes**

* pipx version 1.4.3
* Macos Ventura 13.6.2 (arm64)
* Python 3.12 (homebrew)

**Comment by planetmarshall** [comment]
> This runs normally in my Debian installation. Could you post the output of `pipx run` with `--verbose`?

```
$ pipx run --verbose test.py 
pipx >(setup:860): pipx version is 1.4.3
pipx >(setup:861): Default python interpreter is '/opt/homebrew/opt/python@3.12/libexec/bin/python'
pipx >(exec_app:370): exec_app: /opt/homebrew/opt/python@3.12/libexec/bin/python test.py
/opt/homebrew/opt/python@3.12/bin/python3.12
```

**Comment by planetmarshall** [comment]
In the tests (thttps://github.com/pypa/pipx/blob/main/tests/test_run.py) the syntax for this feature is different - it's

```
# test.py

# /// script
# dependencies = ["requests"]
# ///

import sys
import requests
project = sys.argv[1]
pipx_data = requests.get(f"https://pypi.org/pypi/{project}/json").json()
print(pipx_data["info"]["version"])
```

Which works - maybe it's the docs that need updating?

**Comment by chrysle** [comment]
> Which works - maybe it's the docs that need updating?

Right, I forgot – When implementing support for [inline script metadata](https://peps.python.org/pep-0723/), we also removed support for the old requirement specification. A pull request to update the section would be welcome.
