### ISSUE TITLE
Catch error when application shebang contains space and print helpful error

### ISSUE THREAD

**Issue by Gitznik** [pypa/pipx#1230]
**How would this feature be useful?**

Currently, if 
- pipx installs its virtual environments under a path with spaces, and
- the installed application does not define an entrypoint and/or is invoked via one of its scripts

the execution fails with a `bad interpreter` error. See #1212 for more details.

**Describe the solution you'd like**

Catch this error and provide a more helpful error message. It should hint at setting `PIPX_HOME` to a path without spaces and raising this issue on the package that failed, with the context of [our docs regarding developing for pipx](https://pipx.pypa.io/stable/how-pipx-works/#developing-for-pipx).

**Describe alternatives you've considered**

None

**Comment by uranusjr** [comment]
See also https://github.com/pypa/pip/issues/12599. It is possible to support spaces in the interpreter path, so that’s an option too.

**Comment by SwarajBaral** [comment]
I am trying to find a place where this error could be handled. Should it be during the install process itself ?

**Comment by Gitznik** [comment]
> I am trying to find a place where this error could be handled. Should it be during the install process itself ?

Probably, but we now print a warning whenever we detect a space in the pipx path, so I think this issue is no longer needed :+1:
