### ISSUE TITLE
Use XDG_CACHE_DIR for PIPX_LOG_DIR and PIPX_VENV_CACHEDIR

### ISSUE THREAD

**Issue by hydrargyrum** [pypa/pipx#1234]
**How would this feature be useful?**

Cache/transient/temporary files would be in a dir that's explicitly identified for that.
For example a cache dir is not backed up, or it can be cleaned to save disk space.

Currently, it's all under `~/.local/pipx` but it contains files from many kinds mixed which render this distinction harder.

**Describe the solution you'd like**

See [freedesktop basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), `XDG_CACHE_HOME` is meant for this kind of files.

By default, `$PIPX_LOG_DIR` could be `$XDG_CACHE_HOME/pipx/logs` and `$PIPX_VENV_CACHEDIR` could be `$XDG_CACHE_HOME/pipx/venv-cache`

**Describe alternatives you've considered**

**Comment by chrysle** [comment]
What version of `pipx` are you using? We comply with the freedesktop specification [since 1.2.0](https://pipx.pypa.io/stable/installation/#installation-options).

**Comment by hydrargyrum** [comment]
I found that if `~/.local/pipx` exists, it [prevents](https://github.com/pypa/pipx/commit/c3d8de92b1b6c5c6f637ff16f591598fcf98567a#diff-f817c559e180f76f5216d51c221910a5df8cdc879dfd1f8094a3d82affadd50b) pipx from using `$XDG_CACHE_HOME` dir, so I simply moved my `~/.local/pipx` to `~/.local/share/pipx`, and now `pipx environment` uses the right cache dir, great!
