### ISSUE TITLE
how to install `jupyter` and `jupyterlab`

### ISSUE THREAD

**Issue by goyalyashpal** [pypa/pipx#1235]
hi! thanks a lot for wonderful software.

* i couldn't figure out how to install `jupyter` with `jupyterlab`
* `jupyter-lab.exe` (i.e. `--spec jupyterlab jupyter-lab`) is main thing i want to use
* but when trying to install a new kernel for java language:
    * other stuff use `jupyter.exe` (e.g.: [allen-ball/ganymede])
    * or running `python install_xyz_kernel.py` (e.g.:  [spencerpark/ijava])
* how to do either of those steps with `pipx` ?

[allen-ball/ganymede]: https://github.com/allen-ball/ganymede#installation
[spencerpark/ijava]: https://github.com/SpencerPark/IJava/blob/a03ad7712a5e8c893bbffc527efd66ae9aae0207/README.md?plain=1#L111

i thought to `pipx inject jupyterlab jupyter` but that didn't expose any `jupyter.exe` on path, and now i am clueless on how to accomplish this...

```console
$ java -jar ganymede-2.1.2.20230910.jar -i
ERROR [    main] Install  : Cannot read output of [which, jupyter]
java.io.IOException: Cannot read output of [which, jupyter]
  ...

$ pipx inject jupyterlab jupyter
  injected package jupyter into venv jupyterlab
done! ✨ 🌟 ✨

$ pipx list --include-injected
  ...
   package jupyterlab 4.0.11, installed using Python 3.11.2
    - jlpm.exe
    - jupyter-lab.exe
    - jupyter-labextension.exe
    - jupyter-labhub.exe
    Injected Packages:
      - jupyter 1.0.0

$ jupyter --help
bash: jupyter: command not found
```

**Comment by chrysle** [comment]
> * i couldn't figure out how to install `jupyter` with `jupyterlab`

What exactly do you mean, "with"? In the same venv, it seems, but why? Can't you just install the `jupyter` meta-package separately with Pipx?

**Comment by goyalyashpal** [comment]
> Can't you just install the `jupyter` meta-package separately with Pipx?

so, i tried that, and it seems to work.

but how about that one?

> * or running `python install_xyz_kernel.py` (e.g.:  [spencerpark/ijava](https://github.com/SpencerPark/IJava/blob/a03ad7712a5e8c893bbffc527efd66ae9aae0207/README.md?plain=1#L111))

**Comment by chrysle** [comment]
> but how about that one so that it is installed in the env of that `jupyter`?
> 
> > running `python install_xyz_kernel.py` (e.g.:  [spencerpark/ijava](https://github.com/SpencerPark/IJava/blob/a03ad7712a5e8c893bbffc527efd66ae9aae0207/README.md?plain=1#L111))

You run it with the env's Python (e. g. `$PIPX_HOME/venvs/jupyter/bin/python install.py`)?
