### ISSUE TITLE
Allow linking more binaries than the main project

### ISSUE THREAD

**Issue by frostming** [pypa/pipx#1238]
**How would this feature be useful?**

I have a CLI package `foo` that is shipped with several binaries, and it has an optional dependency on `foo-extra` that when installed, exposes more binaries.

Now when I install with `pipx install foo[extra]`, the extra binaries are not linked to the PIPX_BIN_DIR.

**Describe the solution you'd like**

**Describe alternatives you've considered**

Provide a command `link` to link the binaries from specified package to the PIPX_BIN_DIR, may provide arguments to let users choose which binary to link.

**Comment by chrysle** [comment]
We already have the `--include-deps` flag for the `install` command to include binaries in dependent packages. That does not work in your case (with extras)?

**Comment by frostming** [comment]
My bad not reading the help
