### ISSUE TITLE
Command to update local standalone python versions

### ISSUE THREAD

**Issue by Gitznik** [pypa/pipx#1249]
**How would this feature be useful?**

https://github.com/pypa/pipx/issues/1242 introduced the ability to have pipx download standalone python versions, if the requested python version is not available. Currently, there is no way through pipx to update them. Having a way for pipx to figure out which versions have updates available and applying them would be very useful for housekeeping.

Also see the discussions in the merge review of the feature for more information: https://github.com/pypa/pipx/pull/1243#issuecomment-1932170921

**Describe the solution you'd like**

A new command that checks the downloaded standalone python versions, checks for updates to these versions and updates them.

**Describe alternatives you've considered**

I don't really think there is one.

**Comment by alextremblay** [comment]
Hey @Gitznik,

I've spent the last ~month of my spare time spinning out the code I wrote for managing python distributions into its own tool / library, and I've added support for updating installed distributions.

Check it out: https://github.com/alextremblay/pyvm
and on pypi: https://pypi.org/project/python-version-manager/

feel free to vendor it or use some of its code to improve the pipx implementation :)

**Comment by Gitznik** [comment]
Interesting, thanks for creating, sharing and allowing us to vendor/use the code. Certainly a great resource for when this ticket is picked up :)

**Comment by huxuan** [comment]
Hi @Gitznik,

I am interested in this issue, but have several questions:

1. Seems our first goal is to upgrade the Python version used by pipx-managed applications, so the behavior is more like `pipx reinstall --python <new_python_version> --fetch-missing-python <package_name>`, right? If so, is there any expectation for the "new command", maybe `pipx upgrade-python <package_name>`?
2. Any expectation to the upgrade strategy? From the current implementation [1], I think the intuitive idea is to upgrade the patch version, e.g., from `3.12.2` to `3.12.3` when available. Do we need to support something like from `3.11` to `3.12`? And this is also related to the CLI interaction.
3. Do we need an extra command to manage those installed standalone Python? The functionality will be more like `pyvm` provided. BTW, `pdm` also provide similar features [2].

[1] https://github.com/pypa/pipx/blob/49c998399ae0ff5fd97f748e7135214c83fe098e/src/pipx/standalone_python.py#L193
[2] https://pdm-project.org/en/latest/reference/cli/#python

**Comment by Gitznik** [comment]
Hi @huxuan, great you're looking into this.

This command should allow updating patch versions. I don't think there's a use case for updating minor versions. As you said, switching the minor version should be a reinstall.

From my perspective, updating the python versions should be conscious, via an explicit command. Something like `pipx interpreter upgrade`, optionally specifying the minor version to upgrade the patch version for. The `pipx interpreter` command already exists for pruning existing python versions, so adding the update there seems the most intuitive for me.
