### ISSUE TITLE
expose bash scripts inside the package

### ISSUE THREAD

**Issue by mil-ad** [pypa/pipx#1258]
I have a project that's mostly python-based but I do want to distribute a few simple bash scripts in the project (that use the python package entrypoints) using the same `pipx install`.

For example I have `bash-script-one` and `bash-script-two`. Unfortunately I cannot specify `bash-script-one` in my `[project.scripts]` section because that has the `foo.bar:blah` syntax, i.e. it expects to be pointed to a method inside a py function. 

I can however make sure pip packages these scripts by adding something like this to my `pyproject.toml`:

```
[tool.setuptools.package-data]
some_package = ["bash-script-one", "bash-script-two"]
```

`bash-script-one` and `bash-script-two` are then included in the installed package but not in the same place as my entrypoints.  

It'd be nice if `pipx` had a way so that I could tell it to put these additional executables on PATH in addition to the normal python entrypoints.

**Comment by uranusjr** [comment]
IMO this is out of scope. If a pure Python entry point cannot satisfy the need, the project is no longer covered by a Python package manager and should be distributed in other ways. There are various generic package managing options out there to choose from.
