### ISSUE TITLE
Instructions for installing completions are incomplete

### ISSUE THREAD

**Issue by segevfiner** [pypa/pipx#1268]
**Describe the bug**

The instructions for installing completions are incomplete. You need to install argcomplete, possibly using `pipx` itself. But this is not mentioned anywhere.

**How to reproduce**

Run `pipx completions`

**Expected behavior**

For the instructions to be complete.

**Comment by dukecat0** [comment]
The instruction was added in https://github.com/pypa/pipx/pull/1224, but it has not been released yet.
