### ISSUE TITLE
`pipx ensurepath` adds `c:\users\` to the PATH instead of `C:\Users`

### ISSUE THREAD

**Issue by rosscoleman** [pypa/pipx#1272]
I installed pipx 1.4.3 on Windows 10 using scoop.
```
scoop bucket add versions
scoop install python310 pipx
```

Then, from Powershell, the first time I run `pipx ensurepath`, I get this output (error or warning?)
```
module 'ctypes' has no attribute 'wintypes'
```

However, if I run `pipx ensurepath` again, I get this:
```
C:\Users\rcoleman12\.local\bin has been been added to PATH, but you need to open a new terminal or re-login for this
    PATH change to take effect.

You will need to open a new terminal or re-login for the PATH changes to take effect.

Otherwise pipx is ready to go!
```
That sounds like it's ready. However, if I go view Environment Variables, it has actually added `c:\users\rcoleman12\.local\bin` to the PATH. I have to fix it with `C:\Users\` before anything I install with pipx will work.

**Comment by Gitznik** [comment]
Hi @rosscoleman, thanks for opening this issue.

> Then, from Powershell, the first time I run `pipx ensurepath`, I get this output (error or warning?)
> 
> ```
> module 'ctypes' has no attribute 'wintypes'
> ```

This seems like an error in the upstream `userpath` package: https://github.com/ofek/userpath/issues/55, https://github.com/ofek/userpath/issues/51


> That sounds like it's ready. However, if I go view Environment Variables, it has actually added `c:\users\rcoleman12\.local\bin` to the PATH. I have to fix it with `C:\Users\` before anything I install with pipx will work.

Paths on windows are (almost?) always case insensitive, hence `userpath` uses [os.path.normcase](https://docs.python.org/3/library/os.path.html#os.path.normcase) to lowercase the path. I think if you have a non-standard file system on C that actually is case sensitive this may not hold true. 

Please open an issue in [userpath](https://github.com/ofek/userpath) or comment on the existing issues. I think it's unlikely we will do anything about these issues in pipx.

**Comment by rosscoleman** [comment]
I was testing from a VMWare Horizon virtual desktop. So it could be the case that it has a case sensitive file path.

**Comment by kristjanvalur** [comment]
Upstream seems oddly uninterested in fixing this.  I even made a dead-simple PR:  https://github.com/ofek/userpath/pull/56

**Comment by rosscoleman** [comment]
@Gitznik @kristjanvalur Why not add the exact string `%UserProfile%\.local\bin` to the user PATH? Then pipx doesn't need to use `userpath` on Windows. It would also solve my issue. Is there some reason to prefer adding an absolute path?

**Comment by kristjanvalur** [comment]
> @Gitznik @kristjanvalur Why not add the exact string `%UserProfile%\.local\bin` to the user PATH? Then pipx doesn't need to use `userpath` on Windows. It would also solve my issue. Is there some reason to prefer adding an absolute path?

I'm not a contributor to pipx, I just observed this problem, exactly like here, and went upstream to `userpath` whose problem it is.
However, to answer your question, `userpath` is a cross platform library to _permanently_ modify the path.  For windows, this involves modifying user entries.   I guess pipx wants to just use an off-the-shelf library to add itself to the user's path for good, rather than have to write custom code for each platform.

Sadly, that cross-platform library is broken on windows and the maintainer refuses to fix it.

**Comment by Gitznik** [comment]
> I guess pipx wants to just use an off-the-shelf library to add itself to the user's path for good, rather than have to write custom code for each platform.

That's it, there's a fair amount of logic required to permanently modify the path across platforms and I'd rather not have the code for it within pipx.

> Sadly, that cross-platform library is broken on windows and the maintainer refuses to fix it.

I don't think it's generally broken on windows. I just ran `pipx ensurepath` on a windows VM in `cmd`, `git bash` and `powershell` and it ran fine in all 3. 

Anyways, let's see if another person raising this bug makes the maintainer of `userpath` reconsider.

**Comment by Gitznik** [comment]
This was fixed upstream now. 

Reopening this ticket, as per our `pyproject.toml`, version `1.9` of `userpath` is not allowed, but `1.9.2` contains the fix. Needs a quick research why we don't allow `1.9` and whether that is still valid with the 2 fix versions that were released.

**Comment by kristjanvalur** [comment]
It is broken. Whoever uses a module without importing it is not doing
Python right.

**Comment by dukecat0** [comment]
> Needs a quick research why we don't allow `1.9`

According to #1075, only `1.9.0` isn't allowed.

**Comment by chrysle** [comment]
> According to #1075, only `1.9.0` isn't allowed.

That is true, hence I do not see why we should leave this issue open.

**Comment by Gitznik** [comment]
Gotcha, yes this can be closed :+1:
