### ISSUE TITLE
inject command does not respect "--force" option

### ISSUE THREAD

**Issue by huxuan** [pypa/pipx#1300]
**Describe the bug**

When `--force` is NOT specified, the `pipx inject` command will still install the dependency when it exists.

**How to reproduce**

```bash
pipx install pycowsay
pipx inject pycowsay cowsay # inject cowsay into pycowsay for the first time
pipx inject pycowsay cowsay # inject again without `--force`, but it is still installed again
```

**Expected behavior**

Only install the injected package again when `--force` is specified.

BTW, I can try to submit a pull request.

**Comment by chrysle** [comment]
> BTW, I can try to submit a pull request.

That would be welcome, thank you!
