### ISSUE TITLE
Support list packages in toml format.

### ISSUE THREAD

**Issue by huxuan** [pypa/pipx#1302]
**How would this feature be useful?**

Nowadays, `pyproject.toml` is becoming a standard configuration file for Python projects. It would be useful if we can list related Python applications in the corresponding Python project, especially when combining with features like `install-all` (#687). 

**Describe the solution you'd like**

Add a new option `--pyproject` to `pipx list`, just like `--json` and `--short`, it will print the package spec in toml and user can just copy it into `pyproject.toml` for management. In the future, we can even support `pipx install-all` that will by default install packages listed in the `pyproject.toml`.

**Describe alternatives you've considered**

No alternative solutions to the best of my knowledge.

**Comment by chrysle** [comment]
I don't really see the use case this could be relevant for, could you elaborate? IIUC you want all pipx-installed packages to be listed in the format of a `dependencies`  `pyproject.toml` key; but you can't actually want to copy that listing as a whole to your `pyproject.toml` file? Pipx is rather of use to have CLI tools at hand quickly and does not perform any high-level version management.

**Comment by huxuan** [comment]
Sorry for the potential misleading. I am not mean the `dependencies` but just pipx's metadata. I suppose it to be in the section like `[tool.pipx]`.

Considering a project that need to use `poetry`, `pre-commit` and etc. We usually have to add a prerequisite instruction to install all these applications. But actually, we can make it more reproducible with something like `pipx install-all` after cloning the repo.

Moreover, instead of installing tools like `black`, `ruff` as dev dependencies, maybe it is better to manage them with `pipx`. Since all dev denpendencies are installed in the same virtual environment, even together with project's dependencies, it will be likely to have conflicts when more tools are included.

**Comment by huxuan** [comment]
> I suppose most developers will already have these tools installed (probably via `pipx`), or don't have trouble with managing a venv for development. 

Yes, I have to admit this may not be a desirable feature for experienced developers. It is just another way to share the package list and will be quite useful for NEW contributors. For example, I do not use `nox` for other projects, when trying to make some contribution to `pipx`, instead of looking into the [contribution guide](https://github.com/pypa/pipx/blob/main/CONTRIBUTING.md) and then run `pipx install nox`, it will be more convenient to just run `pipx install-all` after cloning the repo. We can have something like `pipx.json` but that may not be a ordinary approach for Python projects. Actually, the idea comes from https://github.com/pypa/pipx/pull/874#issuecomment-1202014249. Since `pyproject.toml` is becoming a must-have configuration for Python projects, it will be convenient to make it inside.

> how would `pipx` determine which dependency to install in an own venv and which packages to inject (e.g. `pytest` and dependencies)?

We can just follow the existing specification metadata, seems #1303 already shows an example. I haven't tried it yet.

> how would you make sure that the file system is uncluttered, as I guess you mean by this `pipx` should manage an isolated set of venvs for each project? Do you think projects should configure `pipx` to manage their dev dependencies, or should `pipx` translate the individual setup on its own?

Good point, that could be the next step for toml support. But for the first step, I would suggest to treat it as a file format just like `json`. 
  
> What do you mean exactly with "more tools"?

Here is a list of tools I can think of:

- Tools that are likely to be commonly used: 
   - pre-commit
   - pytest
   - black
   - ruff
   - mypy
   - nox
   - pipenv/poetry/pdm
- Tools that maybe not be so commonly used:
   - [toml-sort](https://pypi.org/project/toml-sort/)
   - [pycomplete](https://pypi.org/project/pycomplete/)
   - [git-changelog](https://pypi.org/project/git-changelog/)

Besides, I even want to manage all the `dev-dependencies` with pipx, inlcuding `pytest`, `sphinx`/`mkdocs` (with various plugins as injected packages). When the project becomes larger, it tends to have conflicts when installing these (especially for the plugins) with `project.dependencies` even in the same virtual environment.

**Comment by chrysle** [comment]
>  But for the first step, I would suggest to treat it as a file format just like `json`.

Good, but I'm still unsure how moving `pipx` metadata in TOML format into a `pyproject.toml` table would help in this case. You want `pipx` to handle the configuration given under said table, correct? Then we'll need to configure it so that it gains the ability to take that in account.

**Comment by huxuan** [comment]
Hi @chrysle I totally agree with you. Support a new format is easy, but make `pipx` fully integrated with `pyproject.toml` can be complicated. Just wonder if there is any format I should follow when proposing the plan, just something like PEP?

**Comment by chrysle** [comment]
>  Just wonder if there is any format I should follow when proposing the plan, just something like PEP?

A packaging PEP is written up for a more general, extensive change to the infrastructure of Python packaging.
I think proposing design changes to a specifc tool in this category is fine to be done in issue format.

**Comment by huxuan** [comment]
Thanks for the kind reply. I will create a new issue on toml format support then.
