### ISSUE TITLE
`pipx install --force` without `--python` complains about the ignorance of `--python`

### ISSUE THREAD

**Issue by huxuan** [pypa/pipx#1304]
**Describe the bug**

When run `pipx install --force` without `--python`, `pipx` still complains about the ignorance of `--python`

**How to reproduce**

```shell
> pipx install pycowsay
> pipx install pycowsay --force
--python is ignored when --force is passed. If you want to reinstall pycowsay with <path/to/default/python>, run `pipx reinstall pycowsay
--python <path/to/default/python>` instead.
```

**Expected behavior**

No `--python` ignorance warning.

BTW, seems the bug is introduced by the default value of `--python` [1]. And there are at least two approaches to resolve it. One is to remove the default value and check whether there is any side effects. The other way is to change the condition when warning [2]. Please let me know if there is any preference. 

[1] https://github.com/pypa/pipx/blob/ac70dc0d2221bc6a78e39bef86f43b5c73ef03d7/src/pipx/main.py#L376
[2] https://github.com/pypa/pipx/blob/ac70dc0d2221bc6a78e39bef86f43b5c73ef03d7/src/pipx/commands/install.py#L60

**Comment by multiservicemobiel-bit** [comment]
Ignorant 31 0645752144
