### ISSUE TITLE
No such file or directory: '.github/workflows/constraints.txt' when used in GitHub Action

### ISSUE THREAD

**Issue by tarilabs** [pypa/pipx#1331]
**Describe the bug**

It seems to me more GitHub runner are onboarding `pipx==1.5.0` causing our action to now fail with the error:

```
pipx >(subprocess_post_check_handle_pip_error:331): '/opt/pipx/venvs/poetry/bin/python -m pip --no-input install --constraint=.github/workflows/constraints.txt poetry' failed
pipx >(subprocess_post_check_handle_pip_error:346): Fatal error from pip prevented installation. Full pip output in file:
    /opt/pipx/logs/cmd_2024-04-08_15.22.19_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not open requirements file: [Errno 2] No such file or directory: '.github/workflows/constraints.txt'
```

while this is not a problem with earlier pipx 1.4.3

**How to reproduce**

Screenshot: in this run (8602647917), the left GitHub Action runner came with pipx 1.4.3, right GitHub Action runner came with 1.5.0

![Screenshot 2024-04-08 at 17 23 19 (2)](https://github.com/pypa/pipx/assets/1699252/4b653f2e-2c98-4d33-8bfc-6b79e8cffab8)

Analogously, see this PR job: https://github.com/kubeflow/model-registry/actions/runs/8602865736/job/23573396714
failed, while other runner in the same matrix just passed the step successfully.

When forcing pipx==1.4.3 with: https://github.com/kubeflow/model-registry/pull/55/commits/8971944dc1a344b3043fa41aa82852b8713412b8

Then the error is resolved: https://github.com/kubeflow/model-registry/actions/runs/8602962417/job/23573717964?pr=55

**Expected behavior**

Expected no change in behaviour.

Kindly advise?
Thanks in advance!

**Comment by Gitznik** [comment]
I reckon this is due to https://github.com/pypa/pipx/pull/1237. Did a quick test and just forcing `run_dir` to `None` here https://github.com/pypa/pipx/blob/0837df2bf07069abba182c896e7605f9d9d9b95a/src/pipx/venv.py#L260 resolved the problem.

@tarilabs aside from forcing pipx version < 1.5, passing an absolute path also fixes this, until we come up with a better solution.

**Comment by chrysle** [comment]
Related: #1389. I could use some help with the corresponding PR.
