### ISSUE TITLE
Global parameter does not work using ensurepath command

### ISSUE THREAD

**Issue by marcosalberto** [pypa/pipx#1337]
**Describe the bug**

Follow the pipx install documentation for MacOS causes a "unrecognized arguments" error on ensurepath command.

**How to reproduce**

➜  ~ sudo pipx ensurepath --global
Password:
usage: pipx [-h] [--quiet] [--verbose] [--global] [--version]
            {install,uninject,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,interpreter,run,runpip,ensurepath,environment,completions} ...
pipx: error: unrecognized arguments: --global
➜  ~

**Expected behavior**

Install pipx globally without errors

**Comment by Gitznik** [comment]
Hi @marcosalberto, could you please provide the version of pipx you are on?

**Comment by marcosalberto** [comment]
Hi @Gitznik,

I'm using the 1.5.0 version and change the parameter position fixes the issue.

```
➜  ~ pipx --version
1.5.0
```

Sorry by didn't add a comment making reference to the PR.

**Comment by boris-ning-usds** [comment]
Ah, I just installed pipx for the first time and caught this.

This works.
> sudo pipx --global ensurepath

This doesn't work
> sudo pipx ensurepath --global

**Comment by UlyC** [comment]
pipx 1.1.0-1, same issue

**Comment by chrysle** [comment]
Will work as described in the documentation in the upcoming `pipx` version (#1397).

**Comment by salko-ua** [comment]
i have issue with
~ ❯ sudo pipx --global ensurepat
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,completions}
            ...
pipx: error: argument command: invalid choice: 'ensurepat' (choose from 'install', 'inject', 'upgrade', 'upgrade-all', 'uninstall', 'uninstall-all', 'reinstall', 'reinstall-all', 'list', 'run', 'runpip', 'ensurepath', 'completions')

and
~ ❯ sudo pipx ensurepath --global                                            ✘ 2
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,completions}
            ...
pipx: error: unrecognized arguments: --global

**Comment by Gitznik** [comment]
> i have issue with ~ ❯ sudo pipx --global ensurepat usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,completions} ... pipx: error: argument command: invalid choice: 'ensurepat' (choose from 'install', 'inject', 'upgrade', 'upgrade-all', 'uninstall', 'uninstall-all', 'reinstall', 'reinstall-all', 'list', 'run', 'runpip', 'ensurepath', 'completions')

there's a typo in `ensurepath`

**Comment by BurninChrome** [comment]
I have the same issue:
sudo pipx --global ensurepath
usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions} ...
pipx: error: unrecognized arguments: --global

sudo pipx ensurepath --global
usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions} ...
pipx: error: unrecognized arguments: --global

**Comment by Gitznik** [comment]
> I have the same issue: sudo pipx --global ensurepath usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions} ... pipx: error: unrecognized arguments: --global
> 
> sudo pipx ensurepath --global usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions} ... pipx: error: unrecognized arguments: --global

Which version of `pipx` are you on? (`pipx --version`)

**Comment by gundeep-dialpad** [comment]
I have the same error with `pipx` `1.0.0`
none of the following work:
```
pipx --global ensurepath
pipx ensurepath --global
# neither of these with sudo
```

I did just like it mentions in the [docs for ubuntu installation](Perform action globally for all users.)
And I got 1.0.0 🤷‍♂️

**Comment by Gitznik** [comment]
> I followed [docs for ubuntu installation](https://github.com/pypa/pipx?tab=readme-ov-file#on-linux) and ended up with 1.0.0, when the latest is 1.6.0 🤷‍♂️

Yes, unfortunately the pipx version bundled for ubuntu is massively outdated (see [here](https://pipx.pypa.io/stable/installation/)), and the `--global` flag was not around in version 1.0.

**Comment by huxuan** [comment]
Should we suggest to use pipx-managed pipx as discussed here: https://github.com/pypa/pipx/discussions/1341 ?

IMO, it works quite well for me on Linux/Mac/Windows.

**Comment by Gitznik** [comment]
> Should we suggest to use pipx-managed pipx as discussed here: #1341 ?
> 
> IMO, it works quite well for me on Linux/Mac/Windows.

Mind opening a new issue for this?

**Comment by huxuan** [comment]
> Mind opening a new issue for this?

Here we go: https://github.com/pypa/pipx/issues/1449
