### ISSUE TITLE
Unable to install command with plugin

### ISSUE THREAD

**Issue by jaraco** [pypa/pipx#134]
Consider the case where one might want to install `tox` with one or more plugins, such as [tox-venv](https://github.com/tox-dev/tox-venv). I tried:

```
$ pipx install tox --spec='tox tox-venv'                                                                                                             
Invalid requirement: ''tox tox-venv''

"/Users/jaraco/.local/pipx/venvs/tox/bin/python -m pip install 'tox tox-venv' -q" failed
```

I find I can pass `--spec=tox --spec=tox-venv` and that does seem to work, but probably only because the latter spec is honored and happens to include tox in its dependencies.

I note that I can also simply `pipx install tox`, then subsequently `~/.local/pipx/venvs/tox/bin/pip install tox-venv`, but that's not particularly friendly.

Should pipx provide another way to install a command with optional plugins?

**Comment by cs01** [comment]
Does this do what you want?
```
pipx install tox
pipx inject tox tox-venv
```

**Comment by jaraco** [comment]
Yes. I should RTFM. I think I only read about options to `install` because I was thinking about a "one-liner" use-case.

Would it make sense for `install` to have a `--inject` option that would allow install and injection in one go?

**Comment by cs01** [comment]
Yeah that sounds like a good idea :+1:

**Comment by dukecat0** [comment]
This feature was added in #900.
