### ISSUE TITLE
Support Python version number for `--python` arg when py launcher is not available

### ISSUE THREAD

**Issue by huxuan** [pypa/pipx#1342]
**How would this feature be useful?**

Currently, if we want to specify the python when py launcher is not available, we have to specify the whole command name, for example, we have to use `--python python3.12` rather than `--python 3.12`. It would be more convenient if we can check `python3.12` directly when the input value is `3.12`.

**Describe the solution you'd like**

We can use `packaging.version` module to parse the input value and then compose the command f"python{python_version}" if it is a valid version number.

**Describe alternatives you've considered**

AFAIK, there is none.

BTW, I can submit a pull request if we agree on this change.

**Comment by Gitznik** [comment]
I'm not against this. We already do the same thing the other way around, if py launcher is available.

I do not think it should result in a warning though and should not be endorsed. If `python3.X` is provided, it is very clear what executable we're using, as it has to be on the `PATH`. With just `3.X`, this becomes less obvious. This is the same behavior as we have for `py launcher` versions, starting with `python`.
