### ISSUE TITLE
pipx install -r requirements.txt doesn't work

### ISSUE THREAD

**Issue by ZeroDot1** [pypa/pipx#1391]
pipx install -r requirements.txt doesn't work

Everywhere, if you want to install something, it says in the manuals and documentation `pip install -r requirements.txt` and `pipx install -r requirements.txt` does not work. I think this is a big problem and should be fixed.

**Comment by chrysle** [comment]
This was already discussed in #1031.

**Comment by huxuan** [comment]
> And for all the questions, I didn't see a solution to the problem in pipx's documentation.

If you want to export and install all the applications in batch, `pipx list --json` and `pipx install-all` might be what you need. It will be included in the next release I think.
