### ISSUE TITLE
Rename USE_EMOJI to PIPX_USE_EMOJI

### ISSUE THREAD

**Issue by dkav** [pypa/pipx#1395]
**How would this feature be useful?**
It would make easily discernible that this environmental variable is used by pipx.

**Describe the solution you'd like**
Replace `USE_EMOJI` with  `PIPX_USE_EMOJI`

**Describe alternatives you've considered**
`PIPX_NO_EMOJI` (which is similar to Homebrew's `HOMEBREW_NO_EMOJI`)

**Comment by huxuan** [comment]
The suggestion is good, but I have a little concern about back-compatibility. Maybe we should support the `PIPX_USE_EMOJI` first and have a deprecation warning for `USE_EMJOI` usage?

**Comment by dkav** [comment]
That sounds fair to me.

**Comment by uranusjr** [comment]
We need to be careful with emitting a deprecation warning since the environment varialbe may have been set for other reasons. Maybe we should just keep supporting `USE_EMOJI` indefinitely but only recommend and document the variable prefixed with `PIPX_`.
