### ISSUE TITLE
pipx run + package with subprocess.call

### ISSUE THREAD

**Issue by xmnlab** [pypa/pipx#1399]
Hi everyone!

Today a user of our package pointed that it wasn't working with pipx.

I am very new to pipx, so I am still learning how it works.

I managed to fix some issues, but I reached a problem that I couldn't workaround it yet.

so my program uses subprocess.call to run a CLI program that was installed as part of the dependencies of my program.

but it seems that when it is using pipx, it is not able to find it: https://pastebin.com/JWuJxYgv

I am wondering if maybe I add some env variables to the subprocess.call it would work, although initially I was using also `sh` lib with  my env variables, and it failed as well.

Have anyone experienced something like that? any tip to workaround it?

appreciate any help.

All the best,

**Comment by huxuan** [comment]
If you are using `pipx install` you may try whether `--include-deps` help.

**Comment by xmnlab** [comment]
Hi @huxuan , thanks for the tip.

The command I am running is this one
`pip run --verbose --no-cache scicookie --profile osl`

Initially it works, until it calls a `subprocess.call`.

The dependencies are installed, but it seems that subprocess.call is not able to find it

**Comment by huxuan** [comment]
Hi @xmnlab,

Yep, that is what I mean. AFAIK, `pipx run` does not support features like `--include-deps`. IIUC, you just need to make nodejs globally accessible. So, there are several potential approaches I can think of:

1. Use `pipx install --include-deps` instead of `pipx run`.
2. Install nodejs separately and make it accessible without using `nodejs-wheel`.

**Comment by xmnlab** [comment]
hi @huxuan , appreciate your explanation. I have a better big picture now.

as a workaround, I change the code base of our project: https://github.com/osl-incubator/scicookie/pull/286/files#diff-108d8dad817b0dd62379434c9c4a4c5a232bdb8890dd59d2eb3aed181e70f3beR105-R112

In our tests it worked, although it maybe is not a very robust mechanism.

Thank you so much for all the help.
