### ISSUE TITLE
Look into ruff rule RUF012

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [pypa/pipx#1408]
**How would this feature be useful?**

[`RUF012`](https://docs.astral.sh/ruff/rules/mutable-class-default/) checks for mutable default values in class attributes:
> Mutable default values share state across all instances of the class, while not being obvious. This can lead to bugs when the attributes are changed in one instance, as those changes will unexpectedly affect all other instances.

```console
$ ruff check --extend-select RUF --ignore RUF005
src/pipx/animate.py:24:20: RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
src/pipx/pipx_metadata_file.py:40:28: RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
src/pipx/pipx_metadata_file.py:41:29: RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
src/pipx/pipx_metadata_file.py:42:44: RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
src/pipx/pipx_metadata_file.py:43:56: RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
Found 5 errors.
$ 
```

Introduced in #610:
https://github.com/pypa/pipx/blob/5eed47950ba97ea8e0ad292a1026cf87809f940e/src/pipx/animate.py#L23-L24

Introduced in #222:
https://github.com/pypa/pipx/blob/5eed47950ba97ea8e0ad292a1026cf87809f940e/src/pipx/pipx_metadata_file.py#L29-L44

**Describe the solution you'd like**

As a first step, I'd like to understand whether this is on purpose or not.

I suspect the relevant classes are designed to have one instance, in which case this is not an issue in practice. Nevertheless, it's good practice to avoid mutable default values, so that future maintainers don't have to ask themselves again.

**Describe alternatives you've considered**

**Comment by chrysle** [comment]
> I suspect the relevant classes are designed to have one instance, in which case this is not an issue in practice. 

As for `PackageInfo`, there are several instances created for the different types of packages `pipx` recognizes (e.g. injected, main, ..). BTW, I think that should be made a dataclass.

> Nevertheless, it's good practice to avoid mutable default values, so that future maintainers don't have to ask themselves again.

Agreed.

**Comment by huxuan** [comment]
I think it is actually a bug, we did not encounter problem mostly because `pipx` is a cli tool and most functions are only called once before exit.

BTW, I notice that you have proposed many ruff rules, just wonder whehter there is any recommended rule set? AFAIK, there is no [preset](https://github.com/astral-sh/ruff/discussions/3363).

**Comment by DimitriPapadopoulos** [comment]
While ruff enables the following [set of rules by default](https://docs.astral.sh/ruff/rules/#rules), other rules are indeed useful:
> By default, Ruff enables Flake8's `F` rules, along with a subset of the `E` rules, omitting any stylistic rules that overlap with the use of a formatter, like `ruff format` or [Black](https://github.com/psf/black).

It is hard to suggest a default set of rules. There is no wide enough consensus to balance the individual preferences of maintainers. I've seen maintainers [revert from _ruff_ to _flake8_ because _ruff_ is not totally a drop-in replacement of _flake8_](https://github.com/adrienverge/yamllint/issues/628#issuecomment-1920820663), and other maintainers embracer _ruff_ and enable `ALL` rules except specific rules they disable.

The rules I have suggested so far reveal actual bugs or result undeniably(?) in more readable or faster code.
