### ISSUE TITLE
[DOC] Installation instructions mal formatted

### ISSUE THREAD

**Issue by MokhFn** [pypa/pipx#1412]
**Describe the bug**

The installation doc hints at this instruction : `sudo pipx ensurepath --global # optional to allow pipx actions with --global argument` while it should be `sudo pipx --global ensurepath # optional to allow pipx actions with --global argument`

Otherwise we get the following error :

<img width="846" alt="image" src="https://github.com/pypa/pipx/assets/20328292/3ecbd51b-a38d-428a-89c2-8073640c5850">  

The instruction should be `[sudo] pipx [options] [commands]` instead of `[sudo] pipx [commands] [options]`

While it makes more sense to use the latter, the current software allows only the former.

**How to reproduce**
Launch the instruction from the doc : `sudo pipx ensurepath --global # optional to allow pipx actions with --global argument`

**Expected behavior**
No errors

**Comment by dukecat0** [comment]
@MokhFn I have provided a fix for this in #1397 and you should be able to run `sudo pipx ensurepath --global` in the next release, but please run `sudo pipx --global ensurepath` for now.

**Comment by MokhFn** [comment]
Nice, thanks ! i was already starting a PR for the fix. Saved me sometime ;)

**Comment by b4shful** [comment]
When I tried to run `sudo pipx --global ensurepath` I get the following:
![image](https://github.com/pypa/pipx/assets/28313200/2f30cc1f-ea5f-4ef5-8067-7c52ca300fc2)

I'm on Arch Linux.

I just ignored it, but it could be confusing to people following the install instructions. Should it be ignored? Or `--force`d?
