### ISSUE TITLE
Potential Bug: Installation Instructions for --global

### ISSUE THREAD

**Issue by BSuperbad** [pypa/pipx#1419]
**Describe the bug**

When following instructions for macOS installation, the optional sudo pipx ensurepath --global should be as follows:
sudo pipx --global ensurepath
Link: https://pipx.pypa.io/stable/#on-macos

**How to reproduce**

$ sudo pipx ensurepath --global
usage: pipx [-h] [--quiet] [--verbose] [--global] [--version]
            {install,uninject,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,interpreter,run,runpip,ensurepath,environment,completions}
            ...
pipx: error: unrecognized arguments: --global

**Expected behavior**

We switched ensurepath and --global so that --global comes first and now it's good to go!

**Comment by dukecat0** [comment]
Please see https://github.com/pypa/pipx/issues/1412#issuecomment-2112520650
