### ISSUE TITLE
pipx inject <package> --include-apps <app> returns unrecognized arguments: <app>

### ISSUE THREAD

**Issue by robgifford** [pypa/pipx#1448]
**Describe the bug**

**How to reproduce**
running pipx-1.6.0
#Install a package:
pipx install ansible==8.* --include-deps
#inject an app into venv ansible
pipx inject ansible --include-apps ansible-lint

results in:
/# pipx inject ansible --include-apps ansible-lint
usage: pipx [-h] [--quiet] [--verbose] [--global] [--version]
            {install,install-all,uninject,inject,pin,unpin,upgrade,upgrade-all,upgrade-shared,uninstall,uninstall-all,reinstall,reinstall-all,list,interpreter,run,runpip,ensurepath,environment,completions}
            ...
pipx: error: unrecognized arguments: ansible-lint

**Expected behavior**

inject ansible-lint into ansible venv

Additionally, reverting the pipx version to 1.5.0 and the above commands work.

**Comment by huxuan** [comment]
This should be the same issue as #1444
