### ISSUE TITLE
How to delete temporary environment of pipx run?

### ISSUE THREAD

**Issue by Saya47** [pypa/pipx#1468]
After I run an app how can I remove the temporary environment it has created without restarting my system?
If I run multiple apps, each will have their own temp env's so the system can get cluttered fast when you test a lot of apps, it would be nice to have an option to delete them at once!
Thanks very much!

**Comment by dukecat0** [comment]
Running this command would remove all the caches:
```rm -rf $(pipx environment -V PIPX_VENV_CACHEDIR)```
