### ISSUE TITLE
`pipx install --global` partially installs in `~/.local`

### ISSUE THREAD

**Issue by viscruocco** [pypa/pipx#1475]
**Describe the bug**

When executing `pipx install --global`:

- It correctly installs the venvs to `/opt/pipx/venvs` and the binaries and manual pages to `/usr/local/bin` and `/usr/local/man`.
- The shared-libs are mistakenly installed to `~/.local/share/pipx`.
- Empty and unused `~/.local/bin` and `~/.local/share/man` directories are created. (This can be a problem if there are no write permissions to `~/.local`, e.g. in a docker container without a proper user home directory.)

**How to reproduce**

```sh
$ docker run -it --rm python:3 bash
$$ pip install git+https://github.com/pypa/pipx.git
$$ pipx install --global cowsay
$$ which cowsay
/usr/local/bin/cowsay   # --> good
$$ ls /opt/pipx/venvs
cowsay                  # --> good
$$ ls /opt/pipx/
venvs                   # --> bad: bin and share should be here
$$ ls ~/.local/
bin  share  state       # --> bad: bin and share should NOT exist here; good: state/pipx/log is ok here
$ ls ~/.local/bin/
                        # --> bad: ~/.local/share/bin is empty
$ ls ~/.local/share/
man  pipx               # --> bad: ~/.local/share/pipx is actually created and used here
```

**Expected behavior**

```sh
$ docker run -it --rm python:3 bash
$$ pip install git+https://github.com/pypa/pipx.git
$$ pipx install --global cowsay
$$ which cowsay
/usr/local/bin/cowsay
$$ ls /opt/pipx/venvs
cowsay
$$ ls /opt/pipx/
bin  share  venvs
$$ ls ~/.local/
state
```

**Comment by viscruocco** [comment]
After some consideration I noticed that the log files should also be written into the global directories instead of `~/.local`. As mentioned above `~/.local` might not be writeable after all. Since there is no configuration variable for the log directory it would be especially problematic to place it outside of PIPX_HOME. (The same goes for the cache and trash directories.)

**Comment by Denney-tech** [comment]
Encountering similar bug/behavior with `pipx --global upgrade <spec> --install`, but it _does_ install apps to `~/.local/bin/` even though they are already found in `/usr/local/bin`.

**Comment by viscruocco** [comment]
> [...] `pipx --global upgrade <spec> --install` [...]

That's most likely related to https://github.com/pypa/pipx/issues/1443. Try putting `--global` after `upgrade` instead:
`pipx upgrade --global <spec> --install`
