### ISSUE TITLE
'pin' claims package is not installed when it is installed

### ISSUE THREAD

**Issue by kpfleming** [pypa/pipx#1477]
**Describe the bug**

I'm trying to use `pipx pin` to pin the version of Pillow that is injected into one of the venvs managed by pipx. Unfortunately the command claims that Pillow is not installed, when it is installed.

**How to reproduce**

1. `pipx install esphome`
2. `pipx inject esphome pillow==10.2.0`
3. `pipx pin --verbose --injected-only pillow`

```
kpfleming@balrog24:~$ pipx pin --verbose --injected-only pillow
pipx >(setup:1083): pipx version is 1.6.0
pipx >(setup:1084): Default python interpreter is '/home/kpfleming/.local/share/hatch/pythons/3.12/python/bin/python3.12'
pipx >(run_pipx_command:218): Virtual Environment location is /home/kpfleming/.local/pipx/venvs/pillow
Package pillow is not installed
```

I get the same result if I run `pipx pin --injected-only pillow==10.2.0`, or don't include `--injected-only`.
 
**Expected behavior**

Pillow should be pinned to version 10.2.0 in the venv containing ESPHome.

**Comment by dukecat0** [comment]
You should run `pipx pin --injected-only esphome` instead as `esphome` is the name of the venv.

**Comment by kpfleming** [comment]
Thanks! The confusion of using 'package' for multiple meanings, I guess.
