### ISSUE TITLE
Using `pipx inject python-lsp-server 'python-lsp-server[rope]'` fails

### ISSUE THREAD

**Issue by arp242** [pypa/pipx#1478]
I installed `python-language-server` with:

```
% pipx install python-language-server
⡿ creating shared libraries
  installed package python-language-server 0.36.2, installed using Python 3.12.4
  These apps are now globally available
    - pyls
done! ✨ 🌟 ✨
```

And that works. I want to add `python-lsp-server[rope]`, so I do:

```
% pipx inject python-lsp-server 'python-lsp-server[rope]'
⚠️ python-lsp-server already seems to be injected in 'python-lsp-server'. Not modifying existing installation in '/home/martin/.local/share/pipx/venvs/python-lsp-server'. Pass '--force' to
force installation.
```

Unless I'm misunderstanding how this is supposed to work, I believe that should work?

This is on Linux, with `--verbose`:

```
% pipx inject --verbose python-lsp-server 'python-lsp-server[rope]'
pipx >(setup:1083): pipx version is 1.6.0
pipx >(setup:1084): Default python interpreter is '/usr/bin/python3.12'
pipx >(run_pipx_command:218): Virtual Environment location is /home/martin/.local/share/pipx/venvs/python-lsp-server
pipx >(inject:135): Injecting packages: ['python-lsp-server[rope]']
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(needs_upgrade:83): Time since last upgrade of shared libs, in seconds: 1159. Upgrade will be run by pipx if greater than 2592000.
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(package_name_from_spec:378): Determined package name: python-lsp-server
pipx >(package_name_from_spec:379): Package name determined in 0.0s
pipx >(run_subprocess:175): running /home/martin/.local/share/pipx/venvs/python-lsp-server/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(inject_dep:68): Package python-lsp-server has already been injected
⚠️ python-lsp-server already seems to be injected in 'python-lsp-server'. Not modifying existing installation in '/home/martin/.local/share/pipx/venvs/python-lsp-server'. Pass '--force' to
force installation.
```

And when adding `--force` it does seem to do the right thing:

```
% pipx inject --verbose python-lsp-server 'python-lsp-server[rope]' --force
pipx >(setup:1083): pipx version is 1.6.0
pipx >(setup:1084): Default python interpreter is '/usr/bin/python3.12'
pipx >(run_pipx_command:218): Virtual Environment location is /home/martin/.local/share/pipx/venvs/python-lsp-server
pipx >(inject:135): Injecting packages: ['python-lsp-server[rope]']
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(needs_upgrade:83): Time since last upgrade of shared libs, in seconds: 1211. Upgrade will be run by pipx if greater than 2592000.
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(package_name_from_spec:378): Determined package name: python-lsp-server
pipx >(package_name_from_spec:379): Package name determined in 0.0s
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: python-lsp-server[rope]
pipx >(install_package:245): Installing python-lsp-server from spec 'python-lsp-server[rope]'
installing python-lsp-server from spec 'python-lsp-server[rope]'...
pipx >(run_subprocess:175): running /home/martin/.local/share/pipx/venvs/python-lsp-server/bin/python -m pip --no-input install python-lsp-server[rope]
pipx >(run_subprocess:175): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:349): get_venv_metadata_for_package: 147ms
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: python-lsp-server[rope]
  injected package python-lsp-server into venv python-lsp-server
done! ✨ 🌟 ✨
```

**Comment by huxuan** [comment]
It looks that you should `pipx install python-lsp-server[rope]` directly. `pipx inject` is used by specifying the package specs, for example, `pipx inject python-lsp-server black` will install `black` in the venv that installs `python-lsp-server`.

**Comment by arp242** [comment]
Seems to me you want a plugin like this in the same venv? But I've been out of the loop with Python development since the Python 2.6 days or thereabouts, so I don't really know what I'm doing.

But saying `python-lsp-server already seems to be injected in 'python-lsp-server'` seems a bug to me, no?

And even if `inject` is not the right command here, I don't see why this "Install packages into an existing Virtual Environment" should fail here.

**Comment by huxuan** [comment]
It means the same package has already been installed, which is true as you have already run `pipx install python-lsp-server`. Maybe you can describe what you want to do. I think there is some misunderstanding here.

**Comment by arp242** [comment]
Just following the README: https://github.com/python-lsp/python-lsp-server?tab=readme-ov-file#installation

**Comment by huxuan** [comment]
> Just following the README: https://github.com/python-lsp/python-lsp-server?tab=readme-ov-file#installation

There is no need to inject the extra packages. Instead, you can just run `pipx install python-lsp-server[rope]` to achieve what you want I think.

**Comment by arp242** [comment]
```
% pipx install 'python-lsp-server[rope]'
'python-lsp-server' already seems to be installed. Not modifying existing
installation in '/home/martin/.local/share/pipx/venvs/python-lsp-server'. Pass
'--force' to force installation.

% pipx list
venvs are in /home/martin/.local/share/pipx/venvs
apps are exposed on your $PATH at /home/martin/.local/bin
manual pages are exposed at /home/martin/.local/share/man
   package python-lsp-server 1.11.0, installed using Python 3.12.4
    - pylsp
```

**Comment by huxuan** [comment]
> ```
> % pipx install 'python-lsp-server[rope]'
> 'python-lsp-server' already seems to be installed. Not modifying existing
> installation in '/home/martin/.local/share/pipx/venvs/python-lsp-server'. Pass
> '--force' to force installation.
> 
> % pipx list
> venvs are in /home/martin/.local/share/pipx/venvs
> apps are exposed on your $PATH at /home/martin/.local/bin
> manual pages are exposed at /home/martin/.local/share/man
>    package python-lsp-server 1.11.0, installed using Python 3.12.4
>     - pylsp
> ```

I did not see any unexpected result from the log. I may suggest to make clear what you want to do and want pipx actually provided. Since there is no obvious bug according to the conversation above I will close this issue.
