### ISSUE TITLE
 pipx wont run

### ISSUE THREAD

**Issue by seanfire99** [pypa/pipx#1482]
pipx list

Traceback (most recent call last):
  File "/usr/bin/pipx", line 5, in <module>
    from pipx.main import cli
  File "/usr/lib/python3.12/site-packages/pipx/main.py", line 19, in <module>
    import platformdirs
ModuleNotFoundError: No module named 'platformdirs'

**Comment by Gitznik** [comment]
Can you please share some more information?

1. What operating system are you on
2. How did you install pipx
3. What version of python are you on

I can see some issues on poetry where mac users were able to resolve it by running `brew install python-platformdirs`.

**Comment by seanfire99** [comment]
I'm on EndevourOS pipx from aur python ver 3.12.4 from arch repos i will be closing this as i gave up and reinstalled my OS .
