### ISSUE TITLE
binary not added globally when using pipx inject

### ISSUE THREAD

**Issue by jeremyp3** [pypa/pipx#1483]
hello,

I think I have the same problem as #58

for simplification reasons I need to make a venv that contains ansible and a few tools like pre-commmit and cookiecutter.

$ pipx install ansible-base
  installed package ansible-base 2.10.17, installed using Python 3.12.4
  These apps are now globally available
    - ansible
    - ansible-config
    - [...]
    - ansible-vault
done! ✨ 🌟 ✨

now I want to add pre-commit
$ pipx inject ansible-base pre-commit
  injected package pre-commit into venv ansible-base
done! ✨ 🌟 ✨

in .local/bin I don't have any links for pre-commit ::( and it's not available on my system either

$ pipx --version
1.6.0

I haven't found anything in the documentation available here that applies to my case:
https://pipx.pypa.io/stable/examples/#pipx-inject-example

is there anything I haven't understood? :)

thanks !

**Comment by chrysle** [comment]
I suppose what you want is `pipx inject`'s `--include-apps` option (e.g.  `pipx inject --include-apps ansible-base pre-commit`)?

**Comment by jeremyp3** [comment]
thank very much, it works the way I want it to! :)
