### ISSUE TITLE
Custom pip path

### ISSUE THREAD

**Issue by mwriter** [pypa/pipx#1504]
How can I configure pipx to use the specified pip binary path?
Such as PIPX_DEFAULT_PYTHON but for pip.

**Comment by chrysle** [comment]
This contradicts with `pipx`'s concept of having a shared `pip` library with that it manages all installed packages. You could use the `upgrade-shared` command to pin `pip` to a specific version, or what is your use-case here?

**Comment by mwriter** [comment]
> This contradicts with `pipx`'s concept of having a shared `pip` library with that it manages all installed packages

Do I understand correctly that in this concept it's possible to change python interpreter but it's impossible to change pip?
It seemed to me that the portable version of running through pipx.pyz is just designed not to be tied to anything.
And so it turns out that the current version is nailed down and interferes with real portability.
Maybe I'm missing something deeply but I don't understand why should be attached to anything at all.

**Comment by mwriter** [comment]
In addition there are portable python versions such as https://github.com/indygreg/python-build-standalone
And how to use the portable pipx.pyz with such a python version?
It seems to me that the concept needs to be seriously adjusted ;)

**Comment by uranusjr** [comment]
What is the use case here? You want to be able to choose the Python version because each version may introduce incompatibilities to user libraries, but pip does not have the same user interface that matters.

**Comment by mwriter** [comment]
> What is the use case here?

Take any portable version from https://github.com/indygreg/python-build-standalone, take pipx.pyz and show how to use them together.

> but pip does not have the same user interface that matters

Yes, but the pipx won't work without it and it's impossible to set up a path to it.

**Comment by mwriter** [comment]
@uranusjr 
Oh, you even had a project with a similar idea
https://github.com/uranusjr/ouo

**Comment by mwriter** [comment]
@uranusjr 
Although I will clarify just in case: pip isn't built into pipx, is it?

**Comment by chrysle** [comment]
> Take any portable version from https://github.com/indygreg/python-build-standalone, take pipx.pyz and show how to use them together.

We actually have a builtin feature to integrate these standalone Python builds. They're  fetched via a CLI option (ref. [docs](https://pipx.pypa.io/stable/docs/#pipx-install)), extracted and cached under `$PIPX_HOME/py/<version>`. If you absolutely want to, you could also place them there manually.

**Comment by mwriter** [comment]
> They're fetched via a CLI option (ref. [docs](https://pipx.pypa.io/stable/docs/#pipx-install)), extracted and cached under `$PIPX_HOME/py/<version>`

And where is it described in the documentation?

> If you absolutely want to, you could also place them there manually.

And nosystem pip will be picked up automatically?
But there is an option to specify the path to the interpreter
```
--python PYTHON
```
Why not just do the same for exists nosystem pip path? Why force to change the existing paths?

**Comment by mwriter** [comment]
And clarify an important point after all: pip isn't built into pipx, is it?
