### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by mwriter** [pypa/pipx#1505]
Please show an example of how to use pipx offline using sample .whl files.
Pipx is constantly going online. At first during initialization it climbs to update pip
```
python -m pip --no-input --disable-pip-version-check install --force-reinstall -q --upgrade pip
```
Then when launching a package already installed from a whl file it starts searching for it on pypi.org.
Or is such mode not provided at all?

**Comment by chrysle** [comment]
> At first during initialization it climbs to update pip

It is being worked on providing a way to skip this shared library upgrade via an option, see #1278.

> Then when launching a package already installed from a whl file it starts searching for it on pypi.org.

Yeah, unfortunately this is a limitation right now; working around it was already requested in #1275.

**Comment by mwriter** [comment]
> It is being worked on providing a way to skip this shared library upgrade via an option

But the documentation says
```
--skip-maintenance  (deprecated) No-op
```

> this is a limitation right now

I understand correctly that initially, when designing pipx, it was possible to save installed packages locally for subsequent launches. And all these years no one was confused that there were network requests even for already installed packages?
And it's such a sandbox system, seriously :)

**Comment by mwriter** [comment]
I hoped that I had finally met a normal python sandbox system.
Are there any other analogues of a portable and fully customizable python sandbox?

**Comment by uranusjr** [comment]
Contributions are always welcomed.

**Comment by mwriter** [comment]
> Contributions are always welcomed

That's not the answer. And definitely not the answer of a good developer.
It's about the architecture of pipx itself.
Isn't she important to anyone here at all?
