### ISSUE TITLE
Issues installing nuitka with pipx

### ISSUE THREAD

**Issue by MagicalDrizzle** [pypa/pipx#1531]
**Describe the bug**

Executing `nuitka` after installing nuitka gives `python.exe: No module named nuitka`
**How to reproduce**
`pipx install nuitka`

**Expected behavior**
nuitka should launch normally.

It seems like the problem is with nuitka having their runnable binary be a cmd script  - and something about the symbolic linking process breaks it. The symlink in bindir gives the error, while running the actual cmd file inside the venv works fine.

**Comment by uranusjr** [comment]
Unfortunately there is no way to make this setup work. You’ll need to ask Nuitka to fix this.

**Comment by MagicalDrizzle** [comment]
Yeah I suppose I'll just have to add the venv dir itself to PATH (it works) as a workaround. Thank you ^^

**Comment by uranusjr** [comment]
Is it not possible to make the script a real entrypoint? Using a batch script can have a few more negative side effects aside from pipx.

**Comment by MagicalDrizzle** [comment]
Honestly I'm not sure - I'll go ask the nuitka folks. It seems the issues is %dp0 and %CD% resolving to the path of the symlink instead of the file it points to...
