### ISSUE TITLE
Package not Recognized as a Python Package After pipx Installation

### ISSUE THREAD

**Issue by Worfran** [pypa/pipx#1533]
I followed the installation process in the [quick installation guide](https://docs.openmc.org/en/latest/quickinstall.html), but OpenMC is not recognized as a Python package.

I used `pipx` to install the package and have already run `pipx ensurepath`, but my Python scripts do not recognize OpenMC.

I am new to this type of coding and to using Linux. I would greatly appreciate any help.

When I try to install it again, I get the following message:
```
'openmc' already seems to be installed. Not modifying existing installation in '/home/.../.local/share/pipx/venvs/openmc'. 
```
And when I use `ensurepath`, I get:
```
/home/.../.local/bin is already in PATH.
⚠️  All pipx binary directories have been added to PATH. If you are sure you want to proceed, try again with the '--force' flag.
```

**Comment by yolabingo** [comment]
pipx is not the right tool for this job, pipx is for installing cli tools written in Python

Based on the openmc docs you link you shared, the docker method looks simplest
https://docs.openmc.org/en/latest/quickinstall.html#installing-on-linux-mac-windows-with-docker

**Comment by Worfran** [comment]
Hi, thank you for your help. Here’s what I did:

> 

1. > Created a Python environment
"""
$ python -m venv <name_environment>
"""
2. Added an alias in my console:
"""
alias  <name_enviroment>="source <path_to_venv>/bin/acticate"
"""
3. Installed OpenMC using pip as in the [quick installation guide](https://docs.openmc.org/en/latest/quickinstall.html) inside the python enviroment.
