### ISSUE TITLE
pip_args?

### ISSUE THREAD

**Issue by AlJohri** [pypa/pipx#204]
hey, I'm not 100% sure how to use the `--pip-args` properly. I wanted to upgrade to a pre-release version and I had to run the command in this strange way (that's single quotes inside of the double quotes):

```
pipx upgrade clokta --pip-args "'--pre'"
```

Without the extra quotes, I get:

```
pipx upgrade: error: argument --pip-args: expected one argument
```

Is there a better way to do this?

Thanks!

**Comment by cs01** [comment]
How about this?

```
pipx upgrade clokta --pip-args=--pre
```

If you want to pass more arguments, you can do
```
pipx upgrade clokta --pip-args='--pre --some-other-pip-arg'
```

**Comment by kevinjfoley** [comment]
I had the same issue, might help to customize the `usage` parameter [here](https://github.com/pipxproject/pipx/blob/master/pipx/main.py#L251) to show the `=`'s

**Comment by cs01** [comment]
I wonder if `argparse.REMAINDER` will help. If it does I'll update pipx to use that, otherwise I can update the usage instructions like you said.

**Comment by kevinjfoley** [comment]
I think `argparse.REMAINDER` is the best solution, this is how I was expecting it to work personally.  

I did a bit of testing with it as I haven't used it before and it looks like it wouldn't break the current use either so I think that's a good solution.

**Comment by cs01** [comment]
Nice, thanks. The one concern I had was with `pipx run` since there is already an `argparse.REMAINDER` in use there, so I wasn't sure how they'd interact.

**Comment by kevinjfoley** [comment]
Oh I didn't take a look at `pipx run`, at a quick glance I think that will actually break things there, maybe just adding a more verbose `usage` is a safer approach then?

**Comment by gaborbernat** [comment]
> Oh I didn't take a look at `pipx run`, at a quick glance I think that will actually break things there, maybe just adding a more verbose `usage` is a safer approach then?
