### ISSUE TITLE
Add repology shield to README

### ISSUE THREAD

**Issue by jayvdb** [pypa/pipx#234]
**How would this feature be useful?**
I believe it is important for pipx to be available as distro packages, and ensure they are kept updated.  A repology shield would help achieve that.  e.g. https://github.com/lilydjwg/nvchecker has it in their README.

Currently there are two entries in repology which cover pipx:

- [`pipx`](https://repology.org/project/pipx/versions)
- [`python:pipx`](https://repology.org/project/python:pipx/versions)

I assume that those two can be merged.

Here is what each shield looks like.  Obviously it will be more impressive once the two are merged.

[![Packaging status](https://repology.org/badge/vertical-allrepos/python:pipx.svg)](https://repology.org/metapackage/python:pipx/versions)

[![Packaging status](https://repology.org/badge/vertical-allrepos/pipx.svg)](https://repology.org/metapackage/pipx/versions)

**Describe the solution you'd like**
In markdown syntax it would be:

`[![Packaging status](https://repology.org/badge/vertical-allrepos/pipx.svg)](https://repology.org/metapackage/pipx/versions)`

**Comment by gaborbernat** [comment]
PR welcome.
