### ISSUE TITLE
upgrade and upgrade-all don't work with pre-release package versions

### ISSUE THREAD

**Issue by mmerickel** [pypa/pipx#286]
pipx version 0.14.0.0

**Describe the bug**
Upgrading packages that were installed with `pipx install --pip-args '\--pre' <pkg>` fails to upgrade to a newer pre-release without also specifying `pipx upgrade --pip-args '\--pre' <pkg>`.

It'd be nice if pipx recognized the current version of the package was a pre-release version and automatically upgraded it with `--pre` so that `pipx upgrade-all` would work. Right now I need to manually upgrade the package and pass `--pip-args`.

The package I've been upgrading is poetry.

**Comment by uranusjr** [comment]
Auto-inferring pre-releases has a lot of pit-falls (which is why pip chose this current behaviour), and the suggestion would probably dissatisfy another group of people.

**Comment by itsayellow** [comment]
With the merge of #222 pipx currently remembers the options used for `install` when later executing other pipx commands like `upgrade-all` and `reinstall-all`.  This hasn't been released yet to pypi but if you grab the latest pipx from github (and consider it beta) it should do what you want.

**Comment by itsayellow** [comment]
With the release of pipx versions >= 0.15.0.0, `pipx upgrade-all` now uses the same `--pip_args` that were used during install.  

`pipx upgrade` will only use the `--pip_args` supplied to it, however.
