### ISSUE TITLE
pipx incorrectly warns about PATH when PIPX_BIN_DIR is (under) a symlink

### ISSUE THREAD

**Issue by FallenWarrior2k** [pypa/pipx#329]
First off, thank you for this amazing tool. Really helped me clean up all the Python CLI tools I had lying around. Also, after looking at the corresponding code, I was unsure whether to open this issue against [userpath](https://github.com/ofek/userpath) or pipx, and I'll move it there if so desired. From what I see, the cause seems to be that pipx `.resolve()`s the `PIPX_BIN_DIR`, while `userpath` uses just `normpath()` and not `realpath()` for its comparisons.

**Describe the bug**

My `~/.local/bin` is symlinked, and every time I install a package using pipx, I get the incorrect warning that `/real/path/of/local/bin` is not on my `PATH`. However, since I have a symlink to it on my `PATH`, everything still works. Still, I'd like to get rid of this pesky warning.

**How to reproduce**

Install any package while the real path of your `PIPX_BIN_DIR` is not on your `PATH`, but have a symlink pointing to it on your path. pipx will warn that `PIPX_BIN_DIR` is not on your path.

**Expected behavior**

Since the installed binaries are very much accessible through the symlink, there should be no reason to warn the user.

**Comment by ofek** [comment]
https://pypi.org/project/userpath/1.7.0/
