### ISSUE TITLE
ensurepath creates double entries in the path

### ISSUE THREAD

**Issue by floatingpurr** [pypa/pipx#351]
Hi guys, I run into a potential problem w/ the command

```bash
$ pipx ensurepath
```
**More context:**

- OS: macOS Catalina 10.15.2 
- Shell: zsh 5.7.1

**Describe the bug**
When I run `ensurepath` the path `$HOME/.local/bin` is inserted twice both in `.zshrc` and in `.zprofile`

Then, my path is polluted with doubled entries

```bash
<other_stuff>:/Users/myuser/.local/bin:/Users/myuser/.local/bin
```

**How to reproduce**
```bash
$ python -m pip install pipx
$ pipx ensurepath
```

**Expected behavior**
Just one entry of `/Users/myuser/.local/bin` should be added to the path.

**Comment by ciarancourtney** [comment]
Same on Windows 10

**Comment by ralish** [comment]
Saw the same with several dozen entries in my system `PATH` being duplicated into my user `PATH`.

The cause is actually a bug in the `userpath` library used by `pipx`. I've opened an issue here:
https://github.com/ofek/userpath/issues/23

**Comment by ofek** [comment]
@ciarancourtney @ralish Windows is fixed in `1.4.0` (see https://github.com/ofek/userpath/pull/24)

The OP's issue is different https://github.com/ofek/userpath/issues/3#issuecomment-512928319

**Comment by ralish** [comment]
Confirming this is fixed (on Windows) with `userpath` 1.4.0. Thanks @ofek!

**Comment by floatingpurr** [comment]
Not fixed for macOS

**Comment by meowmeowmeowcat** [comment]
@floatingpurr Do you still encounter this issue?

**Comment by floatingpurr** [comment]
Hi @meowmeowmeowcat. To be honest, off the top of my head, I can't remember. Next time I'll check it out. However, this is an old issue. I guess that if anybody has experienced something similar anymore, everything should be fine now. I'm gonna close it for now. Thanx for asking.

**Comment by floatingpurr** [comment]
Ok, just tried. When I run `ensurepath`, an entry like the following one:

```
# Created by `pipx` on 2022-09-02 09:58:37
export PATH="$PATH:/Users/floatingpurr/.local/bin"
```

is appended to both `.zshrc` and `.zprofile`.

Is that the expected behavior?

**Comment by meowmeowmeowcat** [comment]
https://github.com/ofek/userpath/issues/3#issuecomment-512938672
