### ISSUE TITLE
pipx help identifies itself as __main__.py if executed using `python3 -m pipx`

### ISSUE THREAD

**Issue by itsayellow** [pypa/pipx#433]
**Describe the bug**

When executing pipx using `python3 -m pipx`, getting help with `--help` shows `usage: __main__.py` instead of `usage: pipx` 

**How to reproduce**

`python3 -m pipx --help`
or using a subcommand, e.g.
`python3 -m pipx ensurepath --help`

**Expected behavior**

Help text should start with:
`usage: pipx`
Help text instead starts with:
`usage: __main__.py`

This is probably a minor bug, but users may encounter it, for example, before executing `python3 -m pipx ensurepath` (as our installation directions recommend) if they first type `python3 -m pipx ensurepath --help`.

It could probably be easily fixed by adding `prog="pipx"` as an argument to `parser = argparse.ArgumentParser()` inside `get_command_parser()` in `main.py`.

**Comment by uranusjr** [comment]
Would it be possible to display `path/to/python -m pipx` in this case? That would be better than unconditionally showing `pipx` IMO.
