### ISSUE TITLE
Command to run a command in a package virtualenv

### ISSUE THREAD

**Issue by pawamoy** [pypa/pipx#434]
**How would this feature be useful?**
It would be useful when one wants to play a bit with the internals/api of a package in a Python interpreter.

**Describe the solution you'd like**
Instead of creating a venv myself, and install for example aria2p and ipython inside it, I would like to use pipx directly. I already installed aria2p with pipx, injected ipython in its venv, and now I would like to run ipython in this venv.

**Describe alternatives you've considered**
Creating a venv myself, or manually activating the venv of the pipx package. We could also consider adding a `shell` command (to activate the venv) instead of another `run` command.

Do you think this is in the scope of pipx :slightly_smiling_face:?
Thanks for the great project!

**Comment by itsayellow** [comment]
One solution is to use the `--include-apps` option when you inject ipython into your aria2p venv.  Then whenever you execute ipython, it would use the one inside your aria2p venv.

Would this work for you?

**Comment by pawamoy** [comment]
Not really, I also have ipython installed through pipx :sweat_smile:

**Comment by itsayellow** [comment]
So is the problem that you don't want aria2p installed with your normal ipython venv?  Because a workaround would just be to pile everything you want into the same venv.

**Comment by pawamoy** [comment]
> So is the problem that you don't want aria2p installed with your normal ipython venv

Hmmm, this could a solution, yes. But I find it a bit redundant to install aria2p both in its own venv **and** in the ipython venv. I mean, more redundant than installing ipython both in its own venv and in the aria2p venv, because what matters more here is the aria2p version I'm using, not the ipython one :slightly_smiling_face:

**Comment by itsayellow** [comment]
Upgrading!  :+1: Yes that's a challenge for injected packages.  Good point.

**Comment by pawamoy** [comment]
Hi @gaborbernat, is there a commit or PR you could reference?

**Comment by pawamoy** [comment]
Ah, I guess it's https://github.com/pypa/pipx/pull/563 :slightly_smiling_face: 
Well, it kinda provides a workaround for my use-case, but being able to run commands inside venvs would still be useful I think.

**Comment by pawamoy** [comment]
To re-state the original use-case:

- I have many tools that can be used as libraries, each installed in its own pipx venv
- if I want to play with their API, I can inject ipython into each of these venvs
- but then it's hard to call these injected ipython
- the workaround suggested by @itsayellow is too install ipython in its own venv, and inject all the tools there as well
- with not too many tools it's probably OK, but with more, that makes a polluted ipython venv, with risks of dep conflicts

I suppose there are other use cases where one would want to run an installed script in a given pipx venv, though I don't have any in mind.

Anyway that was just to provide feedback, feel free to keep this issue closed.

**Comment by pawamoy** [comment]
I see, thank you for the explanation! :+1:
