### ISSUE TITLE
Installing additional dependencies before the package itself

### ISSUE THREAD

**Issue by jedenastka** [pypa/pipx#442]
**How would this feature be useful?**
It would allow users to install programs that need additional packages in their setup.py, for example [Overviewer](https://github.com/overviewer/Minecraft-Overviewer/blob/master/setup.py).

**Describe the solution you'd like**
Add an `--additional-dependicies PACKAGES` switch, where `PACKAGES` is a comma (or space) separated list of package specs.

**Describe alternatives you've considered**
Installing dependency as pipx package, then injecting package as dependency. Bad soulution, even installing the package with pip is better.

**Comment by uranusjr** [comment]
Can you even install overviewer? From the documentation, it seems like it only supports `setup.py build`. pipx won’t be able to handle it even if you get past the dependency installation stage.

**Comment by clbarnes** [comment]
Python has a system for [projects specifying their build-time dependencies](https://www.python.org/dev/peps/pep-0518/). I would hope that packages with nontrivial build requirements (i.e. anything other than setuptools) would use that system and just allow pip to handle it. Pipx could feasibly implement a workaround for those which don't, but there may be diminishing returns involved in maintaining something specifically for what is hopefully a decreasing number of increasingly outdated projects.

**Comment by itsayellow** [comment]
We do support the pip syntax for "extras", (specified with square brackets) if the package supports them:
https://packaging.python.org/tutorials/installing-packages/#installing-setuptools-extras

I'm not sure overviewer does, however, but it could.

**Comment by salotz** [comment]
I generally agree with what @clbarnes is saying that packages *should* specify their build-time dependencies. They often don't though (perhaps for complicated reasons). It seems like a reasonable feature (+1 from me) if devs think so too, but I guess you can always make the envs manually.

My use-case is installing qtile https://github.com/qtile/qtile and I am opening issues to try and deal with this on their end. But would like to use pipx :)

**Comment by uranusjr** [comment]
IMO we need concrete examples that projects refuse to fix build-time dependency issues. I have yet to see one myself; most of the time the project maintainers are simply not aware of PEP 517, and when there are indeed technical issues they are generally willing to fix them. Providing a workaround in pipx feels irresponsible (that’s too strong but I can’t think of a better word) since it works against PEP 517 adoption, causing a bigger problem for the community long-term.

**Comment by salotz** [comment]
@uranusjr this might be one?

Qtile needs `cairocffi` as a build dependency. But specifically they need `cairocffi` that was *built* with the library `xcffib`. However, `xcffib` is an extra dependency for `cairocffi`. As far as I know there are no equivalent to install extras for build requirements.

**Comment by Darsstar** [comment]
> Another use-case for this feature might be to help support (some?) private registries.
> 
> Google's Artifact Registry, in particular, would certainly benefit from this feature. To download packages from that registry, you need to have the `keyrings.google-artifactregistry-auth` package installed _at the time of the `pip install` command_: ie. without pipx you could do:
> 
> ```
> pip install keyrings.google-artifactregistry-auth
> pip install my-private-package --index-url="https://us-python.pkg.dev/project-name/index-name/simple"
> ```
> 
> Since pipx creates a new virtualenv for each package, it's not currently possible (as far as I can tell) to install a private package as the _first_ package in a new env (injecting a package into an env which already contains the keyring package is possible, of course).

#829 is what I came up whith for this use case
