### ISSUE TITLE
`pipx run` crashes if .cache venv has link to non-existent python interpreter

### ISSUE THREAD

**Issue by itsayellow** [pypa/pipx#449]
**Describe the bug**
If `pipx run` setup a venv in `~/.local/pipx/.cache` and tries to reuse it, and the python executable the venv was originally symlinked to is missing, pipx will crash with an error.

**How to reproduce**
Execute the following for a given python interpreter
```
pipx run --verbose --spec=git+https://github.com/cs01/nox.git@5ea70723e9e6 nox -s develop
```
Uninstall the original python interpreter version, and run again
```
pipx run --verbose --spec=git+https://github.com/cs01/nox.git@5ea70723e9e6 nox -s develop
```

**Expected behavior**

Expected that pipx should notice that the venv is not functional and try to reinstall the venv and package before running.

Actual:
```
birchtree:pipx pipx run --verbose --spec=git+https://github.com/cs01/nox.git@5ea70723e9e6 nox -s develop
pipx > (run:55): ⚠️  nox is already on your PATH and installed at /Users/mclapp/.local/bin/nox. Downloading and running anyway.
pipx > (needs_upgrade:51): Time since last upgrade of shared libs, in seconds: 220.17554593086243. Upgrade will be run by pipx if greater than 2592000.0.
pipx > (run:85): Reusing cached venv /Users/mclapp/.local/pipx/.cache/d0a0c94932f2286
pipx > (run_subprocess:112): running /Users/mclapp/.local/pipx/.cache/d0a0c94932f2286/bin/nox -s develop
Traceback (most recent call last):
  File "/usr/local/Cellar/pipx/0.15.4.0/libexec/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.15.4.0', 'console_scripts', 'pipx')()
  File "/usr/local/Cellar/pipx/0.15.4.0/libexec/lib/python3.8/site-packages/pipx/main.py", line 585, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/usr/local/Cellar/pipx/0.15.4.0/libexec/lib/python3.8/site-packages/pipx/main.py", line 139, in run_pipx_command
    return commands.run(
  File "/usr/local/Cellar/pipx/0.15.4.0/libexec/lib/python3.8/site-packages/pipx/commands/run.py", line 86, in run
    retval = venv.run_app(app, app_args)
  File "/usr/local/Cellar/pipx/0.15.4.0/libexec/lib/python3.8/site-packages/pipx/venv.py", line 329, in run_app
    return run(cmd, check=False)
  File "/usr/local/Cellar/pipx/0.15.4.0/libexec/lib/python3.8/site-packages/pipx/util.py", line 128, in run
    returncode = run_subprocess(
  File "/usr/local/Cellar/pipx/0.15.4.0/libexec/lib/python3.8/site-packages/pipx/util.py", line 115, in run_subprocess
    return subprocess.run(
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mclapp/.local/pipx/.cache/d0a0c94932f2286/bin/nox'
birchtree:pipx 
```

The final error is a little deceptive, the file `/Users/mclapp/.local/pipx/.cache/d0a0c94932f2286/bin/nox` exists, but the interpreter it is trying to use on execution does not exist.

**Comment by uranusjr** [comment]
Not sure how much pipx can do here though, unless we actively parse the linked script 😥

**Comment by itsayellow** [comment]
I we could just run `python --version` in the venv first or in a separate thread and then at least we'd know if something was wrong with the interpreter, and possibly force a reinstall.

**Comment by itsayellow** [comment]
Maybe if there's no cached venv we install it, and if we find a cached venv we run `python --version` to minimally check its validity and THEN we run the script.

**Comment by itsayellow** [comment]
40ms to use subprocess to check `python3 --version`.
```
>>> time.time();subprocess.run(["python3","--version"]);time.time()
1595226430.740194
Python 3.8.4
CompletedProcess(args=['python3', '--version'], returncode=0)
1595226430.785056
```

**Comment by cs01** [comment]
There are any number of ways a venv could be corrupted. Checking for a valid python interpreter is one, but this feels like a specific solution to a more general problem. What if we wrapped the call in a try/except and if it fails, just wipe the cache for that dir and then try again?

**Comment by itsayellow** [comment]
Is there a way to wrap it in a `try`...`except` that would only detect a corrupted venv and not just the app itself crashing?

Also, I can't think of other ways a previously-fine venv would get corrupted, although this is probably just be my lack of imagination.  Can somebody give an example of another failure mode that would require a venv reinstall?

**Comment by gaborbernat** [comment]
IMHO the overhead is not worth the benefit here. If you run into this just reinstall.
