### ISSUE TITLE
Need consistent `inject --include-apps` behavior with suffix

### ISSUE THREAD

**Issue by itsayellow** [pypa/pipx#521]
**Describe the bug**

When injecting into a venv with a suffix using `--include-apps`, currently the injected apps do not take the venv sufix.  This seems inconsistent to me.

We should at least decide intentionally what the proper behavior should be.

**How to reproduce**

```
pipx install pycowsay --suffix _2
pipx inject pycowsay_2 black --include-apps
```
**Expected behavior**

I would assume if that we would end up with a `black_2` app to match the venv, but in fact we end up with a `black` app.

**Comment by amardeep** [comment]
I am facing the same issue. pipx inject doesn't take a suffix argument, and doesn't add the suffix of the original argument.

**Comment by meowmeowmeowcat** [comment]
Maybe an option like `--with-suffix` can be added.
