### ISSUE TITLE
Bootstrap pipx

### ISSUE THREAD

**Issue by ThatXliner** [pypa/pipx#579]
**How would this feature be useful?**

Since pipx has dependancies, I would like a way to bootstrap pipx. I acknowledge that you can do `pipx install pipx`

**Describe the solution you'd like**
An alternative bootstrapping shell script.

**Describe alternatives you've considered**
A PyPi package for pipx installing `pipx-install`. Although it's more cross platform, it would take more work, in my opinion.

**Comment by itsayellow** [comment]
One existing solution is 
https://pypi.org/project/pipx-in-pipx/
https://github.com/mattsb42-meta/pipx-in-pipx

Related is #244

**Comment by gaborbernat** [comment]
> Another way is to use zipapp:
> `curl -L https://github.com/pypa/pipx/releases/latest/download/pipx.pyz -o pipx.pyz && python pipx.pyz`
