### ISSUE TITLE
Change VenvInspectInformation.distributions to be type `Iterable[metadata.Distribution]`

### ISSUE THREAD

**Issue by itsayellow** [pypa/pipx#629]
**How would this feature be useful?**

Change `VenvInspectInformation.distributions` in `venv_inspect.py` to be type `Iterable[metadata.Distribution]`.  (Or whatever type `importlib.metadata.distributions()` returns.)

So we don't have to cast it to a `list()` which is unnecessary.

**Comment by aanghelidi** [comment]
Hello @dukecat0 , I would like to be assigned to this one, can I work on it?

**Comment by dukecat0** [comment]
Hello @aanghelidi, please feel free to work on it!

**Comment by aanghelidi** [comment]
Hello @dukecat0 , here is my attempt to solve this issue, let me know what you think about it.
