### ISSUE TITLE
Install a .whl file containing console entry point

### ISSUE THREAD

**Issue by johnthagen** [pypa/pipx#641]
**How would this feature be useful?**

If a user creates a `.whl` file that contains an [`entry_point` `console_script`](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point), normally they can run:

```bash
(venv) $ pip install myproject-0.1.0-py3-none-any.whl
```

And then those entry points are available within the virtual environment.

But when I try to do something similar with `pipx`:

```
$ pipx install myproject-0.1.0-py3-none-any.whl                               
Fatal error from pip prevented installation. Full pip output in file:
    ~/.local/pipx/logs/cmd_2021-03-02_14.39.35_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement myproject-0-1-0-py3-none-any-whl
    ERROR: No matching distribution found for myproject-0-1-0-py3-none-any-whl

Error installing myproject-0-1-0-py3-none-any-whl.
```

It seems like the `.whl` file name is being normalized into a PyPI name?

**Describe the solution you'd like**

Be able to run

```
$ pipx install myproject-0.1.0-py3-none-any.whl
```

And it installs the package into the `pipx` environment, making the console entry points available in the PATH.

**Comment by johnthagen** [comment]
Digging deeper into the docs, I realized that `pipx` needs to see the `./` in the file name to treat it as a file.

This works:

```bash
$ pipx install ./myproject-0.1.0-py3-none-any.whl   
```

**Comment by johnthagen** [comment]
I will leave this open in case `pipx` maintainers want to fix this to match `pip`'s behaviour.

It seems like the `.` in the file name (e.g. `.whl`) could be something to key off of.

**Comment by uranusjr** [comment]
Technically `myproject-0.1.0-py3-none-any.whl` can be a valid project name, although obviously it’s hard to imagine anyone doing it in practice. pip’s logic includes several special cases to be “helpful”, and I would be fully supportive if pipx choose to not replicate them.
