### ISSUE TITLE
utf-8 error when using ensurepath

### ISSUE THREAD

**Issue by AltamimiYasser** [pypa/pipx#644]
**Describe the bug**
I installed pipx using the official way and when running `python3 -m pipx ensurepath` I get the following error:
`'utf-8' codec can't decode byte 0x90 in position 210: invalid start byte`

**How to reproduce**
clean install, so I've just installed it and don't really know how to reproduce. I even tried running the command in a virtual environment but still the same error.

**Expected behavior**
to not show the error and be able to use pipx normally

**Comment by itsayellow** [comment]
Can you attach the text from the log for this command which you should find in a file in directory `~/.local/pipx/logs/`?  

Also, is that the only error it displays?  Is there any more references to module names or lines of code (i.e. the stack trace?)

**Comment by AltamimiYasser** [comment]
Thanks for your time.
here is the log file 
[cmd_2021-03-08_17.13.54.log](https://github.com/pipxproject/pipx/files/6101912/cmd_2021-03-08_17.13.54.log)

and no that's the only error that shows up in the terminal after executing the command
![2021-03-08_17-19](https://user-images.githubusercontent.com/62793407/110333318-86031080-8032-11eb-90db-0607202ea5a4.png)
 
I should also mention that I've had problems before with pip after stupidly installing packages globally as a root user and had it conflict with a lot of pacman package manager but I went through the steps and tried to clean up my system. I'm saying this as I don't know if there are problems that already exist in my system after manually removing some modules. but then I tried in a virtual environment and I suppose that should be isolated and has no relation at all to the system packages.

Thanks!

**Comment by itsayellow** [comment]
Awesome, that log is SO informative!  Score one for pipx's new log functionality. 😄 

It looks like the error is originating inside of a pipx dependency, `userpath`, which handles things when we execute `pipx ensurepath`.

I believe it's because your system defaults to non-utf8 and `userpath` doesn't handle that when it spawns another process and then tries to interpret the stdout from it.

**Comment by itsayellow** [comment]
As a workaround you could try using a utf-8 locale, something like:
```shell
LANG=en_US.utf8 python3 -m pipx ensurepath
```

Or replace `en_US` with whatever your current LANG is set to.

**Comment by itsayellow** [comment]
To help diagnose what might be happening @AltamimiYasser , if you don't mind posting it, what is the output of the command `echo $PATH`?

**Comment by AltamimiYasser** [comment]
Tnaks for your time! 
My system defualt is en_US.utf8:

`echo $LANG`
returns 
`en_US.utf8`

and I tried `LANG=en_US.utf8 python3 -m pipx ensurepath` but it still comes back with the same error and it's really confusing:(

here is the `echo $PATH` result:
`/home/yasser/node_modules/ /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin`

Thanks!

**Comment by AltamimiYasser** [comment]
UPDATE: 
I seem to have figured out the problem so fast after responding :)

I'm using fish shell and thought maybe that's the problem, so I changed to bash and ran the command again an got:

`⚠️  All pipx binary directories have been added to PATH. If you are sure you want to proceed, try again
with the '--force' flag.

Otherwise pipx is ready to go! ✨ 🌟 ✨
`
so I guess it's a fish conflict of some sort but I don't know what.

Thanks a lot for your help!

**Comment by itsayellow** [comment]
You should note, however, that if your default shell is fish, then running `pipx ensurepath` in bash may not affect your `PATH` when using fish.

You can see the commands added by looking for the text `pipx` in the comments before the new PATH commands in `.profile`, `.bashrc`, etc.:
```shell
grep 'Created by `pipx`' ~/.*
```

**Comment by AltamimiYasser** [comment]
Thank you so much.
I manually added the path to the fish shell and now everything is working as expected. I can close this now but I'll leave it up to you if other people have the same problem

Thanks again

**Comment by 62f** [comment]
"unix-y", is that what they're calling POSIX these days? Also, what good does it do to manually set $LANG to something which it is already set, does pipx unset $LANG or do some 'unix-y' systems neglect to set it or are certain invariables temporarily disengaged or negated for certain ops. / shells?

**Comment by itsayellow** [comment]
> "unix-y", is that what they're calling POSIX these days? Also, what good does it do to manually set $LANG to something which it is already set, does pipx unset $LANG or do some 'unix-y' systems neglect to set it or are certain invariables temporarily disengaged or negated for certain ops. / shells?

The workaround sets `LANG` in an attempt to change the shell's locale to use the encoding `"utf-8"` which was what the code in the `userpath` python package expected.  (We use `userpath` to implement `pipx ensurepath`)  The code in `userpath` has since been updated to no longer assume `"utf-8"` so hopefully in the future neither the problem nor the workaround will be an issue.
