### ISSUE TITLE
--verbose is not documented by the offline error help message as a valid input, especially considering the fact that pipx denies its own existence.

### ISSUE THREAD

**Issue by 62f** [pypa/pipx#696]
I don't quite understand what the problem is.

pipx doesn't have a `--verbose` argument to pipx itself, only after a pipx subcommand.  In general pipx needs to be run with a sub-command, the only exceptions being `-h` or `--version` (as the help text describes.)

As is typical (and helpful) for other CLI applications, when you supply an argument to pipx that isn't accepted, it responds with a help message showing the forms of the pipx command that it will accept.

_Originally posted by @itsayellow in https://github.com/pypa/pipx/issues/694#issuecomment-849272551_

Supplication is that an abbreviated form eg. ```-v``` of ```--verbose``` also be available, and made functional when used, in a less-than-occult manner as per request made in issue#694.

**Comment by itsayellow** [comment]
Sorry, I don't see a reason to add a --verbose option for doing nothing.

**Comment by 62f** [comment]
ℑ𝔱 𝔴𝔬𝔲𝔩𝔡 𝓈𝑒𝑒𝓂 that my request was either not at all understood, was dismissed in its entirety, or 卩乇尺卄卂卩丂 ᗷOTᕼ.
2l͓̽;d̾r̾? 🅃🄾🄾 🄼🄰🄽🅈 i͓̽t͓̽e͓̽m͓̽s͓̽ 🄸🄽 🄾🄽🄴 🄱🄾🅇? ШΣLL DΔMΠ
