### ISSUE TITLE
Support `pipx run package==version` without spec

### ISSUE THREAD

**Issue by henryiii** [pypa/pipx#697]
**How would this feature be useful?**
Currently, if you run a command like this:

```console
$ pipx run build==0.4.0 --help
'build==0.4.0' executable script not found in package 'build==0.4.0'. Available executable scripts: pyproject-build
$ pipx run twine==3.4.1 --version
'twine==3.4.1' executable script not found in package 'twine==3.4.1'. Available executable scripts: twine
```

It installs the right package, but looks for an entrypoint with the package selection portion included.

**Describe the solution you'd like**

This should ideally just take the package argument and look for that, not including the `==` or other version comparison portion. If you really do have an entrypoint called `build==0.4.0`, I think that should require `pipx run --spec build==0.4.0 build==0.4.0`, since that does not match the package name (and you should probably rethink your life choices...)

**Describe alternatives you've considered**

Currently you must use `--spec` to get `pipx run --spec build==0.4.0 build`, adding a pin or limit requires you use `--spec`. Even though it does download the right package.

**Comment by itsayellow** [comment]
I think this is probably good, and in fact I thought this came up once but I couldn't find it in the issues to reference.

The current syntax with `--spec` is more verbose than necessary, I agree.

**Comment by uranusjr** [comment]
I feel this should extend to other specifiers as well, e.g. `pipx run "build>=0.3.0"` should run the `build` entry point as well.

**Comment by henryiii** [comment]
This should also work with `[]`; `pipx run build[virtualenv]` should work.
