### ISSUE TITLE
Migrate documentation build to the readthedocs 

### ISSUE THREAD

**Issue by gaborbernat** [pypa/pipx#698]
## Benefits for doing this:

- documentation built on PR review
- consistency with other PyPA projects
- we could have our documentation under https://pipx.pypa.io

## Downsides
- need to change how things work now
- we'd need to move from our new home at pypa.github.io/pipx

@itsayellow @cs01 @uranusjr can create a PR if happy with this.

**Comment by pradyunsg** [comment]
> need to change how things work now

I wanna clear one of the things that doesn't need to change: You can use mkdocs with ReadTheDocs. It's a supported tool, in addition to Sphinx.

**Comment by uranusjr** [comment]
Does RTD support mkdocs? I'm totally fine with this but wouldn't be happy if the switch involves rewriting the entire documentation.

**Comment by gaborbernat** [comment]
> I wanna clear one of the things that doesn't need to change: You can use mkdocs with ReadTheDocs. It's a supported tool, in addition to Sphinx.

We'd need to migrate away from the way we currently publish documentation 😊 So some change must happen because that how would be managed by readthedocs.

**Comment by pradyunsg** [comment]
> We'd need to migrate away from the way we currently publish documentation 😊

Yup yup, just wanted to answer what I expected to be the obvious first question. :)

**Comment by ericholscher** [comment]
Just wanted to follow up here and see if there is anything we can do to make this migration any easier? We'd love to get more pypa projects using RTD ✨

**Comment by gaborbernat** [comment]
I think we just need someone to do the heavy lifting :blush: otherwise we'd be happy to do this.

**Comment by chrysle** [comment]
> +0.5 from me then, I don't see the benefits, but if someone wants to do it I have no objections either.

@uranusjr Well, one benefit would be automatic publishing of `latest` documentation. Also, it'd enable previewing the docs from pull requests. Could you have a look at the PR implementing this?

**Comment by astrojuanlu** [comment]
And pull request diffs too: https://github.com/readthedocs/addons#docdiff

![image](https://github.com/pypa/pipx/assets/316517/7c855dd8-5f9c-4c88-8739-a7cc28336ce1)

**Comment by gaborbernat** [comment]
cc @cs01 I think we need to address this integration we have (I don't have rights to do it myself, perhaps some other owner can also do it).

Hello,

Previously, manually configured webhooks from integrations did not have a secret attached to them. In order to improve security, we have deployed an update so that all new integrations will be created with a secret, and we are deprecating old integrations without a secret. You must migrate your integration by January 31, 2024, when they will stop working without a secret.

We are contacting you because you have at least one integration that does not have a secret set. These integrations are:

    https://readthedocs.org/dashboard/pipx/integrations/249934/
    https://readthedocs.org/dashboard/pipx/integrations/249935/

If you aren't using an integration, you can delete it. Otherwise, we recommend clicking on "Resync webhook" to generate a new secret, and then update the secret in your provider's settings as well. You can check [our documentation](https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html) for more information on how to do this.

You can read more information about this in our blog post: https://blog.readthedocs.com/security-update-on-incoming-webhooks/.

**Comment by chrysle** [comment]
RTD is now up and running on https://pipx.pypa.io (see #1058). However the page points to the development version right now. I think someone should tag the latest release with stable.
And the builds are failing due to a missing configuration file?

**Comment by gaborbernat** [comment]
<img width="827" alt="image" src="https://github.com/pypa/pipx/assets/690238/416c0014-9229-4df1-916c-d6db67b243bb">
PR builds are now on, see https://github.com/pypa/pipx/pull/1118 and it passed.

**Comment by webknjaz** [comment]
Final action items FYI: https://github.com/pypa/pipx/issues/1058#issuecomment-1836294944

**Comment by chrysle** [comment]
> We need to cut a new release first to have what to tag as stable.

Let's do this soon, I think it's due now and the problem with building the `stable`
 version will supposedly solve itself without tagging... RTD took our latest released version and didn't find the configuration file in it.

**Comment by gaborbernat** [comment]
Done.

**Comment by chrysle** [comment]
According to [this blog post](https://blog.readthedocs.com/addons-flyout-menu-beta/), features like the flyout menu and warning banners, which I think are quite handy, should be available to us, but they don't appear on the website. Did someone opt out of the beta?

**Comment by astrojuanlu** [comment]
Most likely addons have not been enabled. A project admin must do it here:

```
https://beta.readthedocs.org/dashboard/{{ project_slug }}/addons/edit/
```

**Comment by chrysle** [comment]
@gaborbernat Could you have a look?

**Comment by webknjaz** [comment]
I've gone ahead and enabled it there.

**Comment by chrysle** [comment]
@webknjaz Thanks! However the flyout menu still isn't visible. Probably there are some settings to select which addons are to be used?

**Comment by webknjaz** [comment]
I triggered docs rebuilds. Do you not see it still? Maybe, it doesn't work with mkdocs?

**Comment by astrojuanlu** [comment]
:batman_signal: @humitos

**Comment by humitos** [comment]
@astrojuanlu thanks for the ping! I saw the signal and came as fast as I could 😄 

I found the issue. There is a bug in our data validation and because of that, the addon is disabled to avoid initializing it with corrupted data and break other stuffs. It wasn't considering the case for projects with "multiple versions and no translations", which is how `pipx` is defined in Read the Docs.

I prepared a PR to solve this issue and hopefully I will be able to deploy it soon 🚀 . I will let you know here when it's deployed.

**Comment by humitos** [comment]
I created a new released and deployed the changes. It works now! 🚀 

Feel free to ping me if you need me or open an issue at https://github.com/readthedocs/addons if there is anything else not working as expected 👍🏼 

![Screenshot_2024-01-17_10-23-11](https://github.com/pypa/pipx/assets/244656/79615236-fcde-458f-80ce-1f5d8c707628)
