### ISSUE TITLE
Consider redirecting pipxproject.github.io to the new site

### ISSUE THREAD

**Issue by geofft** [pypa/pipx#699]
**How would this feature be useful?**
Now that the docs have been moved to https://pypa.github.io/pipx/ , the old documentation at https://pipxproject.github.io/pipx/ (and pages under it like https://pipxproject.github.io/pipx/how-pipx-works/ etc.) are all broken links. It would be useful to redirect them to the new site. There are a fair number of links to the old site.

**Describe the solution you'd like**
I don't think GitHub has a way to do real redirects, but you could put meta-tag redirects for the old site - preferably for every page but possibly for just the home page.

**Describe alternatives you've considered**
Put up a page indicating that the docs have moved but don't do a redirect.

**Comment by strangemonad** [comment]
+1 google search results are still showing `https://pipxproject.github.io/*` a 301 / moved permanently redirect would be great.

**Comment by gaborbernat** [comment]
Yeah, we'd need to recreate the original project and put a redirect page for it. @itsayellow @cs01 can you recreate the project under the original org?

**Comment by itsayellow** [comment]
I'm a bit busy right now but will try to look into this soon.  I'm guessing we can just make a website without the "pipx" repo?

**Comment by smorel-plenty** [comment]
Related. I also noticed that the project description on pypi still points to the old url for the documentation link https://pypi.org/project/pipx/

**Comment by itsayellow** [comment]
> Related. I also noticed that the project description on pypi still points to the old url for the documentation link https://pypi.org/project/pipx/

Yes, I think all the metadata is updated such that this will change with the next release.

**Comment by itsayellow** [comment]
In fact that's probably a good reason to do a new release right now. 😄

**Comment by itsayellow** [comment]
AFAI can tell, it looks like our pypi project homepage now links to all the proper URLs after releasing 0.16.3.

I'll try to look into making a forwarding website at https://pipxproject.github.io/pipx/ this weekend.

**Comment by itsayellow** [comment]
OK, setup up a redirect site.  All the old https://pipxproject.github.io/pipx/ pages should now redirect to https://pypa.github.io/pipx/.

I couldn't do a real 301 Permanent Redirect using Github pages, but from my web research it seems that using the HTML `<meta http-equiv="refresh">` and `<link rel="canonical">` tags in the header is second best.
https://opensource.com/article/19/7/permanently-redirect-github-pages

**Comment by itsayellow** [comment]
Redirecting pages source: [pipxproject/pipxproject.github.io](https://github.com/pipxproject/pipxproject.github.io/)
