### ISSUE TITLE
How can I see what packages I have injected into a pipx venv?

### ISSUE THREAD

**Issue by halloleo** [pypa/pipx#707]
**How would this feature be useful?**

Sometimes I want to replica an pipx virtualenvironment on another machine, for this it would be great if I could see on the original machine what packages I injected into a pipx venv.

**Describe the solution you'd like**
The best would be a pipx cli command, but if there is a file in the venv I can look the information up in, that would be OK too.

**Comment by uranusjr** [comment]
Does `pipx list --include-injected` cover that?

**Comment by halloleo** [comment]
Yes, that's what I was looking for. Thanks!
