### ISSUE TITLE
upgrade . does uninstall all packages?

### ISSUE THREAD

**Issue by halloleo** [pypa/pipx#708]
**Describe the bug**
I had installed a local pagage (with a pyproject.toml file) via

    pipx install .

Later I tried to upgrade it with 

    pipx upgrade .

I got an error message and did the explicitly an uninstall and install - and *somehow* all packages (apart from the local one) are now gone!

I'm not sure whether I did something else which caused this or this is indeed a bug in pipx, sorry.

**Comment by uranusjr** [comment]
What error did you get?

**Comment by halloleo** [comment]
I didn't capture the exact message, but it was something to the extend: "_Cannot do an upgrade, please uninstall then reinstall._"

**Comment by itsayellow** [comment]
The uninstall bug came up in #631 but should be fixed in current versions of pipx.

Which version of pipx are you using? (i.e. run `pipx --version`)

**Comment by itsayellow** [comment]
BTW typically for `pipx upgrade` you would use the **name** of the package (i.e. one of the names seen in the listing from `pipx list`) instead of the directory name.

Based on your error / warning messages I'm wondering if you have an old version of pipx?

**Comment by halloleo** [comment]
> BTW typically for `pipx upgrade` you would use the **name** of the package (i.e. one of the names seen in the listing from `pipx list`) instead of the directory name.

Well, I will from now on... 😵

> Based on your error / warning messages I'm wondering if you have an old version of pipx?

Yep, it is certainly an old version. Can’t check it now though. Needs to wait until next week.

**Comment by meowmeowmeowcat** [comment]
@halloleo I guess this be closed as fixed?

**Comment by halloleo** [comment]
Yes, this is fixed. Thanks.
