### ISSUE TITLE
Unable to install on Mac OS X Big Sur with homebrew

### ISSUE THREAD

**Issue by maxh** [pypa/pipx#709]
**Describe the bug**
Unable to install with homebrew on OS X 11.4.

**How to reproduce**
```sh
% brew install pipx
Updating Homebrew...
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/manifests/1.18.1_1
#=#=#
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "gdbm_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/gdbm/manifests/1.18.1_1
```

**Expected behavior**
Successful installation. Using the alternative `python3` commands worked.

**Comment by uranusjr** [comment]
This looks like a configuration without your Homebrew installation. We don’t maintain ghcr.io and anything on it.

**Comment by uranusjr** [comment]
I can’t pretend to understand Homebrew but it’s interesting that solves it. Thanks for sharing.

**Comment by itsayellow** [comment]
> Thanks. Reinstalling Mac OS X command line tools fixed this for me; in case anyone else runs into the same error.

Usually that happens when the program needs to be compiled, but that shouldn't be necessary with macos 11.4.  "bottles" are how Homebrew distributes pre-compiled versions of software.  Judging from the error message maybe the "bottle" functionality is not working with your Homebrew installation?  Or just a network hiccup?

**Comment by cs01** [comment]
Who maintains the pipx brew package? Maybe they can help. Is it still @AlJohri?

**Comment by AlJohri** [comment]
Could be an issue with curl: https://superuser.com/questions/1647213/brew-install-fails-downloading-from-ghcr-io-macos-mojave

See the linked github issue for more details.

Doesn't seem related to pipx.
