### ISSUE TITLE
Add `pipx hook` command

### ISSUE THREAD

**Issue by paulmelnikow** [pypa/pipx#713]
Hi! Thank you for this _fabulous_ tool!

**How would this feature be useful?**

Conda offers a command `conda shell.{bash|zsh|fish} hook` which can be invoked from scripts to bring the Conda environment into the current shell.

The boilerplate Conda adds to rcfiles actually invokes this command! But it's [also useful for scripts](https://erictleung.com/conda-in-subshell-script) which install a sequence of tools (Conda, pipx, Poetry) to bootstrap a developer's Python environment, with minimal interaction on their part.

I'm running `pipx ensurepath` from my bootstrap script, however it doesn't take effect until starting the next shell. Starting a new shell is a rather clunky thing to do in the middle of a shell script execution.

**Describe the solution you'd like**

A `pipx hook {bash|zsh|fish}` command which outputs `set -x PATH $PATH /Users/pnm/.local/bin` or something similar, which updates and exports `PATH` in the current shell.

Another alternative (a little less nice I guess) would be a command like `pipx bindir` which resolves pipx's config and just prints `/Users/pnm/.local/bin`.

**Describe alternatives you've considered**

My workaround is to hard-code ~/.local/bin in my bootstrap script. This works, however I'd have more confidence using a pipx command since I know it will honor pipx's config. It also makes the intention of my bootstrap script more self-documenting.

**Comment by uranusjr** [comment]
I wonder if it’s better for pipx to only output the last part (`/Users/pnm/.local/bin` in your example) and let the surrounding script format the appropriate command. This way pipx doesn’t need to add any shell-specific stuff (which I’ve always felt is an anti-pattern).

**Comment by paulmelnikow** [comment]
> I wonder if it’s better for pipx to only output the last part (`/Users/pnm/.local/bin` in your example) and let the surrounding script format the appropriate command. This way pipx doesn’t need to add any shell-specific stuff (which I’ve always felt is an anti-pattern).

Yep, something like `pipx bindir` or `pipx bindirs` would be just fine for my application. Since I'm running this from a shell I know the syntax I need.

That said, I do think that shell specifics could be considered "necessary complexity" for a program like conda or pipx that wants to make an easy experience for the user – who, for better or worse, may not be super-familiar with editing dotfiles. (As someone who works on DX, I can tell you this is the majority of developers. I don't make a value judgement here, just an observation.) So while I think I do think `export PATH=$(pipx bindirs):$PATH` is workable and very explicit, `eval "$(pipx hook zsh)"` feels like it's at a more helpful level of abstraction (which is similar to `pipx ensurepath`). But either of these would be nice.

> Also, does `pipx ensurepath` not more or less cover the same ground?

No, it doesn't. I'm using this in my script to modify the user's dotfiles. However it does not (nor can it) modify the environment of the shell from which it's invoked. This is a problem, since later steps in my script need to invoke the pipx-installed programs.

**Comment by uranusjr** [comment]
That makes sense, thanks. Would you be interested in contributing such a command? I feel we can extend the idea to something like `pipx environment`, `pipx constants`, or something like that (I’m not good at naming things). This would print the variables pipx uses in `pipx.constants`, such as `PIPX_HOME`, `PIPX_SHARED_LIBS`, and `PIPX_BIN_DIR` (the last is the one you’re looking for). The format can be something like

```
PIPX_HOME=/home/user/.local/pipx
PIPX_SHARED_LIBS=/home/user/.local/pipx/shared
PIPX_BIN_DIR=/home/user/.local/bin
```

and we can maybe have an option to print a specific value like

```
$ pipx environment --value=PIPX_BIN_DIR
/home/user/.local/bin
```

Not sure what best to design this, other ideas are definitely welcomed.

**Comment by itsayellow** [comment]
@uranusjr, I like this way in general too, it's nice to have a way to create config with all the defaults populated in case you want to copy and hand-edit them.

**Comment by uranusjr** [comment]
Anyone interested in actually implementhign this? 😉

**Comment by meowmeowmeowcat** [comment]
Hi @uranusjr, I am going to implement this. 👍
