### ISSUE TITLE
AWSCLI gives "ModuleNotFoundError: No module named 'awscli'" on Windows

### ISSUE THREAD

**Issue by takacsd** [pypa/pipx#719]
**Describe the bug**
Installed pipx (0.16.3) on python 3.9.6 on Windows.
Installed awscli (1.20.6) without any issue.
When I try to run any aws command I get:
```
Traceback (most recent call last):
  File "C:\Users\******\.local\bin\aws.cmd", line 50, in <module>
    import awscli.clidriver
ModuleNotFoundError: No module named 'awscli'
```

**How to reproduce**
```
C:\> pipx install --verbose awscli
pipx >(setup:717): pipx version is 0.16.3
pipx >(setup:718): Default python interpreter is 'c:\\python39\\python.exe'
pipx >(package_name_from_spec:323): Determined package name: awscli
pipx >(package_name_from_spec:324): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:135): running c:\python39\python.exe -m venv --without-pip C:\Users\*****\.local\pipx\venvs\awscli
pipx >(run_subprocess:135): running C:\Users\*****\.local\pipx\venvs\awscli\Scripts\python.exe -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:135): running C:\Users\*****\.local\pipx\shared\Scripts\python.exe -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:135): running C:\Users\*****\.local\pipx\venvs\awscli\Scripts\python.exe --version
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: awscli
installing awscli...
pipx >(run_subprocess:135): running C:\Users\*****\.local\pipx\venvs\awscli\Scripts\python.exe -m pip install awscli
pipx >(run_subprocess:135): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:303): get_venv_metadata_for_package: 1016ms
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: awscli
pipx >(needs_upgrade:69): Time since last upgrade of shared libs, in seconds: 260972. Upgrade will be run by pipx if greater than 2592000.
  installed package awscli 1.20.6, Python 3.9.6
  These apps are now globally available
    - aws
    - aws.cmd
    - aws_bash_completer
    - aws_completer
    - aws_zsh_completer.sh
done! ✨ 🌟 ✨

C:\> aws
Traceback (most recent call last):
  File "C:\Users\*****\.local\bin\aws.cmd", line 50, in <module>
    import awscli.clidriver
ModuleNotFoundError: No module named 'awscli'
```
**Expected behavior**
It should just work I guess. ;)

**Comment by uranusjr** [comment]
This looks like an issue with `awscli`, it assumes the package is installed to the “default” Python command, not in a virtual environment. This can only be fixed by `awscli`.

**Comment by c22** [comment]
As a workaround for pipx users on Windows, you can manually edit the aws.cmd file to bypass this issue.

Basic instructions:

open `C:\Users\c22\.local\pipx\venvs\awscli\Scripts\aws.cmd` in your text editor of choice

change line 4 `set PythonExe=""` to point to your pipx venv python.exe

eg.

`set PythonExe="C:\\Users\\c22\\.local\\pipx\\venvs\\awscli\\Scripts\\python.exe"`

See the output of `pipx list --json` if you have trouble finding the right files/paths.

Depending on your setup, you may also wish to suppress the error output of the `assoc` call in aws.cmd by making the same change to the aws.cmd script as proposed in https://github.com/aws/aws-cli/pull/6449

Hopefully the AWS CLI team will be open to accepting further improvements to the aws.cmd file and we can get it playing nice with pipx.
