### ISSUE TITLE
pipx warns that my PATH is not in PATH if there's a symlink.

### ISSUE THREAD

**Issue by WhyNotHugo** [pypa/pipx#720]
**Describe the bug**

pipx warns that my `$PATH` is not in my `$PATH`. I believe it's due to the way it's resolving symlinks:

```
$ pipx install proselint
  installed package proselint 0.11.3, Python 3.9.6
  These apps are now globally available
    - proselint
⚠️  Note: '/home/hugo/.dotfiles/home/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until
    your PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your PATH in your shell's config file (i.e.
    ~/.bashrc).
done! ✨ 🌟 ✨
```

Note that `/home/hugo/.dotfiles/home/.local/bin` is a regular directory, whereas `/home/hugo/.local/bin` is a symlink to the former.

It seems that `pipx` is resolving the symlink and _then_ checking whether it's in `$PATH`, but it should just check if `~/.local/bin`is in `$PATH` without doing the symlink resolution.

**How to reproduce**

```bash
mv ~/.local/bin ~/.local/bin-old
ln -s ~/real-bin ~/.local/bin
pipx install proselint
```

**Expected behavior**

There should be no warning.

**Notes**

This is a symlink since i keep my scripts in a `dotfiles` repository. There's honestly a bit of a conflict with `pipx` using that same directory for its entry points, but I intend to just git-ignore them.

(Edit: Never mind this last bit, I'd misread that issue).

**Comment by uranusjr** [comment]
Is #329 the same issue? It has been fixed in the main branch but not yet released.

**Comment by WhyNotHugo** [comment]
You're very right, thanks!
