### ISSUE TITLE
`pipx` reports incorrect python version

### ISSUE THREAD

**Issue by yoursvivek** [pypa/pipx#721]
**`pipx` reports incorrect python version**

Older python version (one at the time of package installed) reported by `pipx list`, despite global python version being upgraded.

In following demonstration, `black` was installed using pipx when system python3 version was 3.8.5. `build` was installed on a later day when python3 version was upgraded to 3.8.10 and no python-3.8.5 installed.

```
❯ pipx --version 
0.16.3
❯ pipx list 
venvs are in /home/vivek/.local/pipx/venvs
apps are exposed on your $PATH at /home/vivek/.local/bin
   package black 21.7b0, Python 3.8.5
    - black
    - black-primer
    - blackd
   package build 0.5.1, Python 3.8.10
    - pyproject-build
❯ which black
/home/vivek/.local/bin/black
❯ head /home/vivek/.local/bin/black
#!/home/vivek/.local/pipx/venvs/black/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from black import patched_main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(patched_main())
❯ /home/vivek/.local/pipx/venvs/black/bin/python --version 
Python 3.8.10
```

**How to reproduce**
* Install python 3.8.5, install pipx
* Install black (pipx install black)
* upgrade python to say 3.8.10
* Install build (pipx install build)
* Run demostration in previous section.

Notably, in my set up pipx itself is managed by pipx. (Initially installed as `python -m pip install --user pipx && python -m pipx install pipx && python -m pip uninstall pipx`)  

**Expected behavior**
python version reported by `pipx list` should match the version of python interpreter being used app.

**Comment by uranusjr** [comment]
Did you update the underlying Python of `/home/vivek/.local/pipx/venvs/black/bin/python` in-place? `pipx list` outputs the Python version recorded *at the time Black was installed*, not the Python version running it right now. So if you do something like

```
$ python-build 3.8.5 /path/to/python-prefix
$ pipx install black --python /path/to/python-prefix/bin/python
$ python-build 3.8.10 /path/to/python-prefix
```

then `pipx list` would output 3.8.5, not 3.8.10. This is useful for debugging since if an installed app breaks, you can use this information to know whether it’s an issue with the underlying Python.

Maybe we should format the output better to indicate this.

**Comment by yoursvivek** [comment]
1. 
> Did you update the underlying Python of /home/vivek/.local/pipx/venvs/black/bin/python in-place?

Not explicitly, but during upgrade on system it was.

```
❯ readlink -f  /home/ocrolus/.local/pipx/venvs/black/bin/python 
/usr/bin/python3.8
```
2.
> pipx list outputs the Python version recorded at the time Black was installed, not the Python version running it right now
> ... 
> Maybe we should format the output better to indicate this.

I completely agree. Current output is not communicating what it intends to.

**Comment by yoursvivek** [comment]
1. 
> Did you update the underlying Python of /home/vivek/.local/pipx/venvs/black/bin/python in-place?

Not explicitly, but during upgrade on system it was.

```
❯ readlink -f  /home/vivek/.local/pipx/venvs/black/bin/python 
/usr/bin/python3.8
```
2.
> pipx list outputs the Python version recorded at the time Black was installed, not the Python version running it right now
> ... 
> Maybe we should format the output better to indicate this.

I completely agree. Current output is not communicating what it intends to.

**Comment by uranusjr** [comment]
Contributions on an improvement would be most appreciated 🙂
