### ISSUE TITLE
XDG compatibility

### ISSUE THREAD

**Issue by glensc** [pypa/pipx#722]
`pipx` installs stores all it's files to `~/.local/pipx`, but that's not what [XDG spec says][xdg-spec].

These should be probably changed to match:

- `~/.local/pipx/logs` -> `$XDG_STATE_HOME/pipx/logs`
- `~/.local/pipx/shared` -> `$XDG_DATA_HOME/pipx/shared`
- `~/.local/pipx/venvs` -> `$XDG_DATA_HOME/pipx/venvs`

venvs could be `$XDG_STATE_HOME/pipx/venvs`, but I looked virtualenvs are stored in `~/.local/share/virtualenvs`.

when implementing, then for safe migration purposes, `pipx` should use old paths if it finds the parent directory (`~/.local/pipx`) present, otherwise use the new standards confirming paths.

[xdg-spec]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by Baerbeisser** [comment]
Btw, `.../pipx/.cache` shouldn't that be ~/.cache?
I would even go as far as calling it a bug, always that litter in backups everywhere, pipx is not the only one...

**Comment by uranusjr** [comment]
Feel free to propose a PR on this. Note that since moving environments directly would result in broken installations, this _should not_ move existing environments, and would need to implement some sort of fallback mechanism to look in the old locations when relevant things are not found in new (default) locations.

**Comment by pandark** [comment]
> venvs could be `$XDG_STATE_HOME/pipx/venvs`, but I looked virtualenvs are stored in `~/.local/share/virtualenvs`.
Depending on when they adhered to the XDG base directory spec, there may not have been a `$XDG_STATE_HOME` in it yet at the time (it was added a year and a half ago).

**Comment by schaarsc** [comment]
there is also
`~/.local/pipx/.cache` --> `$XDG_CACHE_HOME/pipx`
