### ISSUE TITLE
Rename default branch to 'main'

### ISSUE THREAD

**Issue by jaraco** [pypa/pipx#724]
In order to honor principles of maximum inclusiveness, other projects in pypa have renamed their master branches to main. Would this project consider doing the same?

**Comment by gaborbernat** [comment]
I'm +1 on this, I think only @matthew-brett and @cs01 has those rights though :+1:

**Comment by DiddiLeija** [comment]
I think this is a good practice. I'm also +1 on this :+1:

**Comment by cs01** [comment]
Yes this is something we can do. I am not exactly sure who has rights to do so. If anyone else does, feel free to make the change. Otherwise I will do it when I have the time.

**Comment by jaraco** [comment]
It is done. I used the [routine I described here](https://blog.jaraco.com/switch-to-main-xonsh/). Now the master branch is gone, replaced by main, and with the open PRs pointing to the new main. You'll want to re-clone your local repo or rename your local master branch.
