### ISSUE TITLE
Run console scripts whose name doesn't match package name

### ISSUE THREAD

**Issue by tusharsadhwani** [pypa/pipx#725]
For eg:

```console
$ pipx run textflip            
'textflip' executable script not found in package 'textflip'. Available
executable scripts: flip
```

So it does know about the script named `flip`, but I can't seem to figure out how to make it run that.

I've tried doing:

- `pipx run textflip.flip`
- `pipx run textflip --spec flip`
- `pipx run textflip flip` etc.

None of these seem to work, and I can't seem to find the relevant documentation.

**Comment by tusharsadhwani** [comment]
Also, for whatever reason, `pipx run textflip.flip` seems to be translated into `pipx run textflip.flip`, which I don't think would ever be what I intended to do. Is that intended behaviour?

**Comment by cs01** [comment]
Try moving the spec argument. It’s being interpreted as an argument to the program you are running. 

pipx run --spec PACKAGE APP

**Comment by tusharsadhwani** [comment]
```console
$ pipx run --spec=textflip flip hello
oןןǝɥ
```

Yup, that does work. But it feels really unintuitive to me, the `--spec` param name, and the fact that the app name is being passed as an optional parameter and the `console_script` name is being passed as the default argument. I would assume it would be the other way around.

Something like:

```console
$ pipx run --script=flip textflip
```

And `pipx run textflip.flip` would probably be the most ideal.

**Comment by uranusjr** [comment]
The syntax you suggested is not possible since `textflip.flip` is a valid package name.

**Comment by uranusjr** [comment]
An error message improvement would definitely be nice.

> And in cases where there's a single executable, but with a different name than the package (usually a shorter command name for convenience), the user's intention is clearly to run that one. Maybe pipx could just run textflip.flip in this case?

Makes sense to me (if we add a line reminding the user what command is actually being invoked). Fancy a contribution?

**Comment by tusharsadhwani** [comment]
Some comments for the future: Maybe some extra metadata could be added into `pyproject.toml` to tell it what the default runnable module is inside this package. If unspecified the top level package is taken.

**Comment by tusharsadhwani** [comment]
> Fancy a contribution?

I could take it up if you want!

**Comment by uranusjr** [comment]
> Maybe some extra metadata could be added into `pyproject.toml` to tell it what the default runnable module is inside this package.

There’s already a mechanism for that introduced in #615.

> I could take it up if you want!

Go ahead!

**Comment by cs01** [comment]
I just did a quick search from my phone, but didn’t see it in the docs — is pipx.run captured in our documentation anywhere? We should add a section dedicated to adding pipx support for one’s package and add that to it.
