### ISSUE TITLE
pipx ensurepath fails to do the right thing for csh shells

### ISSUE THREAD

**Issue by mhucka** [pypa/pipx#728]
**Describe the bug**

I tried to install and use `pipx` for the first time, but ran into a limitation: it only appears to know how to edit `.bashrc`/`.profile` files and not `.cshrc` files that are used by the csh shell or derivatives.

**How to reproduce**

I installed `pipx` on a macOS 10.14 system where I previously installed Python 3.9.5 using Homebrew but never installed `pipx` before. After installation, I followed the recommended step to run `pipx ensurepath`. The output looked promising:

```
> pipx ensurepath
Success! Added /Users/mhucka/.local/bin to the PATH environment variable.

Consider adding shell completions for pipx. Run 'pipx completions' for instructions.

You will need to open a new terminal or re-login for the PATH changes to take effect.

Otherwise pipx is ready to go! ✨ 🌟 ✨
```

but inspection of my home dot files showed that while `~/.bashrc` contained the following lines at the bottom,

```
# Created by `pipx` on 2021-08-18 00:18:57
export PATH="$PATH:/Users/mhucka/.local/bin"
```

the file that is relevent to the actual shell I'm running (the shell in which I ran the command above), my `~/.cshrc` file, did not have the same changes made. This means that contrary to the claims of having added `~/.local/bin` to my PATH, it did not do that for my shell.

**Expected behavior**

Evidently, pipx only knows what to do for sh/bash type shells. It could do the same things it does for those shells to the user's ~/.cshrc file too. I tried to search in the source code where this is being done, but haven't been able to find it. I would consider doing a PR if someone could point me to the right part of the code where the dot file munging is being done.

**Comment by meowmeowmeowcat** [comment]
@mhucka `pipx` uses [`userpath`](https://pypi.org/project/userpath/) for `ensurepath`. Therefore, I think whether the shell is supported, is depended on `userpath`. Currently, it supports these shells:
https://github.com/ofek/userpath/blob/829c31541ef4ed1251f4e8df8862567879c4e727/userpath/shells.py#L105-L111
