### ISSUE TITLE
Passing credentials with --index-url

### ISSUE THREAD

**Issue by gitpushdashf** [pypa/pipx#730]
Hi!

Is there a way to pass credentials with `--index-url`? I prepopulated my private pypi URL, but it did not seem to work at all (same URL works with pipenv. It just loops endlessly. I wonder if it should throw exceptions on HTTP 4XX, if it doesn't already, rather than trying over and over.

Not sure how pipx is supposed to work with private indexes.

Thank you!

**Comment by cs01** [comment]
This might help -- https://github.com/pypa/pipx/issues/458#issuecomment-667435942

**Comment by gitpushdashf** [comment]
Great, thank you! Sorry for the slow response.
