### ISSUE TITLE
"pipx install" exits with a non-zero status if package is already installed

### ISSUE THREAD

**Issue by anabeisy16** [pypa/pipx#738]
**Describe the bug**
`pipx install` fails with a non-zero status when the package is already installed. That can cause problems when `pipx install` is used within a bash script and can cause the script to be aborted.

**How to reproduce**
`vim test-script`
```
#!/usr/bin/env bash
set -euxo pipefail
pipx install  pipenv
echo "made it to next command"
```
If run `test-script` twice, the second execution will result in the following error:
`+ python3 -m pipx install workenv
'workenv' already seems to be installed. Not modifying existing installation in
'redacted/pipx/venvs/workenv'. Pass '--force' to force installation.`
Note that `made it to next command` is never printed

**Expected behavior**
Attempting to install a package that is already installed should result in a warning, not an error

**Comment by uranusjr** [comment]
Already fixed and released two days before the report.
