### ISSUE TITLE
setup for `pipx completions` not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by jugmac00** [pypa/pipx#748]
**Describe the bug**
Adding `eval "$(register-python-argcomplete pipx)"` causes the following error message

```
jugmac00@XPS-13-9310:~/bin$ bash

Command 'register-python-argcomplete' not found, did you mean:

  command 'register-python-argcomplete3' from deb python3-argcomplete (1.8.1-1.3ubuntu1)

Try: sudo apt install <deb name>
```

**How to reproduce**
- new Ubuntu 20.04
- install pipx
- call `pipx ensurepath` ...
```
jugmac00@XPS-13-9310:~/bin$ pipx ensurepath
Success! Added /home/jugmac00/.local/bin to the PATH environment variable.

Consider adding shell completions for pipx. Run 'pipx completions' for instructions.

You will need to open a new terminal or re-login for the PATH changes to take effect.
```

- run `pipx completions`
```
jugmac00@XPS-13-9310:~/bin$ pipx completions

Add the appropriate command to your shell's config file
so that it is run on startup. You will likely have to restart
or re-login for the autocompletion to start working.

bash:
    eval "$(register-python-argcomplete pipx)"

zsh:
    To activate completions for zsh you need to have
    bashcompinit enabled in zsh:

    autoload -U bashcompinit
    bashcompinit

    Afterwards you can enable completion for pipx:

    eval "$(register-python-argcomplete pipx)"

tcsh:
    eval `register-python-argcomplete --shell tcsh pipx`

fish:
    # Not required to be in the config file, only run once
    register-python-argcomplete --shell fish pipx >~/.config/fish/completions/pipx.fish
```

- add `eval "$(register-python-argcomplete pipx)"` to `.bashrc`
- open a new bash

```
jugmac00@XPS-13-9310:~/bin$ bash

Command 'register-python-argcomplete' not found, did you mean:

  command 'register-python-argcomplete3' from deb python3-argcomplete (1.8.1-1.3ubuntu1)

Try: sudo apt install <deb name>
```

**Expected behavior**
no errors

**Comment by meowmeowmeowcat** [comment]
@jugmac00 How did you install pipx? If you were using pip to install it, `register-python-argcomplete3` should be installed automatically.

**Comment by jugmac00** [comment]
@meowmeowmeowcat I installed `pipx` via `pip install pipx` inside a virtualenv 

```
$ which pipx
/home/jugmac00/bin/pipx

$ ls -la /home/jugmac00/bin/pipx 
lrwxrwxrwx 1 jugmac00 jugmac00 32 Okt  3 16:17 /home/jugmac00/bin/pipx -> /home/jugmac00/opt/pipx/bin/pipx
```

**Comment by jugmac00** [comment]
```
$ bin/pip list
Package     Version
----------- -------
argcomplete 1.12.3
click       8.0.1
packaging   21.0
pip         21.3.1
pipx        1.0.0
pyparsing   2.4.7
setuptools  58.1.0
userpath    1.7.0
wheel       0.37.0

~/opt/pipx$ bin/
activate-global-python-argcomplete            python-argcomplete-check-easy-install-script
pip                                           python-argcomplete-tcsh
pip3                                          register-python-argcomplete
pip3.8                                        userpath
pipx                                          wheel
python                                        wheel3
python3                                       wheel-3.8
python3.8                                     wheel3.8
```

I have symlinked only the `pipx` binary to `~/bin/pipx`; `~/bin` is on my path.

Oh, now I see - I guess I also need to symlink `register-python-argcomplete` to my `~/bin` directory.

That worked! Thanks for giving me the right pointer!

**Comment by vnktsh** [comment]
In my case the issue was because my PATH to `$HOME/.local/bin` was being set in `.profile` but `eval "$(register-python-argcomplete pipx)"` was done in `.bashrc`. Since `.bashrc` is loaded before `.profile`, there was a bit of race condition. I moved the `eval ...` to `.profile` and it was all good.

**Comment by danielizham** [comment]
> In my case the issue was because my PATH to `$HOME/.local/bin` was being set in `.profile` but `eval "$(register-python-argcomplete pipx)"` was done in `.bashrc`. Since `.bashrc` is loaded before `.profile`, there was a bit of race condition. I moved the `eval ...` to `.profile` and it was all good.

This solved it for me - moving the `eval` command to the `.profile` file. Thanks.

**Comment by Kevingroover** [comment]
I have the same issue, but am not familiar enough with terminal to understand how to fix this, would ya'll please explain how to move the eval command to .profile

**Comment by CoeJoder** [comment]
I had the same issue, but was able to fix it by using this
```eval "$(register-python-argcomplete3 pipx)"```
instead of this
```eval "$(register-python-argcomplete pipx)"```

**Comment by bhugh** [comment]
FYI using Ubuntu 24.04 I had the reverse problem:

.bashrc has this:

`eval "$(register-python-argcomplete3 pipx)"`

That throws a "Command not found" error.

Changing to this seems to fix it:

`eval "$(register-python-argcomplete pipx)"`

Presumably it is the same issue where the correct path is set up in .profile, but .profile is not run until after .bashrc.
