### ISSUE TITLE
0.16.5 release process issues

### ISSUE THREAD

**Issue by musicinmybrain** [pypa/pipx#757]
**Describe the bug**

Version 0.16.5 was released on GitHub (https://github.com/pypa/pipx/releases/tag/0.16.5) with an internal version of 0.16.4.1.dev0: https://github.com/pypa/pipx/blob/0.16.5/src/pipx/version.py

This affects the package metadata used by pip, etc.

Later, a commit entitled “Forgotten release dance” (https://github.com/pypa/pipx/commit/4a22f61d89ff93aa72b530c3fe4277fcb150e252) added the 0.16.5 version number to the changelog, and bumped the internal version number to 0.16.5.1.dev0.

There was never a commit with the correct version number 0.16.5 for this release.

Furthermore, the PyPI package is still at 0.16.4.

**How to reproduce**

Examine the PyPI and GitHub project pages and compare with the above descriptions.

**Expected behavior**

A single commit is tagged `0.16.5`, in which `src/pipx/version.py` contains `__version_info__ = (0, 16, 5)`. A release created from this commit appears on PyPI.

----

At this point, it might be easier to create a new, “clean” `0.16.6` release.

Thanks in advance for looking into this!

**Comment by musicinmybrain** [comment]
Any thoughts on this?

**Comment by cs01** [comment]
@gaborbernat i believe you were the last to make a release. Are you able to look into this?

**Comment by gaborbernat** [comment]
Eventually, but I don't have bandwidth for this now.
