### ISSUE TITLE
Documentation's home page is missing two images

### ISSUE THREAD

**Issue by NdagiStanley** [pypa/pipx#759]
**Describe the bug**

The home page - https://pypa.github.io/pipx/ is missing two images (.png and .gif)

**How to reproduce**

Head to the home page of pipx's documentation (https://pypa.github.io/pipx/) and confirm that the images do not render. See below. (I've used green arrows to show)

<img width="1649" alt="Screenshot 2021-11-16 at 14 01 44" src="https://user-images.githubusercontent.com/15629602/141973965-a6b2d0fc-4310-4f66-b8ec-7a3da9db3ab5.png">

**Expected behavior**

The images should render

<img width="1422" alt="Screenshot 2021-11-16 at 14 03 31" src="https://user-images.githubusercontent.com/15629602/141974144-0b86bb22-e170-47b0-b9b6-29cbadd96f43.png">

**Comment by mdsanima** [comment]
I think that's is fixed now.
