### ISSUE TITLE
Using pipx list command

### ISSUE THREAD

**Issue by WCHIHO** [pypa/pipx#766]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Comment by WCHIHO** [comment]
> Successfully installed pipx in jupyter notebook.
>Requirement already satisfied: pipx in c:\users\wchih\appdata\roaming\python\python38\site-packages (0.16.4)
Requirement already satisfied: packaging>=20.0 in c:\users\wchih\anaconda3\lib\site-packages (from pipx) (20.9)
Requirement already satisfied: colorama>=0.4.4 in c:\users\wchih\anaconda3\lib\site-packages (from pipx) (0.4.4)
Requirement already satisfied: argcomplete<2.0,>=1.9.4 in c:\users\wchih\appdata\roaming\python\python38\site-packages (from pipx) (1.12.3)
Requirement already satisfied: userpath>=1.6.0 in c:\users\wchih\appdata\roaming\python\python38\site-packages (from pipx) (1.7.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\wchih\anaconda3\lib\site-packages (from packaging>=20.0->pipx) (2.4.7)
Requirement already satisfied: click in c:\users\wchih\anaconda3\lib\site-packages (from userpath>=1.6.0->pipx) (7.1.2)
Note: you may need to restart the kernel to use updated packages.
> But, pipx is not recognized as a command and is a syntax error:
File "<ipython-input-10-7606060e9b76>", line 1
    pipx list
         ^
SyntaxError: invalid syntax

> pipx                               0.16.4  is listed in jupyter notebook !pip list.

**Comment by dukecat0** [comment]
Closing this since no further info is provided.
