### ISSUE TITLE
importing a package after using pipx in windows 10

### ISSUE THREAD

**Issue by MatteoZhang** [pypa/pipx#768]
**Describe the bug**
After I installed brownie from pipx the package brownie can't be imported on windows

**How to reproduce**
python3 -m pip install --user pipx
python3 -m pipx ensurepath
close shell reopen shell
pipx install eth-brownie
close shell reopen shell
venvs are in C:\Users\XXX\.local\pipx\venvs
apps are exposed on your $PATH at C:\Users\XXX\.local\bin
   package eth-brownie 1.17.1, Python 3.9.4
    - brownie.exe
**EVERYTHING fine till here**

python 
import brownie
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'brownie'**

**Expected behavior**
import brownie
(no errors)

**Comment by uranusjr** [comment]
pipx is not for installing packages to import, but for standalone applications that expose their interface as a command. For importable things, use pip.
