### ISSUE TITLE
Support for PEP 660

### ISSUE THREAD

**Issue by nnrm** [pypa/pipx#779]
**How would this feature be useful?**
Editable installs would be possible for pyproject.toml based builds

**Describe the solution you'd like**
Add support for [PEP 660](https://www.python.org/dev/peps/pep-0660/)

**Describe alternatives you've considered**
Pip already supports this with `pip install -e path/to/project`

**Comment by uranusjr** [comment]
What does not work? pipx simply passes `-e` on to pip, so if pip works, pipx does. Does it not work for you? How? What happened?

**Comment by nnrm** [comment]
Sorry, misunderstood how the build process works for pip, closing it for now.
