### ISSUE TITLE
Upgrade after installing via vcs?

### ISSUE THREAD

**Issue by arozans** [pypa/pipx#782]
This is not a feature request but rather a question.

Is it possible to detect that there is newer app version available on the upstream branch, after installing it from a git repo?

**Comment by gaborbernat** [comment]
I don't believe so at the moment.

**Comment by cs01** [comment]
Is should work roughly the same as with pip. Does pip let you do that (maybe you know @gaborbernat or @uranusjr)?

**Comment by uranusjr** [comment]
The recommended way to do this in pip right now is to uninstall/reinstall. There’s work on making `-U` work for this, but the implementation is not yet ready. https://github.com/pypa/pip/pull/10564

In terms of pipx I think we can simply implement `pipx upgrade foo` to uninstall `foo` and reinstall the same URL again.

**Comment by gaborbernat** [comment]
> In terms of pipx I think we can simply implement `pipx upgrade foo` to uninstall `foo` and reinstall the same URL again.

PR welcome.

**Comment by huxuan** [comment]
Seems this feature is already implemented. Pipx will detect the version and install the latest one. Any specific scenario we should cover?
