### ISSUE TITLE
Mark it as stable, release 1.0.0

### ISSUE THREAD

**Issue by gaborbernat** [pypa/pipx#784]
I think the project is used widely enough that we can commit to keeping it stable and drop the zero ver. What do you think maintainers? @cs01 @uranusjr @matthew-brett

**Comment by cs01** [comment]
I agree the tool has a high level of adoption and API maturity. I am not really feeling great about the level of active development and issue triage, but that's a separate issue. I'm fine if the version gets bumped to 1.0.0.

btw I think you tagged the wrong Matthew.

**Comment by gaborbernat** [comment]
Done via https://github.com/pypa/pipx/actions/runs/1652819946
