### ISSUE TITLE
add a bootstrap option to simplyfy commands or a way like ``pipx run pipx run --spec httpie https``

### ISSUE THREAD

**Issue by MaxPeal** [pypa/pipx#796]
**How would this feature be useful?**
add a posix shell script to bootstrap the usage of the uptodate pipx version on a minimal fresch system with a minimal python install.
its always a problem on a new build system or in CI build systems.

a run like 
pipx run pipx run --spec httpie https
looks not the like the right way

**Comment by meowmeowmeowcat** [comment]
See #579
