### ISSUE TITLE
pipx doesn't respect manually selected point releases on `upgrade`

### ISSUE THREAD

**Issue by tobwen** [pypa/pipx#802]
##  Describe the bug
In the following example, the system's headers and library of _gdal_ are in v3.2.2. Latest _gdal_ is on v3.3.2, so is _pygdal_ looking for this version, can't find it and breaks. Even when installed with `pygdal==3.2.2.*`, _pipx upgrade_ doesn't respect this limitation and the upgrade fails, since the installer can't find latest _gdal_:
```
_main__.GDALConfigError: Version mismatch 3.2.2 != 3.3.2
```

## How to reproduce
``` sh
$ apt-install libgdal-dev gdal-bin gdal-data # should be 3.2.2 on Debian
$ pipx install --include-deps pygdal==3.2.2.* # works
$ pipx upgrade pygdal # fails
```

It gets worse when _pygdal_ has been injected into another package. This completely fails then:
``` sh
$ pipx upgrade --include-injected --force mapproxy
```

## Expected behavior
Read `package_or_url` from pipx_metadata.json and limit it to the version stated in there.

## Workarounds
``` sh
pipx upgrade --pip-args 'install pygdal==3.2.2.*' pygdal
pipx upgrade --include-injected --pip-args 'install pygdal==3.2.2.*' mapproxy
```

## ~/.local/pipx/venvs/pygdal/pipx_metadata.json
``` json
{
    "injected_packages": {},
    "main_package": {
        "app_paths": [],
        "app_paths_of_dependencies": {
            "numpy": [
                {
                    "__Path__": "/home/tobwen/.local/pipx/venvs/pygdal/bin/f2py",
                    "__type__": "Path"
                },
                {
                    "__Path__": "/home/tobwen/.local/pipx/venvs/pygdal/bin/f2py3",
                    "__type__": "Path"
                },
                {
                    "__Path__": "/home/tobwen/.local/pipx/venvs/pygdal/bin/f2py3.9",
                    "__type__": "Path"
                }
            ]
        },
        "apps": [],
        "apps_of_dependencies": [
            "f2py",
            "f2py3",
            "f2py3.9"
        ],
        "include_apps": true,
        "include_dependencies": true,
        "package": "pygdal",
        "package_or_url": "pygdal==3.2.2.*",
        "package_version": "3.2.2.10",
        "pip_args": [],
        "suffix": ""
    },
    "pipx_metadata_version": "0.2",
    "python_version": "Python 3.9.2",
    "venv_args": []
}
```

**Comment by meowmeowmeowcat** [comment]
Currently `pipx upgrade` will ignore any version specifiers and upgrade the package to the newest version.

Maybe we can introduce a new option (probably `--include-version-spec`?) for users to upgrade their packages with version specifiers? i.e. ```
pip install -U package==20.0.*``` instead of `pip install -U package`.

**Comment by uranusjr** [comment]
Do we save the original user request in metadata? (I don’t quite remember) If we do, we should make `pipx upgrade` respect that original input, and introduce a new flag (say `pip upgrade --spec`) to ignore existing constraints.

**Comment by meowmeowmeowcat** [comment]
> Do we save the original user request in metadata?

`package_or_url` is the original user request, and `pipx upgrade` actually respects it. However, packages specifiers and markers are removed by this function:
https://github.com/pypa/pipx/blob/71fe102014393061fcb953609a5b5b2a763f4c0a/src/pipx/package_specifier.py#L176-L188

> and introduce a new flag (say `pip upgrade --spec`) to ignore existing constraints.

+1 on this. We can use that spec for upgrading (`pip install -U SPEC`).

**Comment by jaklan** [comment]
I would really love to have any solution for that issue - I used to run `pipx upgrade-all` automatically, but recently I wanted to maintain two Poetry versions: `1.1.x` and `1.2.x`. I've installed the previous one with `pipx install "poetry<1.2" --suffix 1.1`, but unfortunately when I run the upgrade comment - the constraint is not respected and it's being updated to `1.2.x`, so each time I have to reinstall it.

**Comment by jaklan** [comment]
Hah, it seems I can help myself here - there's some workaround:
`pipx install poetry --pip-args 'install poetry<1.2' --suffix 1.1`
This way the constraint is preserved.

**Comment by meowmeowmeowcat** [comment]
Maybe #891 can help with this case. Run `pipx pin poetry1.1` and then `pipx upgrade-all` will not upgrade it.

**Comment by jaklan** [comment]
> (But I am still implementing `pipx pin` and `pipx unpin`, so I guess it will be available in the next release.)

@dukecat0 what's the status of that? 😉

**Comment by dukecat0** [comment]
Hi @jaklan, I've implemented the logic of it before, but seems like the changes were dismissed accidentally, so I will try to work on it again.

**Comment by jaklan** [comment]
Great to hear, that would be a huge improvement! Btw, for `pipx upgrade-all` I believe the logic is quite simple - _upgrade all apps except the pinned ones_, but what is the plan for `pipx upgrade` behaviour? Would it fail and suggest to use `pipx upgrade --force`, fail and suggest `pipx unpin && pipx upgrade`, or some other approach?

**Comment by dukecat0** [comment]
> fail and suggest pipx unpin && pipx upgrade

IIRC I used this approach in my previous implementation.

**Comment by gaborbernat** [comment]
PR weclome.
