### ISSUE TITLE
Cannot pass --include-deps if --use_binaries is not passed as well

### ISSUE THREAD

**Issue by ssbarnea** [pypa/pipx#805]
**Describe the bug**
When trying to inject additional dependencies with their executables into existing pipx env, a confusing error like below will appear:

**How to reproduce**

```
$ pipx inject --include-deps ansible-core ansible-lint yamllint
Cannot pass --include-deps if --use_binaries is not passed as well

$ pipx --version
0.12.3.1
# ^ that is the default version that comes with Ubuntu, bit outdated.
```

Other than the fact that the error message contains an unexpected underline and that  --help does not display any --use-binaries option, that is a real problem. An attempt to upgrade pipx would fail to upgrade it if it was installed initially as a system package.

I am aware that this is likely more of a Ubuntu, specific bug than pipx but I am raising it here because pipx has an direct interest of having a functional version of pipx in ubuntu, especially as installing as system package is what Ubuntu suggest when someone is trying to run pipx. 

**Expected behavior**
```
Being suggested options that can be used.
```

**Comment by gaborbernat** [comment]
PR welcome 👍

**Comment by meowmeowmeowcat** [comment]
In 1.0.0(the newest version), the error message for `pipx inject --include-deps ansible-core ansible-lint yamllint` would be:
```
Cannot pass --include-deps if --include-apps is not passed as well
```

**Comment by chrysle** [comment]
Can you explain why these options must be passed together?
