### ISSUE TITLE
Add support to export/freeze the installed tools

### ISSUE THREAD

**Issue by frostming** [pypa/pipx#807]
**How would this feature be useful?**

I am not sure if this is already requested. It would be helpful if we can export the installed tools into a metadata file so we can later reproduce the environment on a new machine.

**Describe the solution you'd like**

Since all venvs already contain a `pipx_metadata.json` file, it won't be hard to collect them and combine them into a single JSON file.

Also need to add a command or option to `install` command to read that file and install all the tools defined in it.

**Describe alternatives you've considered**

The exported file could be in other human-readable formats such as yaml, toml, etc. In that case, a new parser and writer will need to be implemented.

**Comment by meowmeowmeowcat** [comment]
> Since all venvs already contain a pipx_metadata.json file, it won't be hard to collect them and combine them into a single JSON file.

`pipx list --json` should help.

> Also need to add a command or option to install command to read that file and install all the tools defined in it.

Probably a duplication of #687.

**Comment by frostming** [comment]
Great, I should read the manual, thanks

**Comment by cs01** [comment]
Thanks @meowmeowmeowcat for all your help with pipx
