### ISSUE TITLE
Installing with brew installs python 3.10 when 3.9 is available

### ISSUE THREAD

**Issue by BeyondEvil** [pypa/pipx#808]
Not sure if this is by design or not.

But installing `pipx` with `brew install pipx` will also install python 3.10 even tho 3.9 is already available.

**Comment by meowmeowmeowcat** [comment]
> install python 3.10 even tho 3.9 is already available.

Python 3.10 is the dependency of pipx on Homebrew. 
https://github.com/Homebrew/homebrew-core/blob/7a41c8766c27b91e6e0c6bc2f69f6b3ffae87f85/Formula/pipx.rb#L20

**Comment by BeyondEvil** [comment]
Yeah, I figured.

I went the route of installing it using python instead (the linux way).
