### ISSUE TITLE
flag for app considered ambiguous option to pipx run

### ISSUE THREAD

**Issue by C-nit** [pypa/pipx#823]
**Describe the bug**
some flag arguments are not possible to provide to the app as they seem to be checked for use with `run` instead of the APP

**How to reproduce**
```console
$ pipx --verbose run --spec kfp-tekton dsl-compile-tekton --py pipeline.py --output pipeline.yaml
usage: pipx run [-h] [--no-cache] [--pypackages] [--spec SPEC] [--verbose] [--python PYTHON] [--system-site-packages] [--index-url INDEX_URL]
                [--editable] [--pip-args PIP_ARGS]
                app ...
pipx run: error: ambiguous option: --py could match --pypackages, --python
```

**Expected behavior**
any and every flag to be passed to APP directly

**Comment by uranusjr** [comment]
You need to add `--` to prevent the options from being interpreted as one to `pipx run`. This is how argument parsing works.

```
pipx --verbose run --spec kfp-tekton -- dsl-compile-tekton --py pipeline.py --output pipeline.yaml
```

**Comment by cs01** [comment]
Let’s take this as an opportunity to improve the docs. PRs welcome.
