### ISSUE TITLE
When combining pipx with awscli, awscli cannot find itself 

### ISSUE THREAD

**Issue by RoelantStegmann** [pypa/pipx#826]
- Installed the latest _Anaconda 4.11.0_ which gave me _Python 3.9.7_
- pip install pipx gave me `pipx --version` _1.0.0_
- pipx install awscli gave me  _package awscli 1.22.71, installed using Python 3.9.7_

**Describe the bug**
If I run `aws` I get

```
File association not found for extension .py
Traceback (most recent call last):
  File "c:\Users\RoelantStegmann\.local\bin\aws.cmd", line 50, in <module>
    import awscli.clidriver
ModuleNotFoundError: No module named 'awscli'
```

It seems that it cannot access the package itself, but only the entrypoint. 

**Expected behavior**

I expect just to have my `aws` package working. Other packages work as expected. 

** Tried solutions **
I tried the suggestion [here](https://stackoverflow.com/a/66386629/7441757) but that did not work for me.

**Comment by uranusjr** [comment]
This is a bug in awscli and you’ll need to ask them to fix the issue, unfortunately.
