### ISSUE TITLE
EXE file in .local/bin does not run, but package works

### ISSUE THREAD

**Issue by fladd** [pypa/pipx#831]
**Describe the bug**

When I run
```
pipx install zipped-album-player
zap
```

nothing happens. The programme does not run.

Activating .local/pipx/venv/zipped-album-player and then running `python -m zap`, however, works just fine.

Running the programme via pipx on Mac and Linux also works fine.

So there is an issue with the .exe file generated by Pipx.

Is there a way to debug this? I.e. can I somehow make the .exe file print error messages, so I can see what is going on?

**How to reproduce**

```
pipx install zipped-album-player
zap
```

**Expected behavior**

The programme should run.

**Comment by uranusjr** [comment]
Likely #825
