### ISSUE TITLE
--pip-args does not work with args that start with "--"

### ISSUE THREAD

**Issue by gwerbin** [pypa/pipx#833]
**Describe the bug**

Passing a flag to `--pip-args` that starts with `--` does not work properly. If you write `--pip-args --foo`, Pipx separates this into two separate options, `--pip-args` and `--foo`, then exits with an error code because `--pip-args` now is missing its argument.

**How to reproduce**

```bash
pipx install --pip-args --pre hy
```

**Expected behavior**

Pipx should pass the `--pre` option to Pip when installing Hy.

**Comment by uranusjr** [comment]
`pipx install --pip-args=--pre=py`.

https://github.com/python/cpython/issues/53580
