### ISSUE TITLE
pipx installs using python 3.10 fail on M1 laptop.

### ISSUE THREAD

**Issue by damienrj** [pypa/pipx#834]
**Describe the bug**
When installing pipx via homebrew the installed packages fail when using the python 3.10.2 (I assume it is being pulled in by homebrew since I don't have it installed). 

```
  File "/Users/damien/.local/pipx/venvs/notebooks/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/damien/.local/pipx/venvs/notebooks/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/damien/.local/pipx/venvs/notebooks/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/Users/damien/.local/pipx/venvs/notebooks/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

If I switch to python 3.9 it works ` pipx install ... --python /opt/homebrew/opt/python@3.9/bin/python3` 

Could we remove this? 
https://github.com/Homebrew/homebrew-core/blob/d1e40dde9dc0b86025b16e024bbb4e180efa6d4b/Formula/pipx.rb#L20

**Comment by meowmeowmeowcat** [comment]
What package are you trying to install? Seems that this is not an issue from pipx.

**Comment by damienrj** [comment]
It is a private package but gprc is what is not compatible with the python
3.10 which is being required by brew. Having ***@***.*** would also be fine.
