### ISSUE TITLE
reinstall-all does not recover from python version upgrade

### ISSUE THREAD

**Issue by fishy** [pypa/pipx#835]
**Describe the bug**
After the system's python version upgraded (for example, 3.9 -> 3.10), `pipx upgrade-all` fails with `pip` module issue (this is kinda expected):

```
$ pipx upgrade-all
/home/fishy/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3/dist-packages/pipx/util.py", line 202, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/fishy/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip setuptools wheel' failed
/home/fishy/.local/pipx/venvs/poetry/bin/python: No module named pip
Error encountered when upgrading poetry:
'/home/fishy/.local/pipx/venvs/poetry/bin/python -m pip install --upgrade poetry -q' failed

Versions did not change after running 'pipx upgrade' for each package 😴

Some packages encountered errors during upgrade.
    See specific error messages above.
```

But when I try to recover it from `pipx reinstall-all` (which is usually useful to recover from other minor upgrades), it does not recover, and also uninstall my already installed packages:

```
$ pipx reinstall-all
/home/fishy/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3/dist-packages/pipx/util.py", line 202, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/fishy/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip setuptools wheel' failed
uninstalled poetry! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/fishy/.local/pipx/logs/cmd_2022-04-23_10.34.06_pip_errors.log

Error installing poetry.
The following package(s) failed to reinstall: poetry
$ ls -l .local/pipx/venvs/
total 0
```

I have to remove `~/.local/pipx/shared` and manually reinstall packages to recover.

**How to reproduce**

**Expected behavior**

1. `pipx reinstall-all` really should not remove the packages even if it cannot recover them
2. if there's no easy way to recover automatically, maybe print out a message saying something like "manually remove your ~/.local/pipx/shared might help"?

**Comment by meowmeowmeowcat** [comment]
>  But when I try to recover it from pipx reinstall-all (which is usually useful to recover from other minor upgrades), it does not recover, and also uninstall my already installed packages:

The reason is that pipx uninstall packages by deleting their directories. Then, pipx tries to install them again but it gets `No module named pip` error.

Maybe it can try to run `pip` before it uninstalls packages? Therefore, it will not delete packages even if it can't reinstall them.
