### ISSUE TITLE
On Debian 9 python3 -m pipx ensurepath " Python 3.6 or later is required "

### ISSUE THREAD

**Issue by Merlincool** [pypa/pipx#836]
Using Debian 9 gets error > Python 3.6 or later is required.

I have already installed python 3.10 on my debian 9.
first step is successful `python3 -m pip install --user pipx`
but this one throws error `python3 -m pipx ensurepath`

my python 3.10

`python3.10 -V`

`Python 3.10.4`

**Comment by uranusjr** [comment]
Your `python3` and `python3.10` point to different Python installations. Use `python3.10 -m pip install --user pipx` to install, and run with `pipx` or `python3.10 -m pipx` instead.

**Comment by Merlincool** [comment]
> Your `python3` and `python3.10` point to different Python installations. Use `python3.10 -m pip install --user pipx` to install, and run with `pipx` or `python3.10 -m pipx` instead.

I tried that as well but didn't work. I had to finally give path to my ~/local/bin which wasn't in path. It got solved.
