### ISSUE TITLE
installing  package from git repo

### ISSUE THREAD

**Issue by ithinkido** [pypa/pipx#838]
**Describe the bug**
installing from source control  fails as  tested on demo example from [README](https://github.com/pypa/pipx#installing-from-source-control)

**How to reproduce**
```pipx install git+https://github.com/psf/black.git```   

fails with the following  

Package cannot be a url

**Expected behavior**
I would like to be able to install a package from a git repo as descried in the README

**Comment by uranusjr** [comment]
You’re on an old version.
