### ISSUE TITLE
Relocatable installation

### ISSUE THREAD

**Issue by ws1088** [pypa/pipx#839]
Is it possible to install a package using pipx in directory /a/b/c/d1/app1 and move it (and its virtual env) to another location and the package will still work? In my environment we have a mirror cron job to copy tools/files from /a/b/c/d1 to /a/b/c/d2 (which we cannot write to).

**Comment by gaborbernat** [comment]
It is not.

**Comment by cs01** [comment]
It should be close to being relocatable. The symlink to the binary will break, but other than that virtual environments can be moved.

**Comment by gaborbernat** [comment]
> The symlink to the binary will break, but other than that virtual environments can be moved.

This may be true today and now, but is totally unsupported and can break at any point. Both venv and virtualenv officially are not relocatable, as far as guarantees go.
