### ISSUE TITLE
No module named pip

### ISSUE THREAD

**Issue by jJit0** [pypa/pipx#840]
Python3 version upgrade, broke pipx. It has been upgraded from 3.9.12 to 3.10.4

Since, when I want to `pipx reinstall pycowsay` I get this error `/usr/local/lib/venvs/pycowsay/bin/python: No module named pip`

Any suggestions ?

**Comment by meowmeowmeowcat** [comment]
Try this solution: https://github.com/pypa/pipx/issues/791#issuecomment-1005645899

**Comment by jJit0** [comment]
Yeah that's what I did exactly after opening this issue.
I rememberd the Shared and Venv folders needed to be removed first.
