### ISSUE TITLE
ensurepath adds the wrong path in Windows

### ISSUE THREAD

**Issue by ccornici** [pypa/pipx#842]
**Describe the bug**

After running `python -m pip install --user pipx` it warns me as per README about the path not being added.
Then I run the `pipx ensurepath` from **/Roaming/**
It tells me it succeded.
But when I go to see the path var, it added **/Local/** instead of Roaming, so nothing works. Had to add it manually myself...

**How to reproduce**

**Expected behavior**

**Comment by meowmeowmeowcat** [comment]
pipx adds `/Local/` to PATH by default. However, you can change this behaviour by setting environment variable `PIPX_BIN_DIR`.
