### ISSUE TITLE
pipx install package>=1.2.3 fails to perform upgrade

### ISSUE THREAD

**Issue by ssbarnea** [pypa/pipx#847]
**Describe the bug**
I was surprised to discover that `pipx install package>=1.2.3` would do nothing is a previous version is already installed, even if that is older than the version mentioned.

**How to reproduce**

**Expected behavior**

Match pip behavior. If not possible, it should at least fail when given ranges if it does not support them.

**Comment by uranusjr** [comment]
I think the general direction is to use `upgrade` for this. Merging this into #356.

**Comment by bristea** [comment]
That is a bummer as it would make pipx and installer that cannot be used in an idempotent way.
