### ISSUE TITLE
Show warning when a URL with #egg is provided to pipx

### ISSUE THREAD

**Issue by hrittich** [pypa/pipx#875]
**Describe the bug**

Exposing the shell commands of extra dependencies does not work when installing via git+ssh. It works when installing from a local directory.

**How to reproduce**

Create a git repository `git+ssh://git@gitlab.com/.../my-package.git` with a package whose extra dependency exposes a shell command. Then, run

    pipx install  --include-deps "git+ssh://git@gitlab.com/.../my-package.git#egg=my-package[extra-dependency]"

The shell command of the `extra-dependency` is not exposed, even though the extra dependency is installed in the venv.

**Expected behavior**

The shell command should be exposed.

**Comment by uranusjr** [comment]
Could you provide a working reproducer that we can test against?

**Comment by hrittich** [comment]
Sure. Here you go:

If you run either

    pipx install --include-deps "git+https://github.com/hrittich/package-with-extras.git#egg=package-with-extras[httpie]"

or

    pipx install --include-deps "git+ssh://git@github.com/hrittich/package-with-extras.git#egg=package-with-extras[httpie]"

pipx stops with the error message "No apps associated with package package-with-extras or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead."

If you, instead, run

    git clone https://github.com/hrittich/package-with-extras.git
    pipx install --include-deps "./package-with-extras[httpie]"

the command succeeds and the dependencies (e.g., httpie) are exposed to the command line.

**Comment by uranusjr** [comment]
So `package-with-extras[httpie] @ git+https://github.com/hrittich/package-with-extras.git` works correctly, while the `#egg=` part is actually completely discarded by pipx. Since the `#egg=` format is a legacy format that was never standardised, and the `name @ url` format was a standard much before pipx was implemented, I am inclined to say the latter form should not be used with pipx.

We could potentially emit a warning if the `#egg=` fragment is detected and tell the user this has no effect at all, but it’s a nice-to-have feature and not critical.

A pull request on that addition would be much welcomed.

**Comment by hrittich** [comment]
@uranusjr Thanks for the explanation. That helped a lot. I was not aware that the I was using an old form for the package spec.

**Comment by meowmeowmeowcat** [comment]
These lines might also need to be updated:
https://github.com/pypa/pipx/blob/71fe102014393061fcb953609a5b5b2a763f4c0a/README.md?plain=1#L167-L171

**Comment by chrysle** [comment]
It seems like a deprecation warning is already thrown by pip, which would make the error message unnecessary: 

```
$ python src/pipx install --include-deps "git+https://github.com/hrittich/package-with-extras.git#egg=package-with-extras[httpie]"
DEPRECATION: git+https://github.com/hrittich/package-with-extras.git#egg=package-with-extras[httpie] contains an egg fragment with a non-PEP 508 name pip 25.0 will enforce this behaviour change. A possible replacement is to use the req @ url syntax, and remove the egg fragment. Discussion can be found at https://github.com/pypa/pip/issues/11617
....
```

**Comment by chrysle** [comment]
@uranusjr  Do you think this can be closed?

**Comment by uranusjr** [comment]
pip’s warning is a bit different; it does not ignore `#egg` entirely, only if the part contains `[]`. But yeah I think pip’s warning is sufficient for the original issue; we can discuss whether pipx needs a separate warning for non-extra names as well (which #906 implements).
