### ISSUE TITLE
pipx installs optional dependencies automatically

### ISSUE THREAD

**Issue by tddschn** [pypa/pipx#880]
**Describe the bug**

`pipx install <myapp>` installs optional dependencies for <myapp>, which is not the desirable behavior sometimes.

I read `pipx install --help`, but didn't find an option to disable this behavior.

**How to reproduce**

The app I was trying to install was [git-pp](https://github.com/tddschn/git-pp). 

git-pp has an optional dependency `uvloop` ([pyproject.toml](https://github.com/tddschn/git-pp/blob/master/pyproject.toml)), which is not available for Windows and running `pipx install git-pp` will break on windows.

```
# run this on Windows
$ pipx install git-pp
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\me\.local\pipx\logs\cmd_2022-07-30_13.44.33_pip_errors.log

pip seemed to fail to build package:
    uvloop[uvloop]<0.17.0,>=0.16.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    RuntimeError: uvloop does not support Windows at the moment
    error: metadata-generation-failed

Error installing git-pp.
```

**Expected behavior**

Do not install optional dependencies by default, or at least allow users to control this behavior via an option.

**Comment by meowmeowmeowcat** [comment]
https://stackoverflow.com/a/70227012

**Comment by meowmeowmeowcat** [comment]
> Do not install optional dependencies by default, or at least allow users to control this behavior via an option.

pipx doesn't install optional dependencies by default, so I suspect this is related to your `pyproject.toml`.

You can refer to the docs: https://python-poetry.org/docs/pyproject/#extras

**Comment by tddschn** [comment]
@meowmeowmeowcat Thank you! You're right, I was using `extra` dependencies, not `optional` depedencies.
