### ISSUE TITLE
VIRTUAL_ENV Environment Variable Missing

### ISSUE THREAD

**Issue by TheTechromancer** [pypa/pipx#887]
Hello,

I have an app that uses `ansible`'s `pip` module to install certain python packages within the virtual environment, *after* its initial creation (when the app is run). 

Note that this works okay in a typical virtual environment (e.g. in a `poetry shell`), where I'd normally grab the `VIRTUAL_ENV` environment variable and pass it through to ansible's `pip` module via the `virtualenv` argument:

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
![image](https://user-images.githubusercontent.com/20261699/185445481-3cf69159-6a21-4337-94fc-3336f7e0be4d.png)
 
But I can't get it to work in `pipx`'s virtual environment, for two reasons:
1. The `VIRTUAL_ENV` environment variable appears to be missing
2. Scripts from installed Python dependencies are not in the path (i.e. I cannot execute `ansible` even though it is installed in the environment).

So I guess the expected behavior is that the `VIRTUAL_ENV` environment variable would be set, and any secondary Python packages would be accessible from within the environment, via `$PATH`.

I know this is sort of a strange scenario, but I'm not sure exactly how to go about troubleshooting it. Any guidance would be greatly appreciated.

Thanks!

**Comment by uranusjr** [comment]
The `VIRTUAL_ENV` environment variable is not a standard or public interface, and you should not use it to detect whether you are “inside” a virtual environment. For public properties you can rely on to detect a virtual environment, please refer to [PEP 405](https://peps.python.org/pep-0405/#splitting-the-meanings-of-sys-prefix) (tl; dr: compare `sys.prefix` and `sys.base_prefix`).

**Comment by TheTechromancer** [comment]
Thanks very much @uranusjr for the quick reply. Comparing `sys.prefix` and `sys.base_prefix` looks like it will do the trick.

However I need the `pip` executable to be present in the environment. The `pip` package is installed but it is not listed in `<venv>/bin`. Do you know of the best way to fix that inside the pipx environment?

**Comment by uranusjr** [comment]
Use `[sys.executable, "-m", "pip"]` instead
