### ISSUE TITLE
How to upgrade a project to the latest github source?

### ISSUE THREAD

**Issue by halloleo** [pypa/pipx#892]
I have installed a package (`beets`) from pypi with the normal install command line:

    pipx install beets

Now I want to upgrade this package to it to the latest sources from GitHub. - How do I do this?

I know I can install a new package from a repo url:

    pipx install --spec git+https://github.com/beetbox/beets.git beets

but how can I just _upgrade_ an existing one from a GitHub repo?

**Comment by meowmeowmeowcat** [comment]
Does `pipx install --force git+https://github.com/beetbox/beets.git` work for you?

**Comment by halloleo** [comment]
To my surprise, it _did_ work. (I would have thought pipx' `install` command can't handle it when there is already a package with thw same name installed, but it  probably just _overwrote_ the existing one...)

Thanks!
