### ISSUE TITLE
Run arbitrary bash commands like `pipx run --spec pandas --cmd 'python clean-my-data.py'`

### ISSUE THREAD

**Issue by phitoduck** [pypa/pipx#894]
Hi there,

Is it already possible to run arbitrary bash commands with a temporary virtual environment managed by `pipx`? 

**How would this feature be useful?**

I have a use case where engineers/data scientists I work with have a standard set of scripts in every repository. These tend to be utility scripts like:

`bump-version.py`, `update-project-from-latest-template.py`, `ensure-ssh-keys-are-present.py`, `rename-git-branch.py`, etc.

These scripts may require additional dependencies. It's be amazing if in our standard `Makefile`, we could have targets like:

```make
bump-version:
    pipx run --spec commitizen --cmd 'python bump-version.py'

update-project-from-latest-template:
    pipx run --spec cookiecutter --cmd 'update-project-from-latest-template.py'

...
```

**Describe the solution you'd like**

I'd be happy with any syntax. But maybe something like a `--cmd` argument. Or, given that all my examples are `.py` files, maybe `--script-path <some .py file>`.

**Describe alternatives you've considered**

I'll probably do something like this if `pipx` doesn't / won't support this:

```make
update-project-from-latest-template:
    python -m venv ./update-project-venv/
    source ./update-project-venv/bin/activate && python -m pip install cookie-cutter && python update-project-from-latest-template.py
    rm -rf ./update-project-venv/
```

I suppose that's a workaround for just about any feature lacking in `pipx`.

**Comment by uranusjr** [comment]
I’m not fond of this personally. pipx is an application/command manager, and it uses a virtual environment for the job is more of an implementation detail. This kind of makes the virtual environment front-and-center, which is IMO out of scope.

**Comment by phitoduck** [comment]
Fair enough. We can mark this as closed.

**Comment by Morikko** [comment]
A non-exhaustive list of tools doing this:

1. [Pew](https://github.com/pew-org/pew/)
2. [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/index.html)
3. [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv)
