### ISSUE TITLE
[feature request] plugin for asdf-vm

### ISSUE THREAD

**Issue by cocoonkid** [pypa/pipx#901]
**How would this feature be useful?**

I manage all language versions with asdf-vm and when switching python versions or installing the most recent and deleting the older one I always have to move pipx as well and reinstall all the programs I use with it.

If a plugin for pipx would exist (similar to poetry) would alleviate the pain of moving versions.

**Describe the solution you'd like**
Just a plugin for https://asdf-vm.com/

https://asdf-vm.com/plugins/create.html

**Describe alternatives you've considered**

Only manually migration is an alternative.

Thanks for consideration

**Comment by meowmeowmeowcat** [comment]
Could you try https://github.com/amrox/asdf-pyapp?

This works for me:
```
asdf plugin add pipx https://github.com/amrox/asdf-pyapp.git
asdf install pipx latest
```

**Comment by cocoonkid** [comment]
@meowmeowmeowcat This solved it. Thanks a bunch! really neat!
