### ISSUE TITLE
pipx installs executables outside viritualized python environments

### ISSUE THREAD

**Issue by biggestsonicfan** [pypa/pipx#904]
**Describe the bug**
Installing pipx via pip within a `python3 -m venv`, and then installing a package when in that venv results in pipx placing the package in the user's pipx directory and not in the venv's. (Possibly only after `python3 -m pip install --user pipx`)

**How to reproduce**
```
python3 -m venv ./gallery-dl
source gallery-dl/bin/activate
python3 -m pip install --upgrade pip setuptools wheel
python3 -m pip install pipx
pipx install git+https://github.com/mikf/gallery-dl.git
deactivate
whereis gallery-dl
```

**Expected behavior**
pipx installs and contains the package to the venv(?)

**Comment by meowmeowmeowcat** [comment]
pipx installs packages to `~/.local/pipx/venvs` by default. If you want to make it install to specific directory, you can set the environment variable `PIPX_HOME` to override the current behaviour.

**Comment by cglmrfreeman** [comment]
Alright, but in contrast:
python3 -m venv ./hello-world

**Comment by biggestsonicfan** [comment]
I'm unsure why you didn't mention that in the first place.
