### ISSUE TITLE
[request] Add choco package to install pipx

### ISSUE THREAD

**Issue by mshafer1** [pypa/pipx#912]
**How would this feature be useful?**

Similar to #338, adding a ['choco'](https://community.chocolatey.org/packages) package would make it much easier to install pipx on Windows

**Describe the solution you'd like**
Easy system installations of pipx:
```
# install python someway, choco, download, or even pyenv-win
# ...
choco install pipx
```

**Describe alternatives you've considered**
- Using the pip [`pipxinpipx`](https://pypi.org/project/pipxinpipx/) package; however, that method has had stability issues with creating the venv and setting up the pipx installation.
- `choco install pipx --source python`, this option fails on finding pip despite that already being installed on the system.

**Comment by mshafer1** [comment]
I have prototyped a choco package that finds the Python installation (via get-command - roughly equivalent to `which`/`where`) creates a venv and installs pipx into - letting choco handle creating the shim.

Would the maintainers be open to having this contributed to the repo?

**Comment by meowmeowmeowcat** [comment]
Maybe the choco package can be put in a separate repo?

**Comment by mshafer1** [comment]
> Maybe the choco package can be put in a separate repo?

It definitely could, but it may be best for pypa to own the repo either way so there's no confusion over the reuse of the name.

**Comment by uranusjr** [comment]
IMO it is more productive to put this in a separate repository. pipx maintainers don’t use Chocolatey, and I don’t think it’d be particularly responsible if we add something the maitainers don’t use or test.

**Comment by sigma67** [comment]
any update on the separate repo?

**Comment by uranusjr** [comment]
Up for you to create it.

**Comment by sigma67** [comment]
I was thinking of @mshafer1 , as (s)he seems to have a prototyped working script already.

**Comment by mshafer1** [comment]
I've been working through the process to publish it with my company if there's additional interest I could try to get it pushed through this week (fell to the back burner for a bit)

**Comment by mshafer1** [comment]
A tad late for "this week", but initial PR to setup repo is here: https://github.com/ni/pip-executable-choco/pull/1
(CC @sigma67 )

**Comment by jaraco** [comment]
I'm still interested in seeing support for pipx. The pipx guide suggests to use scoop, so I've used scoop instead of chocolatey.

**Comment by le-dawg** [comment]
me2

**Comment by McPhale** [comment]
I would also like to see this.

**Comment by darkn3rd** [comment]
I didn't see a pipx, so I submitted `pipx` package today. I am awaiting for it to be approved and added. 😉 
https://community.chocolatey.org/packages/pipx/1.16.7
