### ISSUE TITLE
Some advice about license compliance

### ISSUE THREAD

**Issue by Ashley123456789** [pypa/pipx#915]
**How would this feature be useful?**

There’s some possible legal issues on the license of your repository when you combine numerous third-party packages.
For instance, _jinja2, textwrap, datetime_ you imported are licensed with _BSD-3-Clause, Python Software Foundation License, Zope Public License (ZPL 2.1),_ respectively. 
However, the _MIT License_ of _your repository_ are less strict than above package licenses on some terms, which has violated the whole license compatibility in your repository and may bring legal and financial risks.

**Describe the solution you'd like**

You can select another proper license for your repository, or write a custom license with license exception if some license terms couldn’t be summed up consistently.

**Describe alternatives you've considered**

**Comment by uranusjr** [comment]
I don’t think that’s how licensing works. pipx does not _redistribute_ third-party packages you mentioned, and thus are not bound by most of the clauses. Very few projects use licenses that impose restrictions to _depending_ on a package (most notably GPL), but pipx does not depend on those, as far as I am aware.

**Comment by Ashley123456789** [comment]
Thanks for your response.
License compatibility does not refer to exact OSS usage behavior, but just to license texts themselves. It can also bring possible legal risks although not straightforward license violation cases.
Besides, although GPL-related license issues are the most famous, issues on any other licenses are also of concern increasingly. 
Looking forward to your reply.
