### ISSUE TITLE
How to uninstall injected package ? 

### ISSUE THREAD

**Issue by Issam-seghir** [pypa/pipx#927]
In the document : 
` inject              Install packages into an existing Virtual Environment`

But how to uninstall this injected package, for example, I install the darglint plugin in flake8 with:
```shellI
pipx inject flake8 darglint 
pipx list --include-injected

   package flake8 6.0.0, installed using Python 3.11.1
    - flake8.exe
    Injected Packages:
      - darglint 1.8.1
```

i try to uninstall darglint with :

```
pipx uninstall  darglint
Nothing to uninstall for darglint 😴

pipx uninstall flake8 inject darglint
pipx: error: unrecognized arguments: inject darglint
```

**Comment by meowmeowmeowcat** [comment]
`pipx uninject` was added in #820 and it should help in this case, but it's unreleased.

**Comment by meowmeowmeowcat** [comment]
https://github.com/pypa/pipx/releases/tag/1.2.0
