### ISSUE TITLE
Globbing for PIPX_BIN_DIR

### ISSUE THREAD

**Issue by beorn** [pypa/pipx#94]
I set `$PIPX_BIN_DIR` to `~/bin` and it created a directory called `~` in my home directory.

```console
% pipx list                 
venvs are in /Users/bjorn/.local/pipx/venvs
binaries are exposed on your $PATH at /Users/bjorn/~/bin
   package pipsi 0.9, Python 3.7.2
    - pipsi
```

**Comment by rkennedy** [comment]
What's your shell, and how did you set `PIPX_BIN_DIR`?

If you use bash or zsh, either of the following _should_ have caused the shell to expand the tilde expression, so pipx would have seen the full path and wouldn't need to do any special tilde expansion of its own:

```bash
PIPX_BIN_DIR=~/bin
export PIPX_BIN_DIR

export PIPX_BIN_DIR=~/bin
```

Did you perhaps _quote_ the assignment, as in `PIPX_BIN_DIR="~/bin"`? Shells don't do tilde expansion in quotes, so you should remove the quotes in that case.

**Comment by beorn** [comment]
I'm using zsh, and I originally had `export PIPX_BIN_DIR="~/bin"` as you expected, but changed it to `export PIPX_BIN_DIR="$HOME/bin"` as tilde wasn't expanded.  I could do it the way you recommend as well.

I have this exact syntax (`"~/.."`) for other env vars (e.g., ssh) so I guess I was just expecting it to work.  Not a big deal, but perhaps consider [os.path.expanduser](https://docs.python.org/3/library/os.path.html#os.path.expanduser)?
