### ISSUE TITLE
Exit code 0 if installing non-existing package on Windows

### ISSUE THREAD

**Issue by Warchant** [pypa/pipx#942]
**Problem description**
```ps
> pipx install xxxzzzccc       
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\warch\.local\pipx\logs\cmd_2023-02-28_12.37.24_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement xxxzzzccc (from versions: none)
    ERROR: No matching distribution found for xxxzzzccc

Error installing xxxzzzccc.

> echo $LASTEXITCODE
0

> pipx --version
1.1.0
```

You clearly see installation error, but this `pipx install` command returns exit code 0, which confuses CI systems. All failures should return non-0 exit code.

OS: Windows 11

**Expected behavior**
I expected to see non-0 exit code when `pipx install` failed.

**Comment by chrysle** [comment]
Can't reproduce this on an Ubuntu OS:

```
~$ pipx install xxxzzz
Fatal error from pip prevented installation. Full pip output in file:
    /home/user/.local/pipx/logs/cmd_2023-03-01_13.51.20_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement xxxzzz (from versions: none)
    ERROR: No matching distribution found for xxxzzz

Error installing xxxzzz.
~$ echo "$?"
1
```
Have you tried `$?` already?

**Comment by Warchant** [comment]
> Can't reproduce this on an Ubuntu OS:
> 
> ```
> ~$ pipx install xxxzzz
> Fatal error from pip prevented installation. Full pip output in file:
>     /home/user/.local/pipx/logs/cmd_2023-03-01_13.51.20_pip_errors.log
> 
> Some possibly relevant errors from pip install:
>     ERROR: Could not find a version that satisfies the requirement xxxzzz (from versions: none)
>     ERROR: No matching distribution found for xxxzzz
> 
> Error installing xxxzzz.
> ~$ echo "$?"
> 1
> ```
> 
> Have you tried `$?` already?

I just checked, on Linux exit code is 1. 

On Windows exit code is 0.

**Comment by chrysle** [comment]
Does `pip install xxxzzzccc` return a non-zero exit status?

**Comment by Warchant** [comment]
> Does `pip install xxxzzzccc` return a non-zero exit status?

No, it returns code 1.

**Comment by chrysle** [comment]
Then this must indeed be an issue with `pipx`. 

Sorry that I can't help you with investigating the problem further; I don't use windows. 

@meowmeowmeowcat Could you add the _windows bug_ labels please?

**Comment by meowmeowmeowcat** [comment]
I don't think this is an issue with pipx. The exit code is 1 on my Windows 11 VM and GitHub CI.
