### ISSUE TITLE
`pipx run wheel` / `install wheel` doesn't work

### ISSUE THREAD

**Issue by henryiii** [pypa/pipx#951]
**Describe the bug**

`pipx run wheel` doesn't seem to be supported. I think it's because `wheel` is filtered out as part of the default environment.

~~A possible fix would be to add the entrypoint for pipx to wheel;~~ otherwise I think special handling would have to be included to see if 'wheel' is specifically asked for.

**How to reproduce**
`pipx run wheel` reports no executables found.

```console
$ docker run --rm -it python bash
# pip uninstall wheel
# pip install pipx
# pipx run wheel
'wheel' executable script not found in package 'wheel'.
Available executable scripts:

```

**Expected behavior**
It should get wheel.

I opened an example of the entrypoint in wheel, but I realized that `pipx install wheel` should work too, and it doesn't:

```console
# pipx install wheel

No apps associated with package wheel or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool
instead.
```

So the fix needs to be here. Note that wheel isn't meant to be used as a library (at least yet), only as a CLI app (or a setuptools helper, of course). And the next version will be gaining a very useful CLI command (`tags`).

It also seems it's filtered from git?

```console
$ pipx run --spec git+https://github.com/henryiii/wheel.git@henryiii/fix/pipxrun wheel tag --help

Cannot determine package name from spec 'git+https://github.com/henryiii/wheel.git@henryiii/fix/pipxrun'. Check package spec for errors.
```

That might be related to the fact the version number is the same, and it doesn't reinstall the package, though.

**Comment by chrysle** [comment]
I'll try to investigate & fix the problem.

**Comment by chrysle** [comment]
@henryiii This really seems to be a problem with `install` (or `venv.install_package()`). After a normal installation with `python -m pip install wheel` the `bin` folder contains the following files (the executable, too): 

```
activate  activate.csh	activate.fish  Activate.ps1  easy_install  easy_install-3.8  pip  pip3	pip3.8	python	python3  wheel
```

After install with `pipx` (which runs exactly the same command), the following: 

```
activate  activate.csh	activate.fish  Activate.ps1  python python3
```
Do you have any idea where something could be "filtered out"?

**Comment by chrysle** [comment]
@uranusjr Could you offer some advice to help solve this problem? The file `pipx_shared.pth` at 
`~/.local/pipx/venvs/<venv>/lib/python<version>/site-packages/` seems to redirect the installation of `pip, setuptools` and `wheel` to `~/.local/pipx/shared/lib/python3.9/site-packages/`. It is created here: 

https://github.com/pypa/pipx/blob/444f985a87a8acf519116189f5731a58f3f02498/src/pipx/venv.py#L165-L176

Do you think overriding this behavior in case of `pipx run` would be a good idea or do you have any other recommendation?

**Comment by henryiii** [comment]
`pipx install wheel` should work too. I’d think a behavior change should trigger on requesting wheel (or pip, setuptools doens’t have a cli iirc).

**Comment by chrysle** [comment]
> [...] on requesting wheel (or pip, setuptools doens’t have a cli iirc).

The installation of pip to the venv is suppressed by default:

https://github.com/pypa/pipx/blob/444f985a87a8acf519116189f5731a58f3f02498/src/pipx/venv.py#L161

**Comment by graingert** [comment]
this also fails for pip eg `pipx run pip download pip`
