### ISSUE TITLE
Allow installing multiple applications with `install` command

### ISSUE THREAD

**Issue by soredake** [pypa/pipx#971]
**How would this feature be useful?**
Instead of:
```
$pip = @("internetarchive", "git+https://github.com/arecarn/dploy.git", "tubeup")
foreach ($p in $pip) {pipx install $p}
```
I will be able to do just `pipx install internetarchive git+https://github.com/arecarn/dploy.git tubeup`

**Describe the solution you'd like**
Allow installing multiple apps with `pipx install`

**Describe alternatives you've considered**
Using foreach or something like this.

**Comment by chrysle** [comment]
That's a good suggestion! I'll try doing something about this.
