### ISSUE TITLE
Pipx cannot install kivy

### ISSUE THREAD

**Issue by markqvist** [pypa/pipx#975]
**Describe the bug**
When installing any application that depends on the ``kivy`` package, or the ``kivy`` package itself, installation fails because of a compilation error:

```
/tmp/pip-install-zd4uxn2o/kivy_3164aa11e0ce45708ca199fc1029611e/kivy/include/gl_redirect.h:72:33: fatal error: GL/gl.h: No such file or directory
    b'/bin/sh: 1: pkg-config: not found\n'
```

**How to reproduce**
```
# Simply try installing Kivy:
pipx install kivy

# Or install an application that lists Kivy as a dependency:
pipx install sbapp
```

**Expected behavior**
The application installs, along with the kivy dependency.

**Error Log**
[pip_errors.log](https://github.com/pypa/pipx/files/11396625/pip_errors.log)

**Comment by meowmeowmeowcat** [comment]
`kivy` should not be installed with `pipx` as it is a library. Perhaps you will have to create a virtual environment and install `kivy` inside of it instead.

**Comment by meowmeowmeowcat** [comment]
It is filtered out later if the build is successful:
```
$ pipx install kivy
[...]
No apps associated with package kivy. Try again with '--include-deps' to include apps of dependent
packages, which are listed above. If you are attempting to install a library, pipx should not be
used. Consider using pip or a similar tool instead.
```

**Comment by chrysle** [comment]
Then this can be closed, I think.

**Comment by markqvist** [comment]
> `kivy` should not be installed with `pipx` as it is a library. Perhaps you will have to create a virtual environment and install `kivy` inside of it instead.

Why should `pipx` not install `kivy` if it is a dependency for the application being installed? In this case, trying to install the `sbapp` package via `pipx` fails because `pipx` cannot install the `kivy` dependency.

Is it not exactly the point of `pipx` to install the application along with any dependencies in an isolated environment? Or am I missing something?

**Comment by meowmeowmeowcat** [comment]
>  In this case, trying to install the sbapp package via pipx fails because pipx cannot install the kivy dependency.

This works for me. I guess the compilation fails because of your environment?
```
$ pipx install sbapp
  installed package sbapp 0.5.2, installed using Python 3.10.4
  These apps are now globally available
    - sideband
done! ✨ 🌟 ✨
```

**Comment by chrysle** [comment]
I can reproduce that too on my Ubuntu 22.04 (x86_64) system.

**Comment by uranusjr** [comment]
Don’t think there’s anything more in investigate here.

**Comment by markqvist** [comment]
I should have been more specific, it only fails on newly released Debian-based OSes.

If it is a problem with the environment, it will get *very* widespread soon (and probably affect other packages than `kivy`), as this is the default setup for most Debian-based distros going forward.

On a fresh install of Ubuntu 23.04:

```
sudo apt install pipx
pipx install sbapp
```

Results in:

```
Fatal error from pip prevented installation. Full pip output in file:
    /home/user/.local/pipx/logs/cmd_2023-05-04_18.29.24_pip_errors.log

pip failed to build package:
    kivy

Some possibly relevant errors from pip install:
    /tmp/pip-install-9oml_0ej/kivy_4ec9e12e4543476c8eb86ef7adf3680f/kivy/include/gl_redirect.h:72:33: fatal error: GL/gl.h: No such file or directory
    b'/bin/sh: 1: pkg-config: not found\n'

Error installing sbapp.

```

The attached error log in my first post is the complete output from an attempted install on a fresh Ubuntu 23.04 install.

I'd recommend re-opening the issue.

**Comment by chrysle** [comment]
> I should have been more specific, it only fails on newly released Debian-based OSes.
> 
> If it is a problem with the environment, it will get _very_ widespread soon (and probably affect other packages than `kivy`), as this is the default setup for most Debian-based distros going forward.
> 
> On a fresh install of Ubuntu 23.04:
> 
> ```
> sudo apt install pipx
> pipx install sbapp
> ```
> 
> Results in:

The debian package is not maintained by the `pipx` project. 
It may contain bugs already fixed in the upstream project or have other issues.

Have you already tried removing the package, installing `pipx` via `pip` as described [in the docs](https://pypa.github.io/pipx/installation/) and re-running `pipx install sbapp`?

**Comment by markqvist** [comment]
With `pipx` from current head of this repo:

```
$ python3 -m pipx install sbapp

Fatal error from pip prevented installation. Full pip output in file:
    /home/user/.local/pipx/logs/cmd_2023-05-04_21.23.54_pip_errors.log

pip failed to build package:
    kivy

Some possibly relevant errors from pip install:
    /tmp/pip-install-n65e87_a/kivy_271f75fb7795400391066886e143f2fb/kivy/include/gl_redirect.h:72:33: fatal error: GL/gl.h: No such file or directory
    b'/bin/sh: 1: pkg-config: not found\n'

Error installing sbapp.
```

But yes, might still be something related to the dependencies of the Ubuntu `pipx` package.

I don't know how much/little `pipx` is supposed to deal with external build dependencies for packages it installs, but now at least you know that packages like this are breaking in newer versions of Ubuntu, and most probably also other Debian derivatives.
