### ISSUE TITLE
reinstall / reinstall-all does not respect injected packages

### ISSUE THREAD

**Issue by s-n-g** [pypa/pipx#976]
**Describe the bug**
Hi all,
I am trying to use pipx for a project I maintain: [pyradio](https://github.com/coderholic/pyradio) 

I use a custom script to perform the installation, which actually executes

```
cd /path/to/source
pipx install --force .
pipx inject pyradio -r requirements-pipx.txt
```

Then when I execute

```
pipx reinstall pyradio
```

or 

```
pipx reinstall-all
```

the package is installed with no error (but I see nothing about the previously injected packages).

When I try to execute `pyradio` I get modules missing.

This tells me that the installed package is looking for the modules within the virtual environment, and does not finds them (the modules are installed system-wide already, so that's why I know it's looking for them within the v.e.).

How do i go about it?

Should I disallow using `pipx inject` altogether?

**How to reproduce**

1. Download [this ZIP file](https://github.com/s-n-g/pyradio/archive/refs/heads/devel.zip)
2. Unzip, open a terminal, go into the directory created by unzip
3. Execute
```
./devel/build_install_pyradio -i
```

At this point you should be be able to run `pyradio`.

Then,
```
╰─➤  pipx reinstall-all --verbose
pipx >(setup:801): pipx version is 1.2.0
pipx >(setup:802): Default python interpreter is '/usr/bin/python'
pipx >(upgrade:91): Upgrading shared libraries in /home/spiros/.local/pipx/shared
upgrading shared libraries...
pipx >(run_subprocess:173): running /home/spiros/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install --upgrade pip setuptools wheel
pipx >(uninstall:132): removed file /home/spiros/.local/bin/pyradio
pipx >(rmdir:55): removing directory /home/spiros/.local/pipx/venvs/pyradio
uninstalled pyradio! ✨ 🌟 ✨
creating virtual environment...
pipx >(run_subprocess:173): running /usr/bin/python -m venv --without-pip /home/spiros/.local/pipx/venvs/pyradio
pipx >(run_subprocess:173): running /home/spiros/.local/pipx/venvs/pyradio/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:173): running /home/spiros/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:173): running /home/spiros/.local/pipx/venvs/pyradio/bin/python --version
pipx >(_parsed_package_to_package_or_url:147): cleaned package spec: /home/spiros/projects/my-gits/pyradio
installing pyradio from spec '/home/spiros/projects/my-gits/pyradio'...
pipx >(run_subprocess:173): running /home/spiros/.local/pipx/venvs/pyradio/bin/python -m pip install --editable /home/spiros/projects/my-gits/pyradio
pipx >(run_subprocess:173): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:316): get_venv_metadata_for_package: 41ms
pipx >(_parsed_package_to_package_or_url:147): cleaned package spec: /home/spiros/projects/my-gits/pyradio
pipx >(_symlink_package_apps:111): Force is true. Removing /home/spiros/.local/bin/pyradio.
  installed package pyradio 0.9.2.6, installed using Python 3.10.10
  These apps are now globally available
    - pyradio
done! ✨ 🌟 ✨
```

The same if you execute `pipx reinstall pyradio --verbose`

And finally...

```
╰─➤  pyradio
Traceback (most recent call last):
  File "/home/spiros/.local/bin/pyradio", line 5, in <module>
    from pyradio.main import shell
  File "/home/spiros/projects/my-gits/pyradio/pyradio/main.py", line 16, in <module>
    from .radio import PyRadio
  File "/home/spiros/projects/my-gits/pyradio/pyradio/radio.py", line 32, in <module>
    from .config import HAS_REQUESTS, HAS_DNSPYTHON
  File "/home/spiros/projects/my-gits/pyradio/pyradio/config.py", line 18, in <module>
    from .browser import PyRadioStationsBrowser, probeBrowsers
  File "/home/spiros/projects/my-gits/pyradio/pyradio/browser.py", line 22, in <module>
    from .simple_curses_widgets import SimpleCursesLineEdit, SimpleCursesHorizontalPushButtons, SimpleCursesWidgetColumns, SimpleCursesCheckBox, SimpleCursesCounter, SimpleCursesBoolean, DisabledWidget, SimpleCursesString, SimpleCursesWidget
  File "/home/spiros/projects/my-gits/pyradio/pyradio/simple_curses_widgets.py", line 5, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'
```

**Expected behavior**

I would expect the commands `reinstall` / `reinstall-all` (maybe also `upgrade` / `upgrade-all` but I cannot test them atm) to "know" about the packages previously injected to the v.e. and act accordingly to keep them available to the program.

**Comment by s-n-g** [comment]
Just a thought (without knowing the ins and outs of **pipx**)...

Anything **injected** from the shell gets recorded in a `requirements.txt` within the v.e.

Anytime `upgrade`, `upgrade-all`, `reinstall`, `reinstall-all` is executed by the shell, `inject` will be triggered with in v.e. `requirements.txt`

![inject](https://user-images.githubusercontent.com/5807638/236674526-08c17487-e830-414e-bfda-e69d3d2ad12f.png)

**Comment by meowmeowmeowcat** [comment]
> `pipx inject pyradio -r requirements-pipx.txt`

I don't think this command works?

I just checked the script, and it seems like the command that you are using is `pipx runpip pyradio install -r requirements_pipx.txt`. Currently pipx doesn't inject packages listed in `requirements_pipx.txt` after reinstall since they are not stored in `pipx_metadata.json`. See #934 for this feature.

Here's an alternative solution provided in #934:
`cat equirements-pipx.txt | sed -e 's/#.*//' | xargs pipx inject pyradio`

You can use the above command to replace `pipx runpip pyradio install -r requirements_pipx.txt`.

**Comment by meowmeowmeowcat** [comment]
> Just a thought (without knowing the ins and outs of **pipx**)...
> 
> Anything **injected** from the shell gets recorded in a `requirements.txt` within the v.e.
> 
> Anytime `upgrade`, `upgrade-all`, `reinstall`, `reinstall-all` is executed by the shell, `inject` will be triggered with in v.e. `requirements.txt`
> 
This already works if you use `pipx inject` to inject packages.

**Comment by s-n-g** [comment]
You are absolutely right!

I did play around with it and thought I was still using `inject`...
My bad :(
Sorry for the noise...
