### ISSUE TITLE
Feature request: `pipx which/where`

### ISSUE THREAD

**Issue by hacker-DOM** [pypa/pipx#983]
<img width="825" alt="image" src="https://github.com/pypa/pipx/assets/18601956/4e07c51f-f4dc-42a5-b759-a03c528fdf84">

It would be great if we had `pipx which slither` or `pipx where slither`, which would return `/Users/dteiml/.local/pipx/venvs/slither-analyzer/lib/python3.11/site-packages` 🙏

**Comment by hacker-DOM** [comment]
Thanks for that. The closest there seems to be PIPX_LOCAL_VENVS. However,

- it's still not 100% clear how to convert between the executable name and the directory name (eg above, executable = slither but directory = slither-analyzer)
- i will probably forget it in one week and try pipx where again...

I am still in favor of this feature. It would show you the directory where the package that originates this executable is located. Maybe call it `where` rather than `which` to stress that functionality.

**Comment by uranusjr** [comment]
On POSIX you can actually get pretty close with something like `readlink $(which slither)`. It’s probably still a good idea to have something like this (except showing the path to the executable since that’s what `which` and `where` do) since the same is much more difficult on Windows.

**Comment by uranusjr** [comment]
pipx is _specifically_ designed to not treat packages as importable libraries, so no. I’d recommend against doing this in the first place as well.

**Comment by gaborbernat** [comment]
> pipx is _specifically_ designed to not treat packages as importable libraries, so no. I’d recommend against doing this in the first place as well.

We're in the business of creating apps the user can use, not virtual environment manager.
