### ISSUE TITLE
improve https://pypa.github.io/pipx/contributing/ by linking contributing space

### ISSUE THREAD

**Issue by matkoniecz** [pypa/pipx#986]
**How would this feature be useful?**
Would make easier for interested people to find where development happens

**Describe the solution you'd like**
Add link to https://github.com/pypa/pipx at https://pypa.github.io/pipx/contributing/

Note that code of conduct is linked, precommit is linked: but " codebase, issue tracker, chat rooms" has no links

**Describe alternatives you've considered**
Maybe users are expected to google for it?

**Comment by chrysle** [comment]
There is already a link to the GitHub project in the upper right corner. That is quite obvious I think.

**Comment by matkoniecz** [comment]
![screen](https://github.com/pypa/pipx/assets/899988/07eb40d5-8711-4cc6-a499-55343f6e3305)

At least I noticed it only after you pointed it out.
