### ISSUE TITLE
Consider clarifying when "console scripts entry point" is needed

### ISSUE THREAD

**Issue by matkoniecz** [pypa/pipx#987]
Is

> If you would like to make your package compatible with pipx

applying only to app functionality distinct from regular package installs, and can be safely ignored in general?

Or is everyone expected to add "console scripts entry point" to all Python packages (or use `--break-system-packages`)?

**Comment by dukecat0** [comment]
Console script entry point should be added if you want users to be able to run your package's functionality directly from the command line.
