### ISSUE TITLE
https://pypa.github.io/pipx/how-pipx-works/ does not explain how "pipx creates an isolated environment for each application"

### ISSUE THREAD

**Issue by matkoniecz** [pypa/pipx#988]
https://pypa.github.io/pipx/

> pipx creates an isolated environment for each application and its associated packages

https://pypa.github.io/pipx/how-pipx-works/

> create or re-use a shared virtual environment that contains shared packaging libraries pip, setuptools and wheel in ~/.local/pipx/shared/

https://pypa.github.io/pipx/how-pipx-works/ seems to describe that pipx creates second layer of packages, distinct from system packages. But is it achieving "isolated environment for each application"? If yes, how it is doing this? Is it per folder?

Or is it meaning "pipx creates an isolated environment for each user" by "pipx creates an isolated environment for each application"?

**Comment by matkoniecz** [comment]
Yes, but how "isolated environment for each application" is achieved? How pipx tries to guess whether `~/user/Documents/install/foobar` is the same project as `~/user/Documents/install/qwerty` ?

**Comment by dukecat0** [comment]
> how "isolated environment for each application" is achieved?

By using virtual environment.

Why would pipx have to guess whether they are the same project?

**Comment by matkoniecz** [comment]
> By using virtual environment.

It it manually created by user, in way not described at https://pypa.github.io/pipx/how-pipx-works/ ?

> create a Virtual Environment in ~/.local/pipx/venvs/PACKAGE that uses the shared pip mentioned above but otherwise is isolated (pipx uses a [.pth file](https://docs.python.org/3/library/site.html) to do this)

seems to describe creation of a single Virtual Environment per package, not for entire application

Or is by

>  pipx creates an isolated environment for each application and its associated packages
 
at https://pypa.github.io/pipx/

meant "isolated environment for each package and its dependencies"? Not having isolated environment for each software project using bunch of packages?

**Comment by matkoniecz** [comment]
I would expect from how-pipx-works an explanation how pipx works.

I remain confused what "application" even is in this context.

(maybe this page is addressed to people who already know more about how pipx works than me, and is not addressed to people completely unaware how pipx works)

**Comment by gaborbernat** [comment]
> I remain confused what "application" even is in this context.

A Python package that exposes a console script entry point.
