### ISSUE TITLE
drop `setuptools` and `wheel` from shared libs

### ISSUE THREAD

**Issue by graingert** [pypa/pipx#990]
this would fix https://github.com/pypa/pipx/issues/951 and cause pip 23.1 to use the pep517 codepath for all packages

since 23.1 pip doesn't need wheel or setuptools anymore https://pip.pypa.io/en/stable/news/#v23-1

> When the wheel package is not installed, pip now uses the default build backend instead of setup.py install and setup.py develop for project without pyproject.toml. ([#8559](https://github.com/pypa/pip/issues/8559))

setuptools was also removed from CPython 3.12's ensurepip: https://docs.python.org/3.12/whatsnew/3.12.html#removed
> Remove the bundled setuptools wheel from [ensurepip](https://docs.python.org/3.12/library/ensurepip.html#module-ensurepip), and stop installing setuptools in environments created by [venv](https://docs.python.org/3.12/library/venv.html#module-venv).

**Comment by chrysle** [comment]
This would be a whole new concept! Only one shared libraries!

I agree this should be done and will take a look.
