### ISSUE TITLE
How exactly does pipx interact with --system-site-packages?

### ISSUE THREAD

**Issue by ckp95** [pypa/pipx#991]
`pipx install` and `pipx upgrade` have the option:

```
  --system-site-packages
                        Give the virtual environment access to the system site-packages dir.
```

What does "access to" mean exactly? Is it read-only access, or read-write access? i.e. if I run `pipx install --system-site-packages` or `pipx upgrade --system-site-packages`, is there any possibility that it will *modify* my system site packages? Or is it guaranteed to "look but don't touch"?

**Comment by dukecat0** [comment]
It's read-only access. Packages you installed with pipx will only exist in the virtual environment.
