### ISSUE TITLE
installed package can't find system-wide wxpython

### ISSUE THREAD

**Issue by fenugrec** [pypa/pipx#992]
Possibly not a bug. Not sure where the issue is.

**Describe the bug**
Trying to install this, https://pypi.org/project/PySetWacom/ , and for some reason it chokes on importing 'wx' despite wxpython being installed already.

**How to reproduce**
```
$ pipx install pysetwacom
$ PySetWacom
....
ModuleNotFoundError: No module named 'wx'
```

Note, I can manually start an interactive python shell and 'import wx' works just fine.

**Comment by uranusjr** [comment]
pipx does not consider system-wide libraries for isolation. Use `--system-site-packages` if you want to override this behaviour.
