### ISSUE TITLE
Pipx cannot be able to install packages

### ISSUE THREAD

**Issue by Zahedcse** [pypa/pipx#995]
I cannot use pip systemwide in Ubuntu 23.04.
I tried to use pipx to install packages, if I want to install selenium using pipx then the error occurs:

pipx install selenium

**No apps associated with package selenium or its dependencies. If you are
attempting to install a library, pipx should not be used. Consider using pip
or a similar tool instead.**

Also I want to mention:
**If I want to use pip then the error was;**

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

Any proven way to work with pipx?

**Comment by dukecat0** [comment]
Use this solution:
```
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
```

pipx is only used to install command line applications.
