### ISSUE TITLE
pipx ensurepath adds itself multiple times

### ISSUE THREAD

**Issue by tripleee** [pypa/pipx#996]
**Describe the bug**

Running `pipx ensurepath` adds several redundant instances of the `$HOME/.local/bin` directory to my `PATH`. These are harmless as such, but somewhat annoying.

**How to reproduce**

`pipx ensurepath` and examine the end of recently modified files in your home directory.

```
cd
ls -art ~ | tail -n 2 | xargs tail -n 7
```

On a fresh Linux Mint installation, I see this:

```
==> .profile <==
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Created by `pipx` on 2023-06-01 04:10:01
export PATH="$PATH:/home/tripleee/.local/bin"

==> .bashrc <==
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Created by `pipx` on 2023-06-01 04:10:01
export PATH="$PATH:/home/tripleee/.local/bin"
```

On a Mac with Zsh, where I installed `pipx` with `brew`, I see similar behavior with `.zprofile` and `.zshrc`

**Expected behavior**

1. If the file already has a stanza which (conditionally) adds `$HOME/.local/bin` to my `PATH`, ideally, do nothing.
2. Or, at the very least, wrap it so that it doesn't unnecessarily add the same directory to the `PATH` multiple times, like the code in the default `.profile` on Mint (and I imagine Ubuntu) already does.
3. The `export` is arguably useless; the system already exports `PATH`.
4. Ideally, don't modify both files. One or the other is sufficient.

There are complications around how the shell loads its startup files; what exactly it does out of the box and how exactly each OS or distro modifies these files to produce consistent and predictable behavior is rather a can of worms. The "belt and suspenders" approach of adding something to both the `.profile` (or `.bash_profile`, `.zprofile`, etc) and `.bashrc` (or `.zshrc` etc) might thus be defendable if the other symptoms can be avoided.

**Comment by essn** [comment]
Bash on Linux - same thing. It actually overwrites my PATH because of the `export PATH=` statement.. Easy enough to fix - but frustrating. On login, I need to source `~/.bash_profile` in order to have my usual PATH.

**Comment by chrysle** [comment]
> It actually overwrites my PATH because of the `export PATH=` statement..

That's not possible... it just adds itself to the rest of the `PATH`. I'll see if it's possible to avoid the redundance, though.

**Comment by essn** [comment]
Yea, that I think that's a different issue. Correlation, not causation -
realized after posting. That's embarrassing 😬

Agree re redundancy tho.

**Comment by chrysle** [comment]
@tripleee This seems to be an issue of the `userpath` module. I've opened an issue at ofek/userpath#46, but it could take some time until this is tackled.

**Comment by dukecat0** [comment]
I am closing this since there's nothing we can fix here.
